### ISSUE TITLE
Adding a CHANGELOG

### ISSUE THREAD

**Issue by guyisra** [zendesk/ruby-kafka#108]
Would it be possible to add a changelog file so we will know what changed between versions?

thanks

**Comment by dasch** [comment]
I've been thinking about when to do that – basically, at long as the code is alpha level I need the freedom to make changes without too many hurdles. If you're using alpha level code, you better expect some changes and instability. However, I believe the Producer API is reaching beta level. While the API isn't frozen, and I don't plan on freezing it completely before v1.0, now could be a good time to introduce a changelog. Note that for e.g. the new alpha level consumer API I'd probably just write e.g. "changes to the consumer API". Once it's beta I'd describe the changes. Once it's production quality I won't make backwards incompatible changes.

**Comment by dasch** [comment]
Added a `CHANGELOG.md` file.
