### ISSUE TITLE
Allow configuring a consumer for at-most-once processing

### ISSUE THREAD

**Issue by dasch** [zendesk/ruby-kafka#112]
Basically, we'd need to commit the offset before yielding the message to the user block. I'd like to see some concrete use cases first, though.

**Comment by mensfeld** [comment]
Isn't that supported already with manual offset commiting?

**Comment by tcrayford** [comment]
note that… to get at most once,  you have to be very careful about your broker and producer set-up. If this is added, I'd like to see documentation on those.

**Comment by mensfeld** [comment]
@tcrayford  what I've meant is that you could realise committing the offset to Kafka with ```#automatically_mark_as_processed``` before yielding to the user.

**Comment by dasch** [comment]
Closing due to a lack of activity.
