### ISSUE TITLE
Authentication using SASL

### ISSUE THREAD

**Issue by dasch** [zendesk/ruby-kafka#119]
http://kafka.apache.org/documentation.html#security_sasl

**Comment by kzk** [comment]
@dasch Hi, we're running the project called Fluentd (http://www.fluentd.org/), an open source data collector. Currently Fluentd's kafka plugin is contributed by community (https://github.com/htgc/fluent-plugin-kafka), but it uses Poseidon. Apparently it doesn't work with v0.9, and we're exploring the possibility of rewriting it with ruby-kafka. One requirements we hear from Fluentd users are, they want Kerberos support to publish events to Kafka. I just saw this ticket but are you now working on this right now? If not, are you open to merge the changes we'll make? I'm just curious how important this is for you at this point. cc/ @repeatedly

**Comment by dasch** [comment]
@kzk that sounds great! I'm not working on Kerberos support, so by all means go ahead :-)

If you need help we can set up a call – otherwise, a work-in-progress PR could be a good starting point.

**Comment by tmeinlschmidt** [comment]
@dasch I'm on adding SASL (kerberos) to ruby-kafka right now, as we need it. It seems to be working, so I'll create some pull request soon. Have to add support and tests for SASL_SSL then too.

**Comment by jpaskhay** [comment]
@tmeinlschmidt We are also in need of this feature for a project we're working on, so we'd be more than happy to help in whatever capacity possible. We were literally about to start doing this ourselves, so we are very thankful to have seen your comment :) We don't have a strong Ruby background on the team but willing to do what we can to help.

We are not currently using SSL, so we may not be able to assist much there, unfortunately.

**Comment by tmeinlschmidt** [comment]
Hey all, pushed some initial code for SASL/GSSAPI authentication. Working on adding some more tests and docs.

**Comment by dasch** [comment]
@tmeinlschmidt I think that code is being overly intrusive - can you make a change within the confines of the existing design?

Feel free to create a PR with design changes separately, although I won't promise that I'll merge it.

**Comment by tmeinlschmidt** [comment]
The problem is - SASL needs to send some kafka messages before any auth can be made. that's the reason I cut ConnectionOperation out from Connection class. Is there any specific part you want to change/rewrite?

**Comment by dasch** [comment]
@tmeinlschmidt can you start by opening a PR? That makes commenting a lot easier.

**Comment by tmeinlschmidt** [comment]
@dasch opened #334.

**Comment by huhongda** [comment]
@dasch when support the SASL/PLAIN? our team will use kafka replace with redis. I find only your gem support SASL.

**Comment by tmeinlschmidt** [comment]
I would like to add PLAIN to SASL auth then as well.

**Comment by trthomps** [comment]
+1 for SASL/PLAIN

**Comment by theduderog** [comment]
+1 I need SASL/PLAIN support as well.

**Comment by dasch** [comment]
@tmeinlschmidt would you want to head this or should we let one of these enthusiasts give it a go?

**Comment by dasch** [comment]
Done!

**Comment by frencopei** [comment]
any update?now fluentd-plugin-kafa support sasl ?  i saw your comment about ruby kafak. it just provide principal and keytab, not krb5.conf,  how get kerberos server addr without  krb5.conf?

**Comment by xidiandb** [comment]
> any update?now fluentd-plugin-kafa support sasl ? i saw your comments about ruby kafak. it just provides principal and keytab, not krb5.conf, how get kerberos server addr without krb5.conf?

same question

**Comment by theduderog** [comment]
I think it was done here - https://github.com/zendesk/ruby-kafka/pull/370
