### ISSUE TITLE
Determine a partition based on a proc

### ISSUE THREAD

**Issue by guyisra** [zendesk/ruby-kafka#127]
Hey,

Most kafka producer implementation have an ability to decide on the partition based on some supplied logic that depends on a key and the partition count.

It is critical for us to have this ability.

Currently, a partition is created by 
`Zlib.crc32(key) % partition_count`

Would it be possible to have it by a supplied proc and if not supplied, the above will be the default?

I can send a PR, which if a partition.respond_to?(:call) it will calculate it based on the proc

Would that be possible/acceptable?

**Comment by dasch** [comment]
What is your concrete use case? Why is it not sufficient to either 1) determine the partition up front or 2) pass the `partition_key`?

I find the "partitioner" API to be rather bad, and would like to avoid adding it if possible.

**Comment by guyisra** [comment]
we need to calculate the partition number based on a common proc all producer and consumer use

Anyway, I see that the client exposes partitions_for which I think we can use to calculate the partition outside of the gem logic

**Comment by dasch** [comment]
I think that's the best option – I'm not sure how common your use case is, and I'd very much prefer to keep the API as simple as possible for now. The benefit of computing the partition outside ruby-kafka is that you'll have access to the message data before it's serialized, which helps with semantic partitioning, e.g.

```ruby
def publish_event(event)
  partition_count = kafka.partitions_for("my-events")

  # All events for a given user go to the same partition:
  partition = event.user_id % partition_count

  producer.produce(event.to_json, partition: partition, topic: "my-events")
end
```

I think that API is superior to passing a proc.
