### ISSUE TITLE
The last message in each group of fetched messages can have a truncated value

### ISSUE THREAD

**Issue by sdball** [zendesk/ruby-kafka#133]
When I put 100,000 lorem ipsum messages into a topic they can all be retrieved fine from the kafka command line client, but the Ruby Kafka consumer was only getting 99,913 complete messages and 87 incomplete messages.

After a lot of digging I determined that the broker was running 87 requests that received 1148 messages and then one final request that received the remaining 124. The incomplete message was always the last message of each "full-size" batch of 1148.

Setting the `min_bytes` key did not seem to have any effect.

In my testing I've been able to get a consumer to retrieve all 100,000 complete records by adding a value size check to the loop. With this check the incomplete messages are not "processed" and the offset isn't incremented.

```
next unless message.value.size > 800
```

I'm going to keep digging and see if I can find out where the actual cut off is happening. I've done a fair bit of debugging in `fetch_operation.rb` and it looks like the problem is farther in.

```
# fetch_operation.rb#L66
response = broker.fetch_messages(**options) # => exhibits the truncated value problem
```

**Comment by sdball** [comment]
Here's the full lorem value I was using:

```
$ for i in {1..100000}; do echo "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet." >> lorem.txt; done
```

Then I just piped that file into the simple producer.

The truncated values all have 192 bytes and the full messages have 888.

**Comment by sdball** [comment]
It looks directly related to the `max_bytes` setting. If I set `max_bytes` to be 1000 then I receive one complete message and one that only has 60 bytes. Bumping `max_bytes_ to 1001 then I still get one complete message and one that only has 61 bytes.

It's like something along the line (Kafka? The socket connection?) is just truncating right in the response instead of at the edge of a message.

Maybe there's some "end of message" byte marker that could be watched for.

**Comment by sdball** [comment]
This is interesting, from the docs they have an example socket server configuration: https://kafka.apache.org/documentation.html#prodconfig

```
socket.request.max.bytes=104857600
```

That's 100 times the default of 1048576 (typo?). Setting that limit certainly works… but only because it is larger than the response of 100,000 messages.

**Comment by sdball** [comment]
Ah, that socket request is a different setting: the max that the server will allow. The default fetch request size for consumers is definitely 1024*1024.

**Comment by sdball** [comment]
Well here we go! https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-FetchAPI

> As an optimization the server is allowed to return a partial message at the end of the message set. Clients should handle this case.

Hm! I wonder if this is even possible for `ruby-kafka` to recognize or if end user consumers simply need to make the consumer loop smart enough to discard the partial message.

**Comment by sdball** [comment]
Here we go! The message declares the number of bytes to read from the socket. With my example and a `max_bytes` setting of `2000` on the final message in the fetch request the message says to read `888` bytes and the socket only reads `146` bytes. I think that mismatch could be recognized and not returned as a message to iterate over.

**Comment by sdball** [comment]
My debugging in `lib/kafka/protocol/decoder.rb`

```
      def read(number_of_bytes)
        gathered = @io.read(number_of_bytes) or raise EOFError
        puts "number_of_bytes: #{number_of_bytes}"
        puts "read from socket: #{gathered.size}"
        gathered
      end
```

I don't think that's the right level for this check, but it was the first good place I found to hook into to check for the mismatch.

**Comment by sdball** [comment]
Woo! That `EOFError` actually seems to be the thing. If that's raised when the number is a mismatch it all works out.

**Comment by dasch** [comment]
@sdball can you confirm that this is still a problem on the latest master? I've added a check for partial messages within message sets in https://github.com/zendesk/ruby-kafka/commit/c933344cbd829c6d096d93a1dbd12f035b843081

**Comment by sdball** [comment]
I can confirm this is indeed fixed on the latest master!

I updated to master and reran my simple consumer using `tee` to output the messages to a log file. (Which makes it easy to know when to interrupt the consumer after processing all the messages.)

```
$ bundle exec ruby simple-consume.rb earliest | tee logs/consume.log
```

Then counted up unique messages:

```
$ sort logs/consume.log | uniq -c
100000 # (complete lorem ipsum messages)
```

100,000 complete messages, which is exactly right. :rainbow:

**Comment by dasch** [comment]
Awesome! :tada:
