### ISSUE TITLE
ack_timeout and backoff in seconds

### ISSUE THREAD

**Issue by guyisra** [zendesk/ruby-kafka#144]
Is there a specific reason that the unit is seconds and not milliseconds?

**Comment by mensfeld** [comment]
+1 for milliseconds - it used to be like that in Poseidon and to be honest I've used 500ms for some reasons.

**Comment by dasch** [comment]
All timeouts in the Ruby standard library are specified in seconds. I want ruby-kafka to be friendly to Ruby developers new to Kafka. If you need 500ms, just specify 0.5s.
