### ISSUE TITLE
Namespace conflicts

### ISSUE THREAD

**Issue by guyisra** [zendesk/ruby-kafka#145]
Hey,

we use a different gem for the consumer, and there is a naming conflict since both gems (this and the one we use) use the Kafka namespace

Would it be possible to have this gem in a different namespace? (like ZenDesk::Kafka or RubyKafka or ZKafka, or whatever)?

**Comment by dasch** [comment]
Nope, this is using the Kafka namespace. What gem is it conflicting with?
