### ISSUE TITLE
Purge buffered messages for a topic if it doesn't exist

### ISSUE THREAD

**Issue by dasch** [zendesk/ruby-kafka#150]
We ran into this in production: a topic hadn't been properly created in a production environment. Rather than dropping messages to that topic and raising an error, the producer held on to them. Eventually, the producer buffers filled up and new messages were dropped.

There are several options for how to handle this:

* Raise an exception when delivering messages to a non-existing topic. This can be tricky with the async producer.
* Drop messages to the topic and log the error.

**Comment by mensfeld** [comment]
@dasch  what does the "hadn't been properly created" mean? Could you explain it a bit better (I'm interested in this error)

**Comment by dasch** [comment]
I'm not quite sure. We've had both human errors and weird Kafka bugs cause a topic to either not be created or not be available. Our automation and monitoring is still being developed.

**Comment by mensfeld** [comment]
But shouldn't kafka create a topic when the first message is being sent?

**Comment by dasch** [comment]
@mensfeld that's an opt-in feature that should be disabled in most production environments.

**Comment by javinor** [comment]
+1

We encountered a related problem. Our server.properties are configured with ```auto.create.topics.enable=true```
but when publishing to a non-existent topic with get a ```Kafka::LeaderNotAvailable``` error. Creating the the topic before hand in the cluster solve the issue.

How about making topic creation and topic availability checking possible via the gem?

**Comment by dasch** [comment]
@javinor can you expand on the problem? Ruby-kafka _does_ create non-existent topics when they're first written to if `auto.create.topics.enable=true` is set for the cluster. However, there can be a considerable delay between a client requests a topic to be created and there being a leader for all partitions. I would not recommend relying on this in production.

**Comment by dasch** [comment]
If this is not the case, I'd love some code that reproduces the issue – it may be a matter of fetching up-to-date metadata. Please use the latest master.

**Comment by javinor** [comment]
@dasch thanks for the quick response! In our production environments this actually works fine since the topics are already available. I'll try using master and get back to you...

**Comment by javinor** [comment]
I continued to investigate and found the problem, I'll open a separate issue as this is not related to the original issue.

**Comment by MartinNowak** [comment]
The buffering semantics are somewhat annoying for reliable synchronous message producing.
When deliver_messages fails, I need to forward that error anyhow, e.g. as 503 Service Unavailable, b/c having the message in a RAM array can't guarantee delivery. But if I already need to handle retries outside of ruby-kafka anyhow then resending the buffered messages just needlessly produces duplicates.
Also annoying, once the buffer is full it will lead to an error before retrying to send the messages, so now I need to add an additional call to deliver_messages before producing a new message.

```rb
producer.deliver_messages if producer.buffer_size == max_buffer_size
producer.produce(message, topic: 'test')
producer.deliver_messages
```

**Comment by dasch** [comment]
I think your use case is somewhat specific (an HTTP frontend for Kafka). What if a `clear_buffer` method was added to the producer?

```ruby
begin
  producer.produce(message, topic: "test")
  producer.deliver_messages
ensure
  # We never want messages to linger in the producer buffer.
  producer.clear_buffer
end
```

I believe most users would want the producer to hold on to messages and do a best-effort attempt at delivering them. Note that _any_ solution that includes retries will sometimes result in duplicates in the topic – this is unavoidable.

**Comment by tcrayford** [comment]
The JVM producer has a `flush` mechanism that waits until all messages have been consumed.

**Comment by tcrayford** [comment]
Uh s/consumed/produced there. Sorry.

**Comment by tcrayford** [comment]
It's useful in other contexts as well - for example if you're consuming from one stream and producing results to another, you want to flush the producer before marking consumer offsets for reliability.

**Comment by dasch** [comment]
That doesn't sound like the best idea in this case – you wouldn't want to wait indefinitely. The current sync producer does wait, but only until all attempts have been exhausted.

**Comment by dasch** [comment]
Basically, most sync producer scenarios would need a timeout, after which we must decide whether to keep the messages buffered or throw them away. I've opted for the first as the default, and would like the discarding behavior to be an explicit opt-in, e.g. `producer.clear_buffer`.

**Comment by MartinNowak** [comment]
Yes a simple clear_buffer would work here, in fact my code looks like this now.
```rb
begin
  producer.produce(message, topic: "test")
  producer.deliver_messages
ensure
  # We never want messages to linger in the producer buffer.
  producer.instance_variable_get(:'@buffer').clear
  producer.instance_variable_get(:'@pending_message_queue').dequeue_each{}
end
```
https://github.com/zendesk/ruby-kafka/pull/157

**Comment by dasch** [comment]
The original error has been mitigated by #159, so I'll close this.
