### ISSUE TITLE
No exception raised when `assign_partitions!` fails

### ISSUE THREAD

**Issue by MartinNowak** [zendesk/ruby-kafka#153]
`deliver_messages` silently (only logs an error) fails when `assign_partitions!` doesn't succeed.
https://github.com/zendesk/ruby-kafka/blob/cd406829bad3b3d8f5e9bff0bb87eb3c72c67e0d/lib/kafka/producer.rb#L334-L337
https://github.com/zendesk/ruby-kafka/blob/cd406829bad3b3d8f5e9bff0bb87eb3c72c67e0d/lib/kafka/producer.rb#L310-L314
Messages still in `@pending_message_queue` might get lost after deliver_messages returns.

**Comment by dasch** [comment]
Can you reproduce message loss? `@pending_message_queue` was built to be resistant to message loss: https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/pending_message_queue.rb

Basically, we need to accept that exceptions will happen as part of the normal operation – nodes will come and go. The producer should handle most of this: it's not just a thin wrapper around a Kafka produce request, it's a stateful buffer of messages.
