### ISSUE TITLE
.partitions_for method and auto-create topics don't work well together

### ISSUE THREAD

**Issue by javinor** [zendesk/ruby-kafka#155]
We encountered a problem with the ```Kafka::Producer```. We have several services that publish to specific topics, each with a different number of paritions and different partition keys. 

Our production and staging environments work fine because the Kafka clusters are already defined and running. 

Our CI on the other hand uses docker images for integration tests between services, and specifically the Kafka cluster is set up with the auto-create topics flag set to true (which is not suitable for production environments).

Before publishing we use the number of partitions for each topic for our hashing function. When calling ```.partitions_for``` if the topic is not created ahead of time raises a ```Kafka::LeaderNotAvailable``` error.

These unveils two problems:

1. The call to ```.partitions_for``` does cause the topic to be created, but consecutive calls to ```.partitions_for``` still raise the error (I'm not sure why this happens).
2. There's no way around this in ruby-kafka. Topics can't be created via the gem, and we're forced to create ahead of time the topics, which makes the auto-create topics flag irrelevant. 

I'd recommend either making available an API for creation of topics, or maybe having ```.partitions_for``` return the default value for auto-created topics? it's called ```num.partitions``` in the configuration (see [here](https://kafka.apache.org/08/configuration.html))

WDYT?

**Comment by dasch** [comment]
Unfortunately, there's no explicit API for creating topics in the Kafka protocol, at least until [KIP-4](https://cwiki.apache.org/confluence/display/KAFKA/KIP-4+-+Command+line+and+centralized+administrative+operations) has been implemented. The current way topic autocreation works is that you issue a metadata request asking for information about the topic – if autocreation is enabled, it will be created at that point. Unfortunately it may take a little while for a leader to be elected for each partition, in my experience up to 30 seconds if you have multiple brokers.

In this case, however, we may get around that, as you may not need there to even be a leader.

**Comment by dasch** [comment]
This seems to be a tricky one. I tried rescuing the exception and returning the count of the partitions in the metadata response, but just after creation there are no partitions set up – so the partition count is zero.

Since explicit admin APIs are coming in Kafka, I'd rather not add too much code in support of that, but there's a hack you _could_ try:

```ruby
loop do
  begin
    kafka = Kafka.new(...) # Create a new Kafka instance to get around caching.
    partitions = kafka.partitions_for("my-topic")
    return partitions if partitions != 0
  rescue Kafka::LeaderNotAvailable
    # Not yet created.
  end
end
```

**Comment by dasch** [comment]
@javinor closing this as there hasn't been any activity. Feel free to write if you want me to take a look at this again.
