### ISSUE TITLE
Can't produce async messages

### ISSUE THREAD

**Issue by fbjork** [zendesk/ruby-kafka#162]
I tried adding the example configuration for async producing of messages to an initializer in my Rails app as follows:

```ruby
$kafka = Kafka.new(seed_brokers: ['localhost:9092'], logger: Rails.logger)

$kafka_producer = $kafka.async_producer(delivery_interval: 1)

at_exit { $kafka_producer.shutdown }
```

Nothing happens when I try to produce a message from my Rails console. 

If I instantiate a new producer it works however. Any ideas?

**Comment by dasch** [comment]
Can you provide a log file?

**Comment by dasch** [comment]
Also, can you try this using the latest release?

**Comment by fbjork** [comment]
The problem is that there are no logs at all when I use the global variable. Even with instrumentation. I'm on version 0.3.4 already.

This is a Rails 4.2 app if it helps.

Any orher information I can send?

**Comment by dasch** [comment]
Try with this logger:

```ruby
logger = Logger.new(STDOUT)
```

**Comment by dasch** [comment]
Try also removing the `at_exit` statement and see if that helps.

**Comment by fbjork** [comment]
Switching out the logger and removing `at_exit` didn't do anything. Still silent. It works fine if I instantiate a new producer from the rails console, but not using a global variable.

**Comment by fbjork** [comment]
Note that the global variable says it's `dead`:

```ruby
[7] pry(main)> $kafka_producer
=> #<Kafka::AsyncProducer:0x007fdfabaf6648
 @max_queue_size=1000,
 @queue=#<Thread::Queue:0x007fdfabaf65f8>,
 @worker_thread=
  #<Thread:0x007fdfabaf6580@/Users/fredrik.bjork/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.4/lib/kafka/async_producer.rb:80 dead>>
```

**Comment by dasch** [comment]
Hmm, that's funky. Does it work as expected in dev, test, and prod? That is, outside of the console?

**Comment by dasch** [comment]
What happens if you increase `delivery_interval`?

**Comment by dasch** [comment]
Hmm, I have an idea – this could be due to Spring. If the producer is instantiated in one process, but the console forks off another process, then the worker thread probably dies. I guess a better solution then would be to wrap the producer and instantiate it lazily, e.g.

```ruby
module KafkaProducer
  class << self
    def instance
      Thread.current[:kafka_producer] ||= init_producer
    end

    private

    def init_product
      kafka = Kafka.new(...)
      kafka.async_producer(...)
    end
  end
end
```

This would delay the initialization such that it's done in the child process, and would also ensure that multi-threaded servers would not cause problems.

Can you try out that approach? If it works I'll update the README.

**Comment by fbjork** [comment]
Ok, confirmed that it's working when I run a regular `rails s` process using WEBrick. However it doesn't work when the process is forked, i.e spring or Pow.

**Comment by dasch** [comment]
The original code or the snippet above?

**Comment by fbjork** [comment]
The original code works when I run `rails s` with WEBrick, but not when forked.

**Comment by dasch** [comment]
Okay, that makes sense. I think the only proper solution is to initialize the producer lazily. Can you try out the snippet in the comment above?

**Comment by fbjork** [comment]
Yep, works like a charm! (Note the typo in the private method `init_product`).

**Comment by dasch** [comment]
Heh, my bad :-) note that you should still make sure to set an `at_exit` shutdown hook, e.g.

```ruby
def init_producer
  kafka = Kafka.new(...)
  producer = kafka.async_producer(...)
  at_exit { producer.shutdown }
  producer
end
```

**Comment by tcrayford** [comment]
@dasch maybe `ruby-kafka` could lazily initialize the ruby thread itself? Or alternatively, track the pid in the connections like https://github.com/redis/redis-rb/blob/3ae7fbda312caba5668bedd2ecd1ab15ff0d975e/lib/redis/client.rb#L344 does

**Comment by dasch** [comment]
If it can be done without adding too much complexity...

**Comment by dasch** [comment]
@fbjork can you try out #166 and see if that fixes the problem without any additional code?

**Comment by fbjork** [comment]
@dasch yep, works like a charm in a Rails console and Unicorn!

**Comment by dasch** [comment]
:heart:
