### ISSUE TITLE
Ability to repair client connection

### ISSUE THREAD

**Issue by guyisra** [zendesk/ruby-kafka#170]
As with the .partitions_for issue (for example) if a producer tries to publish to a topic that doesn't exist it fails and that information keeps staying on the client unless it is closed and reopened.

Is there currently a way to have an existing client do a refresh of some kind so I won't have to close it an reopen a new one?

The reason I am asking is that we are using https://github.com/mperham/connection_pool to have a pool of kafka connections lazy-loaded to alleviate from the time it takes to open a new connection for each event published. If one of those clients fails for any reason, I would rather have the connection to be self-repairing than close it and reopen a new one

**Comment by dasch** [comment]
I'm not sure I follow – you're using a pool of Kafka client objects? The client already keeps an open connection to each broker (lazily initialized), so there shouldn't be any connection setup when sending a message, aside from the first time.

Is the error you're experiencing that after writing to a topic that doesn't exist, the client doesn't notice when the topic is actually created? It's supposed to do that, so that would be a bug. Do you have some code that can reproduce the issue?

**Comment by guyisra** [comment]
The code will be something like this (I will put a workable code soon, but hopefully this will help to start understanding the issue)

```
kafka_client = Kafka.new(..)
# tries to use partitions_for
kafka_client.partitions_for("mytopic")
# at this stage, the topic exist since partitions_for creates it, but only to the kafka broker. The kafka client is completely unaware of this

producer = kafka_client.producer(..)
producer.produce(...)
producer.deliver_messages
# publish would fail at this point
new_kafka_client = Kafka.new
producer2 = new_kafka_client.new(..)
producer2.produce(...) # same event as before
producer2.deliver_messages
# publish should work
```

so essentially, I would either want a way to tell the client to forget everything it knows and refresh (currently I do that by just creating a new client, overriding the old one) or to have a mechanism that will catch errors and heal the connection

btw, the client keeps an open connection, but it gets instantiated per request, so we try to use connection pool to work around that

**Comment by dasch** [comment]
First of all, unless you're using a threaded server I'd just initialize a single producer when booting the app, e.g.

```ruby
# config/initializers/kafka.rb
$kafka = Kafka.new(...)
$kafka_producer = $kafka.producer(...)
```

Secondly, it makes sense that `deliver_messages` will fail – but unless you've disabled retries (`max_retries`) the producer _should_ refresh that information automatically.

**Comment by guyisra** [comment]
Yea, we are using a threaded server

as for the max_tries, it doesn't succeed, no matter the configuration, (max_retries 100 and retry_backoff as 1 second)

I would expect that no retry is needed since the partitions_for told the broker to create the topic, so the client should have knowledge on the new topic

**Comment by dasch** [comment]
Yeah... the topic is created asynchronously and it usually takes a while, so the client won't know about it. The producer _should_ have marked the cluster info as stale, prompting a refresh. I'll look into it.

**Comment by dasch** [comment]
Does it work if you _don't_ call `partitions_for` first?

**Comment by dasch** [comment]
I may have found the issue. Can you try against #175?

**Comment by guyisra** [comment]
The problem is in the partitions_for. I must call partitions_for, since I need to know how many partitions are for the topic

it seems that once calling `client.partitions_for("new_topic")`, it gets added to @target_topics yet either refresh_metadata isn't getting called, or it gets called too soon perhaps? 

looking at the @toptics of cluster_info it has 

`#<Kafka::Protocol::MetadataResponse::TopicMetadata:0x007ff04e915fa0 @partitions=[], @topic_error_code=5, @topic_name="new_topic">]` which is different than other topics..

**Comment by dasch** [comment]
The error code should cause the producer to refresh its metadata... I'll look at this again tomorrow.

**Comment by dasch** [comment]
@guyisra I'm not able to reproduce this. The following code works for me:

```ruby
kafka.partitions_for("unknown-topic") rescue nil
producer = kafka.producer(max_retries: 5, retry_backoff: 5)
producer.produce("hello", topic: "unknown-topic")
producer.deliver_messages
```

Can you provide an example that reproduces the issue reliably?

**Comment by guyisra** [comment]
perhaps the failing is always in the partitions_for. Since here you rescue the Kafka::LeaderNotAvailable error, yet continue normally, it does work.

For my setup, I need to send to a specific partition which will be select based on a calculation, so I must get a result for partitions_for.

However, it would be logical that if a topic is created on the fly it will have the default partition, and by the kafka documentation is 1. Does ruby-kafka use such defaults? or have such constants as default?

**Comment by dasch** [comment]
@guyisra I may have discovered the issue – I guess you're not even proceeding to produce messages until you can get the partition count?

The following code would never work:

```ruby
begin
  partitions = kafka.partitions_for(topic)
rescue Kafka::Error
  retry
end
```

I updated #175 to make sure that an error in `partitions_for` invalidates the cached cluster info, so the above code will now work. Can you confirm that it fixes your issue?

**Comment by dasch** [comment]
> However, it would be logical that if a topic is created on the fly it will have the default partition, and by the kafka documentation is 1. Does ruby-kafka use such defaults? or have such constants as default?

There's currently no way for the client to specify the configuration of a topic that should be auto-created, or indeed whether or not to auto-create a topic – merely asking for the metadata will auto-create the topic with the default config. I believe a future version of Kafka will add separate APIs for creating topics with control over configuration.

**Comment by guyisra** [comment]
The above #175 retries forever, even with sleep before the retry

**Comment by dasch** [comment]
Even with the new and updated code? Make sure to reference the exact commit.

**Comment by dasch** [comment]
0ca4bb1c8ac7009197d37e9afa7f33e76026d37f

**Comment by guyisra** [comment]
yea, still doesn't work unless I create a new client

**Comment by guyisra** [comment]
however, if I try it on a different topic, the first not working topic does work (yet the second still doesn't work, unless I do a third..)

**Comment by dasch** [comment]
It would just seem that this spec should be able to replicate the error then: https://github.com/zendesk/ruby-kafka/pull/175/files

How many times are you retrying?

**Comment by guyisra** [comment]
Well, checking this standalone it does seems to fix the issue.

I seem to have some kind of a rails problem where doing the same exact thing from within the app does not work, either a bundler issue, or some weird caching of the gem... not sure what is going on. I'll try to resolve it and open a new ticket if there more problems concerning the matter.

Can you please release this fix in a new version of the gem? 

Thanks for the effort and fixing this!

**Comment by dasch** [comment]
:heart:

**Comment by dasch** [comment]
Can you try to get it working in the Rails app first? If there's another bug with regards to integrating with Rails I'd like to get that fixed before cutting another release.

**Comment by guyisra** [comment]
The problem was resolved, it was my fault. 

I am using Retryable, though, so it won't retry forever

Thanks again!

**Comment by dasch** [comment]
:heart:

**Comment by guyisra** [comment]
please don't forget about the release :)
