### ISSUE TITLE
InvalidSessionTimeout when setting session timeout > 30

### ISSUE THREAD

**Issue by dremex** [zendesk/ruby-kafka#186]
When setting the "session_timeout" for a consumer, I'm unable to set a value > 30. Is there an additional configuration piece I'm missing?

`kafka.consumer(group_id: "consumer-group", session_timeout: 35)`

`/Users/kerry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.7/lib/kafka/protocol.rb:50:in `handle_error': Kafka::InvalidSessionTimeout (Kafka::InvalidSessionTimeout)
	from /Users/kerry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.7/lib/kafka/consumer_group.rb:105:in `join_group'
	from /Users/kerry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.7/lib/kafka/consumer_group.rb:35:in `join'
	from /Users/kerry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.7/lib/kafka/consumer.rb:201:in `join_group'
	from /Users/kerry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.7/lib/kafka/consumer.rb:205:in `fetch_batches'
	from /Users/kerry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.7/lib/kafka/consumer.rb:101:in `block in each_message'
	from /Users/kerry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.7/lib/kafka/consumer.rb:183:in `consumer_loop'
	from /Users/kerry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.7/lib/kafka/consumer.rb:100:in `each_message'
	from kafkaConsumer.rb:20:in `<main>'`

**Comment by tcrayford** [comment]
The broker also specifies a max session timeout, which by default is 30 seconds. That's likely what you're hitting.

**Comment by dremex** [comment]
Ah yes, I was able to set my "group.max.session.timeout.ms" kafka config value.

Thanks
