### ISSUE TITLE
Make FetchOperation#execute handle Kafka::ConnectionError

### ISSUE THREAD

**Issue by mrkamel** [zendesk/ruby-kafka#194]
My consumer is running into an infinite loop when the current kafka leader breaks (i.e. is shut down, has no connection, etc) even though a new leader is elected and up. This is happening, because FetchOperation#execute doesn't handle Kafka::ConnectionError to mark the cluster info as stale.

See: https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/fetch_operation.rb#L93

My consumer:

```ruby
client = Kafka.new(:seed_brokers => [...], :client_id => "consumer")

offset = :earliest

loop do
  begin
    messages = client.fetch_messages(:topic => "standard", :partition => 0, :offset => offset, :max_wait_time => 8)

    messages.each do |message|
      puts message.value
    end 

    offset = messages.last.offset + 1 if messages.size > 0 
  rescue => e
    puts e
    puts e.backtrace

    sleep 5
  end 
end
```

When i add Kafka::ConnectionError to the list of handled exceptions, everything is working fine and the consumer remains working using the newly elected leader.

Would be nice if Kafka::ConnectionError would be added.

Thanks

**Comment by dasch** [comment]
Can you create a PR?

**Comment by mrkamel** [comment]
done
