### ISSUE TITLE
0.10.0.0 server fails to process snappy compressed producer messages

### ISSUE THREAD

**Issue by MartinNowak** [zendesk/ruby-kafka#200]
Something about processing snappy compressed messages breaks w/ 0.10.0.0.
According to http://kafka.apache.org/documentation.html#upgrade_10_performance_impact the broker translates messages from/to older clients, but maybe that isn't working (I also received 0.10.0 messages from a broker).
With 0.10.0.0 the messages are no longer recompressed by the server which might be another cause for this issue.
I've also filed this issue as [[KAFKA-3764] Error processing append operation on partition - ASF JIRA](https://issues.apache.org/jira/browse/KAFKA-3764).

**Comment by dasch** [comment]
Can you provide some code that reproduces the problem?

**Comment by dasch** [comment]
This could be a lack of vigilance around the `attributes` field in the message struct...

**Comment by dasch** [comment]
@MartinNowak do you have an update on this?

**Comment by dasch** [comment]
Seems to have been a problem in Kafka.
