### ISSUE TITLE
Return the number of messages delivered 

### ISSUE THREAD

**Issue by grantr** [zendesk/ruby-kafka#201]
`deliver_messages` always returns nil. Can it return the number of messages delivered? This would be helpful for synchronous use cases.

**Comment by dasch** [comment]
I'm not sure I want the sync and async producer APIs to diverge too much – can you give an example of what you would use this for?

**Comment by dasch** [comment]
Also, note that `#buffer_size` returns the number of messages buffered, so you could do:

```ruby
begin
  message_count = producer.buffer_size
  producer.deliver_messages # you'll get an error
  message_count
rescue
  0
end
```

**Comment by grantr** [comment]
That's a good enough workaround, thanks @dasch!
