### ISSUE TITLE
Flushing producer on rails shutdown / producer deallocation

### ISSUE THREAD

**Issue by pctj101** [zendesk/ruby-kafka#204]
It's pretty clear how to get kafka going in rails:
https://github.com/zendesk/ruby-kafka#producing-messages-from-a-rails-application

However it's not yet clear how to ensure the producer queue gets flushed when the application gets shutdown.  

The integration point for this could be different depending on the rails server depending on whether the producer is unique per thread, or unique per process.

Another perspective is to simply consider this a case of the producer trying to manage itself and use some kind of object handing.

From: http://stackoverflow.com/questions/27626897/how-can-i-ensure-an-operation-runs-before-rails-exits-without-using-at-exit
```
ObjectSpace.define_finalizer(YOUR_RAILS_APP::Application, proc {puts "exiting now"})
```

Something like an END handler may execute after the object gets garbage collected (not sure)
```
 END { puts "exiting again" } 
```

Perhaps rather than making a finalizer on the rails app, it's better to put a finalizer on the producer itself.

Any suggestion / comments?

**Comment by dasch** [comment]
The section you're linking to includes this:

```ruby
# Make sure to shut down the producer when exiting.
at_exit { $kafka_producer.shutdown }
```

Does that not work for you?

**Comment by pctj101** [comment]
Looks like there's a bit of consideration before using at_exit as a hook:
http://blog.arkency.com/2013/06/are-we-abusing-at-exit/

Have you seen any pros/cons to using the at_exit approach with respect to this gem?

**Comment by dasch** [comment]
I've been using it in production for a while now and haven't seen any issues.
