### ISSUE TITLE
Handle errors in the consumer processing code without crashing

### ISSUE THREAD

**Issue by dasch** [zendesk/ruby-kafka#206]
Given this snippet:

``` ruby
consumer.subscribe("topic-a")
consumer.subscribe("topic-b")

consumer.each_messsage do |message|
  case message.topic
    when "topic-a" then puts "OK"
    when "topic-b" then raise "OH NO!"
  end
end
```

When the above consumer runs, the user code handling messages in `topic-b` will raise an exception, causing the entire consumer to crash. In some cases, this may be the best policy. I feel, however, that there's a case to be made for allowing the consumer to continue with the topics that do not cause failures.

I see a few valid configuration options that would apply to a single topic:
- `crash` – the existing default, crash the entire consumer.
- `drop_message` – skip the message that caused the exception.
- `block_topic` – temporarily ignore the topic, resuming processing of it later.

The specific use case I have is a single consumer that subscribes to multiple topics on behalf of a set of subscribers and delegates processing to them, something like:

``` ruby
subscribers = {}

subscribers["topic-a"] = [subscriber1, subscriber2]
subscribers["topic-b"] = [subscriber3]

subscribers.keys.each {|topic| consumer.subscribe(topic) }

consumer.each_message do |message|
  subscribers.fetch(message.topic, []).each {|subscriber| subscriber.call(message) }
end
```

In this case, I wouldn't want a bug in one of the subscribers to stop other subscribers from continuing – unless they subscribe to the same topic, in which case they'll have to wait.

I'm not quite sure this is the right direction, though. It may be better to just have a separate consumer per subscriber, although the number of consumer groups could quickly balloon.

**Comment by jacobat** [comment]
Does this need to be a concern of this library? It would appear more flexible to allow users to implement whatever exception handling scheme they see fit. I suppose this leaves the question of how to mark which messages have been processed?

**Comment by osheroff** [comment]
I tend to think a crash in the consumer should be mostly a crash, but I can see the benefits of the `block_topic` semantics.  What about something like:

```
consumer.each_messsage do |message|
    case message.topic
    when "topic-a" then puts "OK"
    when "topic-b" then 
      begin
         # some code that might raise occasionally
      rescue StandardError => e
          message.backoff!(backoff_time: 50) # milliseconds
      end
  end
end
```

which tells ruby-kafka "I can't process this message now, so give it to me again for retry in a bit"

**Comment by dasch** [comment]
@jacobat 
> Does this need to be a concern of this library? It would appear more flexible to allow users to implement whatever exception handling scheme they see fit. I suppose this leaves the question of how to mark which messages have been processed?

Indeed. The "message processed" semantics are based on the block not raising an exception.

**Comment by dasch** [comment]
@osheroff that would make the implementation much harder, I'm afraid – you'd need some kind of threading model to make that work :-/ What would be the impact of having, say, a dozen Kafka consumer groups per application? I could just start a consumer for each subscriber in a separate thread...

**Comment by dansimpson** [comment]
I think the user should be responsible for handling exceptions, but some semantics for managing commits and retries would help.  I like the API @osheroff proposed, in that is "pauses" processing on a given topic, at the control of the developer, but may I suggest, if a retry utility is added, that there be a retry policy?

```ruby
consumer.subscribe("topic", retry_policy: {
  max_retries: 4,
  backoff_millis: 100,
  backoff_strategy: :exponential,
  backoff_strategy: lambda { |count, duration| [duration ** count, 5000].min }
})

message.retry # makes use of the retry policy, tracks count for strategy lambda
```

It's an option.  I think this can all be done outside the scope of the consumer, assuming a single subscription.  Otherwise you will need a threading model or something like eventmachine.

**Comment by dasch** [comment]
Yeah... at that point I think it's too complex.

The issue I want resilience to is the code not being able to handle a specific message, e.g. due to a missing field or something. No amount of backoff is going to fix that. I basically want to be able to proceed processing all the partitions that do not contain problematic messages while the developers create and deploy a fix, then resume the partition once the fix is in place.

**Comment by dansimpson** [comment]
Agreed.  Keep in mind that there may be implementations which favor dropping messages, in favor of keeping consumer lag low.

I have a case where I want to do both, depending on the error.  If my process can't access a database due to networking/failure/etc, I want to pause processing.  On the other hand, if an exception is thrown in my processing code due to bad input, I want to drop the message and log the exception.

I can do that with the current implementation, since I am only consuming a single topic, using sleep.

**Comment by dasch** [comment]
I should probably have a more concrete example first. One use case could be a job queue. In the case of e.g. Resque, a job is "failed" if it raises an exception. In that case it's automatically placed in a separate queue so that it doesn't block the rest of the jobs. I guess a Kafka based job queue could do the same:

```ruby
consumer.subscribe("jobs")

consumer.each_message do |message|
  job = JSON.parse(message.value)
  handler = JobHandler.find(job["name"])

  begin
    handler.call(job)
  rescue Exception => e
    failed_job = { job: job, exception: e.to_s }
    producer.produce(JSON.dump(failed_job), topic: "failed-jobs")
    producer.deliver_messages
  end
end
```

Even then, it would be nice if the above consumer could subscribe to _both_ `jobs` _and_ `failed-jobs`, with the latter having a policy of `block_topic`. That would allow other jobs to complete while allowing developers to deploy a fix.

**Comment by dasch** [comment]
> Agreed. Keep in mind that there may be implementations which favor dropping messages, in favor of keeping consumer lag low.
>
> I have a case where I want to do both, depending on the error. If my process can't access a database due to networking/failure/etc, I want to pause processing. On the other hand, if an exception is thrown in my processing code due to bad input, I want to drop the message and log the exception.
>
> I can do that with the current implementation, since I am only consuming a single topic, using sleep.

Using `sleep` is actually a bit tricky here, since the consumer needs to send out a periodic heartbeat, and that's only done once the block returns. If it fails to send a heartbeat within the session timeout, the partitions will be allocated to another consumer.

In the Java library there's the notion of pausing and resuming topics. That could very well be the best solution, but I'm not sure I want to burden the user code too much with these decisions...

In your example, you could achieve what you want like this, given the original API proposal:

```ruby
consumer.subscribe("some-topic", exception_policy: :block_topic)

consumer.each_message do |message|
  begin
    process_message(message)
  rescue NetworkTimeout, SomethingElse
    # Raising the exception here will cause the topic to be paused.
    raise
  rescue Exception => e
    logger.error "Dropped message #{message.offset}: #{e}"
  end
end
```

Maybe if Consumer exposed e.g. `#pause` and `#resume`, the exception policy could be made rather flexible:

```ruby
class TemporaryPausePolicy
  def initialize(consumer)
    @consumer = consumer
  end

  def call(message, exception)
    @consumer.pause(duration: 30)
  end
end

consumer.subcsribe("x", exception_policy: TemporaryPausePolicy)
```

**Comment by dasch** [comment]
I wonder if at this point it would be better to expose a `#poll` method akin to the one in the Java API.

**Comment by dasch** [comment]
Maybe the answer is to add a low-level API rather than making assumptions in a high-level API:

```ruby
consumer = kafka.consumer(group_id: "worker")

consumer.subscribe("jobs")

loop do
  batches = consumer.poll

  batches.each do |batch|
    begin
      batch.messages.each do |message|
        attempt = 1
        
        begin
          process_message(message)
          consumer.mark_as_processed(message)
        rescue => e
          if attemp <= max_attempts
            attempt += 1
            retry
          else
            raise
          end
        end
      end
    rescue => e
      consumer.pause(batch.topic, batch.partition, duration: 30)
    end
  end
end
```

**Comment by osheroff** [comment]
what's the semantics of `pause`?  The difficulty here is really around the `batches` -- there could be 1k messages in the batch for that topic-partition, and you don't want to hit the error case for each of those before you enter a pause-state; ideally you hit the first bad message for a topic-partition, and that causes back-pressure on any inflight messages too.  This *could* be pulled off in a block like this, but it seems like a lot of trickery would be involved in sending the batch back into the queue...

**Comment by dasch** [comment]
@osheroff for ruby-kafka I would imagine that pausing a partition places it on a special _pause list_, causing the consumer to not fetch messages for it. The partition will still be _assigned_ to the consumer, though. After some timeout expires, the partition is removed from the pause list again.

As for the batch: the consumer keeps track of the highest offset marked as processed – it doesn't care that it has already yielded an entire batch, only messages marked as processed are considered "done". So after a partition is resumed, it would start from the last processed offset + 1.
