### ISSUE TITLE
How do I reset the the consumer group offset

### ISSUE THREAD

**Issue by rayjohnson** [zendesk/ruby-kafka#217]
In some cases I need a consumer group to reprocess a topic from the beginning. Is it possible to reset the offset for this case?

**Comment by dasch** [comment]
There's no explicit API for this. I'd recommend versioning your group id, e.g. `my-group-v3`. Each group id has its own offset tracking.

**Comment by dasch** [comment]
In the future I may add support for seeking within partitions, among other reasons in order to support external offset management, but for now I'm closing this.

**Comment by psycotica0-shopify** [comment]
For other future people like myself, there appears to be a `seek` method now to do this.
