### ISSUE TITLE
Ending read loop if no more messages

### ISSUE THREAD

**Issue by rayjohnson** [zendesk/ruby-kafka#218]
I'm trying to figure out how to end if I have read all of the messages off my topic.  Right now I'm stuck in messages.each loop - blocked while it waits for more messages.  However, for my app I'd to get out of the loop and do other stuff.  Is there a way to do this?

**Comment by dasch** [comment]
Not in a nice way, no – what kind of API would you like to see? And is this for the balanced consumer `kafka.consumer` or just the `fetch_messages` API?

**Comment by dasch** [comment]
With `fetch_messages` you can simply check if the returned array is empty:

```ruby
loop do
  messages = kafka.fetch_messages(...)
  break if messages.empty?
  messages.each do |message|
    ...
  end
end
```

I'm working on an experimental non-balanced consumer API:

```ruby
kafka.each_message(topic: "yolo") do |message|
  ...
end
```

I'd like to maybe add a stop-at-end-of-topic option to it.

**Comment by rayjohnson** [comment]
I did not know about the fetch_messages API.  Turns out that is exactly what I needed for this one use case.  Thank you!

However, for my other use case the consumer API is way better.  One thing I'd like to eventually deal with is how to shut down gracefully.  The data this app listens to is more like a drip - not a river.  So I may not (in a timely way) be able to look for a shut down message when not blocked.

So if we want to shut down the service - for maintenance, etc.  I will need a way to more gracefully break out of the loop than killing the process.  Might send a different SIG or something.  Maybe a timeout that returns an empty message set after a certain amount of time.  The stop at end of topic option would certainly work.  Not sure - cause I'm right now more worried about getting something working than maintaining it...  ;)

**Comment by dasch** [comment]
If you're using the Consumer API there's already a way to stop a consumer instance:

```ruby
consumer = kafka.consumer
consumer.subscribe("some-topic")

# Shut down the consumer on SIGTERM.
trap("TERM") { consumer.stop }

consumer.each_message do |message|
  ...
end
```

**Comment by mensfeld** [comment]
@dasch Graceful shutdowon does not work when we're not yet connected. I mean it works but it will run until we're connected and then it will shutdown. Which means that up until it is connected and consuming, there's no way for graceful shutdown.

**Comment by dasch** [comment]
Closing due to a lack of activity.

**Comment by ruchivijaywargia** [comment]
consumer.stop does not seem to be working for me. Can you tell me how do I break the loop?

**Comment by mensfeld** [comment]
@ruchivijaywargia kill it.

**Comment by vitalyk** [comment]
I'm facing same issue with endless loop. Is there possible way from exiting 
`consumer.each_message` since the time it was raised?
