### ISSUE TITLE
Retrieve Latest Offset for Partition

### ISSUE THREAD

**Issue by dstrelau** [zendesk/ruby-kafka#225]
Hi there! I'm attempting to migrate some code from Poseidon, and one feature I can't figure out how to replicate is fetching the latest offset for a partition.

Normally, I'd fetch the `:ealiest` message in the partition and use the `highwater_mark_offset` from the response, but I can't figure out a way to do this easily. It _seems_ like that highwater mark is only accessible in the `FetchedBatch` response, and I can't figure out a way to get to it.

Both `Client#fetch_messages` and `Client#each_message` map to only the `messages` inside the batch, not the batch itself.

`Consumer#each_batch` seems to give me those batches back, but it seems crazy to go through that just to do a simple single fetch.

If all my above assumptions are correct, would you be open to a PR that adds `Client#fetch_batch`, which basically does `fetch_messages` but skips the `flat_map`?

**Comment by dasch** [comment]
What's your reason for wanting to fetch the latest offset?

**Comment by dstrelau** [comment]
I have some monitoring/dashboarding type use-cases where I need to understand the state of consumers vs the latest offsets on each partition.

**Comment by dasch** [comment]
Are your monitors separate from the consumers themselves? It's not documented yet, but [`kafka/datadog`](https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/datadog.rb) is an example of reporting e.g. consumer lag to a dashboard system, in this case Datadog. Events are published to the Active Support Notifications bus, and can easily be subscribed to.

This is of course all based on the assumption that you need this information in the same process that your consumer is running in.

**Comment by dstrelau** [comment]
Hmm, no this doesn't help me unfortunately. Happy to contribute a PR for this if you'd be willing to point me in the direction you'd like to go.

**Comment by dasch** [comment]
So basically you'd like to periodically poll the highwater mark offset for each partition in a set of topics?

**Comment by dstrelau** [comment]
Yep, exactly.

**Comment by dasch** [comment]
As far as I can see in [the protocol](http://kafka.apache.org/protocol.html), there's no Kafka API to give you this directly. The closest thing that doesn't involve fetching any messages would be to do an Offset Request with the special offset -1, meaning "offset of next message to be appended", if I recall correctly. You'd need to first get the complete list of partitions for the topic, which should be easy to do, though.

FetchOperation has some code for resolving offsets that could be extracted into a separate operation class. Let me have a look.

**Comment by dasch** [comment]
Once #230 has been merged I should be able to add an API for this.

**Comment by dasch** [comment]
@dstrelau can you take a look at #232?

**Comment by dstrelau** [comment]
I'm away from a computer until next week, so I can't actually run that branch to test it out, but it looks like it should work. Thanks!
