### ISSUE TITLE
Allow configuring the offset commit retention time

### ISSUE THREAD

**Issue by dasch** [zendesk/ruby-kafka#233]
Currently, the broker default is always used. When a consumer group is stopped and started again after a while, the committed offsets may have expired, causing the group to re-process the topics.

The API could look like this:

``` ruby
consumer = kafka.consumer(group_id: "...", offset_commit_retention_time: 120)
```

I'm not sure whether to surface the nomenclature around "offset commits" or whether to use the more intuitive concept of "checkpointing".

**Comment by dasch** [comment]
What is the maximum value allowed by Kafka?

**Comment by tjwp** [comment]
The maximum appears to be `Integer.MAX_VALUE` (2_147_483_648), over 4000 years.

**Comment by dasch** [comment]
OK, no problems then. I've run into weird arbitrary timeout limits in the past.
