### ISSUE TITLE
When a consumer loses connection from a broker due to rebalancing, offsets are not synced upon reconnect, and messages are consumed multiple times.

### ISSUE THREAD

**Issue by xxx** [zendesk/ruby-kafka#245]
Maybe this is just a wontfix due to Kafka version and the client API being super alpha, but it was surprising behavior to me.

If a second consumer attempts to consume a partition already being serviced by another consumer in the same group, it causes the broker to rebalance (whether that is the correct behavior on the part of Kafka is unknown to me), and one of the consumers will get chosen to continue servicing the partition, while the other is kicked out. The problem is that when this happens, any offsets not already committed by the original consumer will not be committed even if it is chosen by the broker to continue servicing the partition, so those messages are re-fetched. What's especially strange in this case, is that even in this case, only the first message of the re-fetched batch is committed, so the remaining ones are fetched *again*, with only the first being committed each fetch, until the partition is finally caught up.

It's something that could happen accidentally, or when spinning up new hardware, or whatever.

This can be worked around by setting `offset_commit_threshold` to 1 to enforce offset commit after every message processed, but I still think it should be handled at some lower level to prevent the messages from being processed so many times each.

* Version of Ruby: `ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]`
* Version of Kafka: 0.10.0.0
* Version of ruby-kafka: 0f2ae75a712b00a94eb01904582ab397280a6758 (i.e. current HEAD)

###### Steps to reproduce

`consumer.rb`:

```ruby
#!/usr/bin/env ruby

require 'ruby-kafka'

TOPIC = 'mpd-topic'

$kafka = Kafka.new(
  seed_brokers: ['localhost:9092'],
  client_id: 'mpd1'
)

consumer = $kafka.consumer(group_id: 'mpd-consumers', offset_commit_threshold: 0)

consumer.subscribe(TOPIC)

begin
  consumer.each_message do |msg|
    p msg
  end
rescue RuntimeError
  retry
end
```

`producer.rb`:

```ruby
#!/usr/bin/env ruby

require 'ruby-kafka'

TOPIC = 'mpd-topic'

$kafka = Kafka.new(
  seed_brokers: ['localhost:9092'],
  client_id: 'mpd1'
)

producer = $kafka.async_producer

20.times do
  producer.produce(
    'sup?',
    topic: TOPIC,
    partition_key: 'mah-key'
  )
end

producer.deliver_messages

at_exit do
   producer.shutdown
end
```

Then in separate shells to keep the output easy to read:

first shell:

```shell
$ ruby consumer.rb
```

another shell:

```shell
$ ruby consumer.rb
```

third shell:

```shell
$ ruby producer.rb
```

Then watch the output of the consumer.rb shells.

###### Expected outcome

My consumer group wouldn't consumer messages more than twice.

###### Actual outcome

My consumer group consumed messages more than twice.

**Comment by dasch** [comment]
Can you try without setting `offset_commit_threshold` to `0`? I'm not sure what effect it has, but it's certainly not intended...

**Comment by xxx** [comment]
@dasch It's the same effect. `offset_commit_threshold` defaults to 0.

**Comment by dasch** [comment]
Hmm, indeed it is. I think this might be a complex case, I'll have to do some digging.

**Comment by dasch** [comment]
Note that offset commits are unrelated to fetches – the reason there's a commit after processing the first message in a batch is that the time-based commit trigger fires immediately the first time it's checked.

**Comment by xxx** [comment]
@dasch I'm not sure I understand what you mean here. The time-based trigger does not happen on a timer. It fires after a subsequent message is processed as long as `offset_commit_interval` seconds have elapsed (defaults to 10) since the previous commit, and *does* commit all the stored offsets.

**Comment by dasch** [comment]
Let me clarify: the offset commits trigger upon message _processing_, but is not related to message _fetching_. That may explain this:
> only the first message of the re-fetched batch is committed, so the remaining ones are fetched again, with only the first being committed each fetch, until the partition is finally caught up.

Or are you seeing duplicate processing even with a stable consumer group?

An unstable consumer group cannot be guaranteed to not process any messages twice, but some measure can be taken to limit the problem. As you correctly noticed, a consumer disregards its own in-memory checkpoints when the group re-syncs, starting over from the last committed ones. This was done during development to err on the side of at-least-once processing, but it's something that can probably be changed – especially if someone would be willing to put in the time to create tests and/or an implementation.

As an extension of this, I've also looked into ways of trying to keep as many partitions as possible from being re-assigned during a re-sync. It's difficult to balance this with assignment fairness, though. See #103 for some details.

I'd love to get some help with this as I'm quite swamped with other stuff these days.

**Comment by xxx** [comment]
I'm not seeing duplicates with a stable group, but with an unstable group, I would not expect a message to be processed more than twice, but some of them are being processed many more times than that.

The naive approach would be commit uncommitted offsets on connect if there are any.

**Comment by dasch** [comment]
@xxx I'm trying to think through whether it would be safe to keep a consumer's offsets across a group re-sync – I worry that there may be edge cases where a consumer is cut off from the group for some time before rejoining, then committing offsets for a partition that had been handled by another member in the meantime. I may be able to check whether the new group generation is the immediate successor to the old one, in which case it should be safe to keep the offsets for partitions that are still assigned to the consumer...

**Comment by dasch** [comment]
@xxx I opened #248.

**Comment by dasch** [comment]
Should be fixed in the latest releases.
