### ISSUE TITLE
Limit the rate of message deliveries in the async producer

### ISSUE THREAD

**Issue by dasch** [zendesk/ruby-kafka#261]
We experienced a situation where the async producer got into a loop where it started delivering messages at a very high rate. There should be a minimal interval between each attempt in order to spare the brokers.

**Comment by tcrayford** [comment]
@dasch wouldn't this be better handled by using the 0.9 quotas feature on the broker side and having this library respect the backoff responses?

**Comment by dasch** [comment]
Maybe... depends on how the quotas would be implemented client side. Would the API call just block when the quota is used? If so, it would be easier to just skip message deliveries in the async producer if the last attempt was within x seconds. Maybe this could be generalized and use the quota mechanism, though...

**Comment by dasch** [comment]
Seems that the quotas only apply to produce/fetch requests, so they wouldn't have prevented the issue we experienced, which was a flood of metadata requests because a missing topic caused the metadata to constantly be marked as stale...

**Comment by tcrayford** [comment]
Ah, yep. It seems like *all* requests could really use throttling on the servers side. However, for now I think more sensible client side backoff/retry makes sense for this library.

**Comment by dasch** [comment]
@tcrayford can I get you to look at https://github.com/zendesk/ruby-kafka/pull/262?
