### ISSUE TITLE
Support for messages timestamps in 0.10.0

### ISSUE THREAD

**Issue by pbrisbin** [zendesk/ruby-kafka#270]
We are going to start using Kafka Streams and Kafka Connect for some of our message processing. This requires Kafka 0.10.0, and specifically message timestamps. We currently have a number of Ruby producers (using poseidon), which we intended to move over to this library for 0.10.0 support, but we saw that message timestamps are not supported.

Do you have any pointers for adding that functionality? There's a good chance using this library and adding that ourselves is our best option at this time. Any direction on that would be appreciated.

**Comment by dasch** [comment]
As far as I know, Kafka brokers will set the timestamp themselves when the 0.9 API is used – this of course means that you don't directly control the timestamps, but it may be enough for your needs.

Unfortunately, it will be rather tricky to support both 0.9 and 0.10 simultaneously due to that way API compatibility is handled in 0.9. My current plan is to wait for 0.10 to become more widely deployed and then switch over to it completely, abandoning 0.9 support. I'd prefer to do that *after* the library has stabilized, though, in order to leave 0.9 users with something usable. It may not be until version 2.0 of ruby-kafka.

Do you have a hard requirement on user-specified message timestamps?

**Comment by pbrisbin** [comment]
> Kafka brokers will set the timestamp themselves when the 0.9 API is used

Looking at [this document](https://cwiki.apache.org/confluence/display/KAFKA/KIP-32+-+Add+timestamps+to+Kafka+message#KIP-32-AddtimestampstoKafkamessage-Compatibility,Deprecation,andMigrationPlan), I believe the configuration you're referring to would be *Phase 2* (0.10 brokers, 0.10 message.format.version, but 0.9 clients). There is message time-stamping, and it can be configured to be broker-provided, but for older clients, the following is happening:

- At point 1.a, you've got the added overhead of re-compression
- At point 2.c, you're unable to use zero-copy transfer

Confluent has advised us against running this way, because it has been known to cause operational issues (high CPU) on the brokers. Therefore, we're taking the stance that we can't move to the 0.10 message.format.version until we've upgraded our clients to support the 0.10 API. That means we could only get as far as *Phase 1*, and would have no message time-stamping.

We may discover our workload is such that the CPU issues won't bite us, but we decided to investigate updating our clients first -- hence this Issue.

**Comment by dasch** [comment]
That sounds about right – the brokers would have to re-encode every message.

Supporting two API versions would be a lot of work, making the entire API layer much more complicated. I'm interested in making ruby-kafka work for you guys, though, but I would need some help. I'm also leaving for an extended vacation at the end of September, and won't return to work until December 1, so the timing may not work for you.

**Comment by pbrisbin** [comment]
Your plan to hold off until 0.10 sees wider adoption, rather than maintaining two versions is reasonable. IMO, that doesn't preclude us working together to support (only) 0.10 in a fork or long-lived branch. It just means it won't be merge-able for quite a while.

The timing is unfortunate. I'm happy to work with you through Sept and see where we get, but we very much want this support before Dec 1, so if it doesn't look promising, we may decide to go with the JRuby client.

**Comment by dasch** [comment]
@pbrisbin if you're okay with using a branch, it shouldn't be hard. I actually already [associate timestamps with buffered messages](https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/protocol/message.rb#L23), they're just not transmitted to the broker (the timestamp is used to monitor produce->ack delays).

Here's what would be needed to add support for the 0.10 Produce API, as far as I can see:
* The ProduceRequest class would need to have an `api_version` method that returned 2 (see e.g. https://github.com/zendesk/ruby-kafka/blob/cd406829bad3b3d8f5e9bff0bb87eb3c72c67e0d/lib/kafka/protocol/offset_fetch_request.rb#L13)
* Protocol::Message must encode the timestamp according to the [protocol](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-Messagesets)
* The ProduceResponse class would need to be able to decode the new API response.

I think that's it, actually, unless you also need a way to manually set the timestamps when calling `produce`?

**Comment by pbrisbin** [comment]
> Here's what would be needed to add support for the 0.10 Produce API, as far as I can see...

Sounds great. I'd like to spend some time experimenting on those changes this week. I do think we'll need support on the consumer side to avoid the non-zero-copy overhead though.

> I think that's it, actually, unless you also need a way to manually set the timestamps when calling produce?

I don't think we do. And I think it's reasonable not to support that, at least for now. The Kafka docs talk about *created* time or *log-append* time. This client would support the former, and you can get the latter by broker configuration. I thought I had seen *event* time in the documentation somewhere, which is what you're describing, but I can't find it now.

**Comment by dasch** [comment]
Great! If you need help, let me know - we can set up a call if you get stuck. I'd love to get more people involved in this project.

**Comment by mrb** [comment]
@dasch Hey! I'm working on this issue from the Code Climate side. I've got the timestamps successfully encoded into the messages, but I'm having some trouble with the decoding side. Wondering if you have some time tomorrow to chat - let me know! Thanks.

**Comment by dasch** [comment]
@mrb: there may be a bit of a time zone issue – I'm based out of Copenhagen. Do you mean Wednesday? If so, it would be best if we could do it as early as possible. What time would work for you? Or just write when you're ready, then we'll do a hangout if I'm still in the office.

**Comment by mrb** [comment]
@dasch Does 4PM Copenhagen time today (Wednesday) work? Shoot me an email if you can mrb@codeclimate.com. Thanks!

**Comment by dasch** [comment]
:+1:

**Comment by dasch** [comment]
Closing this issue, follow #279 for progress on timestamp support.

**Comment by dasch** [comment]
@pbrisbin I've just released `v0.5.0.beta1` with support for Kafka 0.10. Would you be willing to run this in production for some time and see if everything works as expected?

**Comment by pbrisbin** [comment]
That's great to hear @dasch ! Unfortunately, our pressures to get onto 0.10 have subsided for the moment, and so we're probably going to be on 0.9 for another quarter or so. If/when we do update though, I'd be happy to run the beta (if it's still beta then) and let you know.

**Comment by dasch** [comment]
:+1:

Hopefully it'll be out of beta by then. Make sure to lock down your version to `~> 0.4.0` in your Gemfile, as v0.5 won't be compatible with Kafka 0.9!
