### ISSUE TITLE
How to determine of kafka topic exists

### ISSUE THREAD

**Issue by rayjohnson** [zendesk/ruby-kafka#273]
Is there a straight forward way to determine if a kafka topic exists?

I had a situation where my topic got deleted and when attempting to write or read I get a very weird error about not being able to assign a partition.  That error could certainly be better.

However, if the topic doesn't exist I have bigger problems and I'd actually like a simple way to test and see if a given topic does indeed exist before my code starts up.  I'm not seeing a straight forward way to do that...

**Comment by charkost** [comment]
You can check if the topic is included in the `Kafka::Client#topics` array. It fetches metadata before returning the array which means that it represents the current cluster state.

**Comment by dasch** [comment]
@rayjohnson is this using the producer API? I can improve the error message there.

I usually go into the Rails console, where I have an initializer that sets up a Kafka client and assigns it to the global variable `$kafka`. This makes it easy to grep for topics:

```ruby
$kafka.topics.grep /something/
```

**Comment by dasch** [comment]
The log should contain lines like this:

> Failed to assign partitions to _x_ messages in _topic_

Was that not enough to debug the issue?

**Comment by rayjohnson** [comment]
Well I think the first time I saw that message was because a broker was down (and it was only a three node cluster).  So I kind of had in my head it was meaning something else was going wrong.  I suppose it will be enough to debug in the future now that I know what it really means…  ☺

Ray

**Comment by rayjohnson** [comment]
This is great.  Had not run across it yet – will try it out now!

Ray

**Comment by dasch** [comment]
Closing this out – let me know if you have other questions.

**Comment by electron0zero** [comment]
I use this method to check for topic.

```ruby
def check_for_topic?(topic)
  client =  Kafka::Client.new(seed_brokers: ["kafka-1:9092", "kafka-2:9092", "kafka-3:9092"])
  return client.topics.include?(topic)
end
```
