### ISSUE TITLE
Committed offsets are shifted by one

### ISSUE THREAD

**Issue by tulios** [zendesk/ruby-kafka#280]
Hi, after using the consumer for a while I've caught a difference from other libraries. In my company, we use [burrow](https://github.com/linkedin/Burrow) to monitor our kafka consumers (a lag checker from linkedin) and with ruby-kafka it reports one message lagging in each partition. I noticed it because we have some topics with seasonal load, topics that receive messages in one period of the day and not constantly, and this is really clear on those.

I have started debugging burrow to see if the problem was there but after some checks I concluded that burrow was correct.

* Version of Ruby:
2.3.1

* Version of Kafka:
0.9.0.1

* Version of ruby-kafka:
0.3.15.beta3

###### Steps to reproduce

Regular ruby-kafka consumer group

```ruby
require 'kafka'
kafka = Kafka.new(seed_brokers: ['localhost:9092'])
consumer = kafka.consumer(group_id: 'test1')
trap('QUIT') { consumer.stop }

consumer.subscribe('test')
consumer.each_message { |message| puts(message.inspect) }
```

###### Expected outcome

Comparing ruby-kafka and kafkacat consumers, for example, we have the following results:

Using a new topic with two partitions and publishing one message (the first message)

burrow topic offsets from `/v2/kafka/local/topic/topic-name`
```json
{
  "error": false,
  "message": "broker topic offsets returned",
  "offsets": [
    0,
    1
  ]
}
```

kafkacat consumer group offsets:
(running with `kafkacat -C -b localhost:9092 -o beginning -G kafkacat topic-name`)
burrow consumer group offsets from `/v2/kafka/local/consumer/kafkacat/topic/topic-name`

```json
{
  "error": false,
  "message": "consumer group topic offsets returned",
  "offsets": [
    -1,
    1
  ]
}
```

###### Actual outcome

ruby-kafka consumer group offsets:
burrow consumer group offsets from `/v2/kafka/local/consumer/ruby-kafka/topic/topic-name`

```json
{
  "error": false,
  "message": "consumer group topic offsets returned",
  "offsets": [
    -1,
    0
  ]
}
```

The kafka documentation says: "The committed offset should always be the offset of the next message that your application will read. Thus, when calling commitSync(offsets) you should add one to the offset of the last message processed."

https://kafka.apache.org/090/javadoc/index.html?org/apache/kafka/clients/consumer/KafkaConsumer.html in "Manual Offset Control"

I managed to fix this behavior by adding one to `consumer#mark_message_as_processed`

```ruby
def mark_message_as_processed(message)
  # included +1
  @offset_manager.mark_as_processed(message.topic, message.partition, message.offset + 1)
end
```

and assuming that kafka will have the next offset, I removed the +1 from `offset_manager#next_offset_for`

```ruby
def next_offset_for(topic, partition)
  offset = @processed_offsets.fetch(topic, {}).fetch(partition) {
    committed_offset_for(topic, partition)
  }

  if offset < 0
    resolve_offset(topic, partition)
  else
    # removed +1
    offset
  end
end
```

after those changes burrow correctly notifies the lag and `ruby-kafka` consumers behave the same as the other consumers (java, erlang, etc).

The consumers are consuming all messages but since the offsets are shifted by one the monitoring tools are reporting lag or stopped consumers. I can create a PR with the changes but I decided to get some input first. I checked other libraries and they behave like that.

Thanks

**Comment by dasch** [comment]
Hmm. I think I changed the code to stop storing the _next_ offset in order to fix some bug. I'd be interested in a PR for this, although the addition of one should happen when committing the offsets, not when calling `mark_message_as_processed`, as it's an internal detail as far as the consumer is concerned.

**Comment by tulios** [comment]
I'll move the +1 to the offset commit and prepare a PR today. Thanks

**Comment by dasch** [comment]
:heart:
