### ISSUE TITLE
When message value is JSON it does not get delivered to the consumer

### ISSUE THREAD

**Issue by joeljames** [zendesk/ruby-kafka#285]
- Version of Ruby: ruby 2.2.3p17
- Version of Kafka: 0.10
- Version of ruby-kafka: 0.3.15
###### Steps to reproduce

Consumer is not receiving message when the message is sent as a JSON.
Below is the example which I been using to test:

``` ruby
client = Kafka.new(
  seed_brokers: Rails.configuration.kafka_brokers,
  ssl_ca_cert: Rails.configuration.kafka_ca,
  ssl_client_cert: Rails.configuration.kafka_cert,
  ssl_client_cert_key: Rails.configuration.kafka_private_key
)
producer = client.producer
data = JSON.dump({'foo': 'bar'})
producer.produce(
  data,
  topic: "#{Rails.configuration.kafka_topic_prefix}user-access"
)
producer.deliver_messages
```
###### Expected outcome

The consumer should receive the message 
`b"{'foo': 'bar'}"`
###### Actual outcome

After calling the `producer.deliver_messages` I would expect the consumer to receive the message, but unfortunately, the consumer does not receive the message. 

However, when I try to send an another message. The consumer receives the first and the second message. Not sure why this is happening.

``` ruby
producer.produce(
  'hello',
  topic: "#{Rails.configuration.kafka_topic_prefix}user-access"
)
producer.deliver_messages
```
###### Expected outcome

The consumer should receive the message 
`b"hello"`
###### Actual outcome

```
b"{'foo': 'bar'}"
b"hello"
```

**Comment by dasch** [comment]
Are you sure that you're consuming all the partitions in the topic?

**Comment by joeljames** [comment]
Yes, Its just weird that I have to produce a second message where message body is a string for the first message to reach the consumer.

**Comment by dasch** [comment]
Kafka has no knowledge of the message body, so I can't see why it should matter that it's JSON. I'm unfortunately not able to reproduce the bug currently, as I'm traveling. Can you try writing a failing spec?

**Comment by joeljames** [comment]
@dasch Thanks for taking a look at the issue. 
I have got my ruby producer to send JSON body and python consumer to receive JSON body. 
I was memoizing the Kafka ruby client and producer in my Rails app, I removed the memoization, and everything seemed to work as expected.

**Comment by dasch** [comment]
I'd love to see how that memoization was implemented, as well as which web server you were using.
