### ISSUE TITLE
getaddrinfo: Name or service not known

### ISSUE THREAD

**Issue by jakobcho** [zendesk/ruby-kafka#289]
Hi, 
  I am trying to use ruby-kafka on my PC (running ubuntu locally) to connect to my kafka server on AWS-EC2, but I will get error as  " **getaddrinfo: Name or service not known from SocketWithTimeout** ", 
and I found that it is caused by it got the private DNS of AWS as **ip-172-31-24-81.us-west-2.compute.internal** to query, and then got the error message.

  I was wondering if it is an issue or caused by my mis-using this api. and I am not sure if I can submit issue here or not. Please help me on this problem

many thanks,

p.s. If I hardcode in SocketWithTimeout to always set the host as its public IP address, then it will succeed to get results.

* Version of Ruby: 2.3.1p112
* Version of Kafka: 0.10
* Version of ruby-kafka: 0.3.15

###### Steps to reproduce

#!/usr/bin/env ruby
require "kafka"

logger = Logger.new(StringIO.new)
seed_broker = ["ec2-52-88-163-39.us-west-2.compute.amazonaws.com:9092"]
topic = "kaa"

kafka = Kafka.new(seed_brokers: seed_broker,
                  client_id: "simple_consumer",
                  socket_timeout: 20,
                  logger: logger)

kafka.each_message(topic: topic) do |message|
  puts message.value
end

###### Expected outcome

{"header":{"endpointKeyHash":{"string":"Veiihel+yK9d5KD0nzcZTNloZiA="},"applicationToken":{"string":"20051485642145702525"},"headerVersion":{"int":1},"timestamp":{"long":1477355141676},"logSchemaVersion":{"int":3}},"event":{"temperature":{"double":14.0},"humidity":{"double":0.0},"devicePowerOn":{"boolean":true},"ledLightOn":{"boolean":true},"level":"KAA_INFO","tag":"TAG","message":"MESSAGE_","timeStamp":1477355141132}}
{"header":{"endpointKeyHash":{"string":"Veiihel+yK9d5KD0nzcZTNloZiA="},"applicationToken":{"string":"20051485642145702525"},"headerVersion":{"int":1},"timestamp":{"long":1477355143815},"logSchemaVersion":{"int":3}},"event":{"temperature":{"double":13.0},"humidity":{"double":0.0},"devicePowerOn":{"boolean":true},"ledLightOn":{"boolean":true},"level":"KAA_INFO","tag":"TAG","message":"MESSAGE_","timeStamp":1477355143310}}

###### Actual outcome

/home/vincent.cho/.rvm/gems/ruby-2.3.1/gems/ruby-kafka-0.3.15/lib/kafka/connection.rb:123:in `rescue in open': getaddrinfo: Name or service not known (Kafka::ConnectionError)
	from /home/vincent.cho/.rvm/gems/ruby-2.3.1/gems/ruby-kafka-0.3.15/lib/kafka/connection.rb:105:in `open'
	from /home/vincent.cho/.rvm/gems/ruby-2.3.1/gems/ruby-kafka-0.3.15/lib/kafka/connection.rb:87:in `block in send_request'
	from /home/vincent.cho/.rvm/gems/ruby-2.3.1/gems/ruby-kafka-0.3.15/lib/kafka/instrumenter.rb:21:in `instrument'
	from /home/vincent.cho/.rvm/gems/ruby-2.3.1/gems/ruby-kafka-0.3.15/lib/kafka/connection.rb:86:in `send_request'
	from /home/vincent.cho/.rvm/gems/ruby-2.3.1/gems/ruby-kafka-0.3.15/lib/kafka/broker.rb:50:in `list_offsets'
	from /home/vincent.cho/.rvm/gems/ruby-2.3.1/gems/ruby-kafka-0.3.15/lib/kafka/fetch_operation.rb:134:in `resolve_offsets'
	from /home/vincent.cho/.rvm/gems/ruby-2.3.1/gems/ruby-kafka-0.3.15/lib/kafka/fetch_operation.rb:60:in `block in execute'
	from /home/vincent.cho/.rvm/gems/ruby-2.3.1/gems/ruby-kafka-0.3.15/lib/kafka/fetch_operation.rb:59:in `each'
	from /home/vincent.cho/.rvm/gems/ruby-2.3.1/gems/ruby-kafka-0.3.15/lib/kafka/fetch_operation.rb:59:in `flat_map'
	from /home/vincent.cho/.rvm/gems/ruby-2.3.1/gems/ruby-kafka-0.3.15/lib/kafka/fetch_operation.rb:59:in `execute'
	from /home/vincent.cho/.rvm/gems/ruby-2.3.1/gems/ruby-kafka-0.3.15/lib/kafka/client.rb:372:in `block in each_message'
	from /home/vincent.cho/.rvm/gems/ruby-2.3.1/gems/ruby-kafka-0.3.15/lib/kafka/client.rb:359:in `loop'
	from /home/vincent.cho/.rvm/gems/ruby-2.3.1/gems/ruby-kafka-0.3.15/lib/kafka/client.rb:359:in `each_message'
	from test.rb:13:in `<main>'

**Comment by osheroff** [comment]
you may want to have a look at setting `advertised.host.name` on the kafka server to the node's external IP.  kafka clients fetch connection info from the server, and if that's wrong (in this case, the internal ec2 address) they will fail.

**Comment by jakobcho** [comment]
It works, Thank you so much. I knew it should not be an issue.
