### ISSUE TITLE
"Received out-of-order response id 9, was expecting 10"

### ISSUE THREAD

**Issue by osheroff** [zendesk/ruby-kafka#290]
When consuming a topic that is out of data, the shutdown process appears to be this:

```
11:01:52.483   Sending request 10 (#<Kafka::Protocol::FetchRequest:0x007fd024bbff48>) to kafka.docker:9092
11:01:52.484   Waiting for response 10 from kafka.docker:9092
^C11:01:53.937   Leaving group `occam_count_job_worker`
11:01:53.937   Sending request 11 (#<Kafka::Protocol::LeaveGroupRequest:0x007fd024bbc870>) to kafka.docker:9092
11:01:57.470   Received response 10 from kafka.docker:9092
11:01:57.470   Received out-of-order response id 10, was expecting 11
```

So basically:

```
-> fetch (req10)
SIGTERM
-> leave (req11)
<- fetch (req10) error!
```

Near as I can tell this is relatively harmless, but it's not super ideal, as we never really get an ACK that we've left the group.  Any thoughts on how to fix this?

**Comment by dasch** [comment]
The problem is that some requests can take a long time, especially fetches, so it's not a good idea to wait for the current request to finish. The current mechanism is a bit blunt, however. I'm open to alternatives.
