### ISSUE TITLE
Update to latest dogstats-ruby

### ISSUE THREAD

**Issue by pabloroz** [zendesk/ruby-kafka#292]
Datadog updated its dogstats-ruby and from version 2.* it should be required using  

`require 'datadog/statsd'` instead of `require 'statsd'`

and used with `Datadog::Statsd.new` instead of `Statsd.new`

**Comment by dasch** [comment]
Can you submit a PR?

**Comment by vitaliy** [comment]
I've created one here: https://github.com/zendesk/ruby-kafka/pull/296

Although not sure why functional test failed. Will try to look into it a bit later.
