### ISSUE TITLE
Improved Shutdown Process

### ISSUE THREAD

**Issue by cade** [zendesk/ruby-kafka#295]
Hi! Thanks for all of your work on `ruby-kafka`!

I've been working a decent bit with Kafka over the past 18 months for [my employer](https://www.getharvest.com/). We currently use `poseidon` and are attempting to migrate over to `ruby-kafka`. Since `poseidon` doesn't have an async producer, we implemented one in-house with a similar background-thread-based approach, which allowed us to have a lot of freedom on how to handle shutting down the producer.

When shutting down, we put our producer threads on a timeout in order for them to have a chance to get through the backlog of queued messages. Once the timeout is up, we simply flush the queue to disk in a "dropped messages" log.

With the current state of `ruby-kafka`, it appears that shutting down without potentially losing messages is going to be challenging (which, in fairness, you clearly state in the documentation!). Are you open to entertaining a shutdown flow that does something similar to what I've described? (It doesn't need to flush to disk directly so much as provide some sort of access to the currently queued, unprocessed messages after shutdown.) I realize this may be a bit of a challenge with the current juggling between the async producer's `Queue` instance and the sync producer's internal `MessageBuffer` and `PendingMessageQueue` lists.

I'd be happy to help in whatever way I can (bounce ideas/write code/etc.), but I didn't want to just drop some big shutdown-related PR on you without getting your buy-in first!

**Comment by dasch** [comment]
Hi @cade, thanks for taking the time to post this. I'm currently on vacation, but will look more into this when I come back in a week. This sounds like a somewhat exotic use case though, so I'd be hesitant of supporting it. Have you thought about using a custom wrapper around the sync producer?

**Comment by mensfeld** [comment]
Hey @dasch  any news on that issue? :-)

**Comment by dasch** [comment]
Not really – I don't think this feature would make sense in the main distribution: it doesn't actually guarantee message delivery and seems to place a higher burden on operations.

@cade I would suggest trying to implement your own async producer (take a look at AsyncProducer for inspiration) with the semantics you describe. It could make sense as a separate gem, maybe.

**Comment by cade** [comment]
Sorry I didn't follow up on this before! Without the ability to determine when messages are lost (or easily access the messages currently being processed), the gem's failure scenarios make this a non-starter for us. Thanks for the suggestions though! I'm going to close this issue.

**Comment by mensfeld** [comment]
@cade  can't you just use sync producer?

**Comment by cade** [comment]
Using the sync producer alone would fold message delivery time and delivery failure scenarios into the main web request thread, which would be a regression for us. With our current setup, our Kafka nodes can disappear entirely and the app will remain unaffected.

As Daniel mentioned, we _could_ write our own async handling over the top of the sync producer, but that's pretty much the exact situation we're currently in with Poseidon that we were hoping to avoid going forward. Also, ruby-kafka's current internal representation of messages moving between `MessageBuffer` and `PendingMessageQueue` lists makes it more difficult to get a snapshot of the existing queued messages at the moment of shutdown.

In our experience, Kafka is very fast and stable, and it's quite unusual to drop messages. However, as I'm sure you know, there are loads of potential failure scenarios at the intersection of threading/networking/distributed systems/etc. I do think ruby-kafka would benefit from some sort of visibility into when messages are discarded during shutdown (as the library currently stands, can you ever be confident you haven't dropped messages every time you deploy your app?), but I can certainly understand if you'd rather not take on the additional complexity involved.

Thanks for the suggestions and for taking the time to consider this issue at all!

**Comment by dasch** [comment]
@cade no problem. I still think you should consider porting your setup to ruby-kafka, if for nothing else then because of the 0.9 support.

As for visibility: if `deliver_messages` succeeds on the sync producer, you can be confident that the messages were delivered. I would not want to introduce more advanced visibility than that. Writing an async producer that buffers messages and only clears messages that have been successfully delivered should not be too hard – you can use a thread-safe queue and a background thread to avoid blocking, and can commit the buffer to disk on shutdown.
