### ISSUE TITLE
Failure to send messages if TCP connection to Kafka enters CLOSE_WAIT status

### ISSUE THREAD

**Issue by mikemar10** [zendesk/ruby-kafka#298]
Hello,

I am encountering an issue on a server that submits messages to kafka infrequently using ruby-kafka.  After a message has been successfully sent to kafka, if you wait for the TCP connections to the kafka cluster to enter CLOSE_WAIT status and attempt to send a message, a Kafka::DeliveryFailed exception will be raised and messages will fail to send to one of the partitions.

Ruby version: 2.1.8
Kafka version: 0.10.0.1-1 (confluent-kafka-2.11)
Ruby-kafka: 0.3.11 & master as of 11/15/2016

###### Steps to reproduce

```ruby
kafka = Kafka.new(
  seed_brokers: %w{...},
  connect_timeout: 5,
  socket_timeout: 10
)
producer = kafka.producer(
  compression_codec: :gzip,
  ack_timeout: 5,
  max_retries: 1,
  retry_backoff: 5,
  required_acks: :all
)

# this works
producer.produce('this is a test', topic: 'test')
producer.deliver_messages

# wait until the TCP connections enter CLOSE_WAIT status, you can monitor this on the client using netstat or lsof

#this fails with Kafka::DeliveryFailed
producer.produce('this is a test', topic: 'test')
producer.deliver_messages

# subsequent attempts to send messages will work and new TCP connections will be established
```

###### Expected outcome

I expected ruby-kafka to reestablish the connections to the cluster without raising an exception regardless of how long the process had idled.

###### Actual outcome

Messages fail to be delivered.  If message attempts are tried again in quick succession, the subsequent message attempts will succeed where the original failed.

**Comment by dasch** [comment]
Thanks for reporting this! I'm currently on vacation but will look more into this when I get back in a week. Handling idle connections is tricky.

**Comment by dasch** [comment]
@mikemar10 I'm not sure what the best way to solve this would be – is there a way to reliably detect that the connection is in CLOSE_WAIT state? Generally speaking, the sync producer should do only minimal retrying, as some users may have low-latency requirements. It's typically better to use the async producer if you want things to Just Work(TM).

**Comment by mensfeld** [comment]
@dasch can you tell me if there's a one thread that sends messages asynchronously for all the instances of async producer or does each async producer has it's own asnyc sending thread?

**Comment by dasch** [comment]
There's one thread for each async producer object.

**Comment by mensfeld** [comment]
@dasch thank you. One more question - is the async producer thread safe? I mean I could build a connection pool (as I do with sync producer) but it seems that it would be a big overhead if async is thread safe.

**Comment by dasch** [comment]
The async producer _should_ be thread safe.

**Comment by MacTynow** [comment]
Hi, after reproducing this and trying with the async producer, this is not a solution. The messages are not getting delivered either, it's just that you don't get the error.

What we are doing at the moment to avoid the issue is clearing the connection pool if we catch an error but that's quite hacky...

**Comment by MacTynow** [comment]
@mikemar10 just for information, how's your kafka cluster set up ?

**Comment by MacTynow** [comment]
Just FYI. Our setup is on AWS. The reason our connections were entering `CLOSE_WAIT` status is that the idle timeout of our ELB was the default which is 60 seconds. Raising it mitigates the issue, but it still happens if no messages go through for a while.

**Comment by mensfeld** [comment]
@MacTynow  I know you know  but you can switch temporarily to waterdrop as it wraps and handles this.

**Comment by dasch** [comment]
@MacTynow can I see the code you're using with the async producer? I'm surprised it doesn't work – this should just be a matter of retrying the delivery.

**Comment by mikemar10** [comment]
@MacTynow Unfortunately I no longer have access to the cluster in question because I've since changed jobs.  From memory though, it was a 3 node cluster running Confluent Platform v3 on CentOS 7 under docker.  A 3 node zookeeper cluster ran on the same nodes in a separate docker container.  The docker containers were using the `--net=host` option to bypass the docker port proxy.  I don't recall anything particularly out of ordinary with the cluster.

**Comment by dasch** [comment]
Closing due to a lack of activity. Feel free to reopen if this happens again.
