### ISSUE TITLE
Feature Request: subscribe to multiple topics by regex

### ISSUE THREAD

**Issue by aviflax** [zendesk/ruby-kafka#299]
This feature is [supported](https://kafka.apache.org/0101/javadoc/org/apache/kafka/clients/consumer/Consumer.html#subscribe(java.util.regex.Pattern,%20org.apache.kafka.clients.consumer.ConsumerRebalanceListener)) by the canonical Java client and would be useful for my company’s architecture.

Thanks!

**Comment by aviflax** [comment]
Ah, there’s more info in [the Javadocs for `KafkaConsumer`](https://kafka.apache.org/0101/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html#subscribe(java.util.regex.Pattern,%20org.apache.kafka.clients.consumer.ConsumerRebalanceListener)) (the canonical implementation of the `Consumer` interface I linked above).

**Comment by dasch** [comment]
I would be open to a PR that implements this.

**Comment by dasch** [comment]
Closing due to a lack of activity.

**Comment by rkrage** [comment]
@dasch would you mind reopening this? We would be very interested in this feature. I'd be happy to take a stab at implementation if you could provide some initial guidance (not super familiar with the codebase).

**Comment by rkrage** [comment]
Hmmm that wasn't as difficult as I thought it would be 😄 

Would love some comments on the above PR.
