### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by evanchaoli** [zendesk/ruby-kafka#300]
If this is a bug report, please fill out the following:

* Version of Ruby: 2.2.0
* Version of Kafka: kafka_2.11-0.9.0.0
* Version of ruby-kafka: 0.3.6 ~ 0.3.15

Please verify that the problem you're seeing hasn't been fixed by the current `master` of ruby-kafka.

###### Steps to reproduce

```ruby
kafka = Kafka.new(...)

# Please write an example that reproduces the problem you're describing.
# Just looply send a lot of data to Kafka, then 'top' command shows the 
# Ruby process' memory usage keeps growing.
# async_producer has same memory issue.

producer = kafka.producer
data = '0'*500
  count = 0
  100000.times { |i|
    producer.produce(data, topic: RETRIVE_VMS_PUBLISH_TOPIC)
    count += 1
    if count >= 50
        producer.deliver_messages
        puts "#{i}: #{GC.stat[:heap_live_slots]}"
        count = 0
    end
  }
  producer.deliver_messages

producer.shutdown

```

###### Expected outcome

I'm using this gem in a long run process, and I would expect that memory usage should be stable.

###### Actual outcome

The ruby process (as the sample code above) memory usage keeps growing, finally gets killed by Linux with OOM error.

**Comment by dasch** [comment]
Can you do some more digging and see which objects are growing in numbers?

**Comment by evanchaoli** [comment]
Actually I did memory_profiler and GC.stat, it doesn't look like ruby object leak.

I also tried to shutdown connection and reconnect every 5 produces, which doesn't help.

**Comment by dasch** [comment]
I guess it could be TCP connection leaking...

**Comment by evanchaoli** [comment]
If it's TCP connection leaking, then what is a solution?  I tried Hermann, that works well. With same test program, the ruby process' memory usage is quite stable.

**Comment by dasch** [comment]
We'd have to find the leak – most likely some memoization gone wrong, or a failure to close connections properly.

**Comment by evanchaoli** [comment]
Are you going to work on this? Is there an ETA?

**Comment by dasch** [comment]
There's no ETA, but I'll try to look at it this week.

**Comment by dasch** [comment]
@evanchaoli I've tried to reproduce the issue, but I can't on the latest master:

```ruby
# spec/functional/memory_leak_spec.rb

describe "Memory leak", functional: true do
  let(:producer) { kafka.producer }
  let(:topic) { create_random_topic(num_partitions: 1) }

  after { producer.shutdown rescue nil }

  example "leaking a bunch of memory" do
    logger.level = Logger::ERROR
    data = '0'*500
    count = 0

    100000000.times do |i|
      producer.produce(data, topic: topic)
      count += 1

      if count >= 50
        producer.deliver_messages
        puts "#{i}: #{GC.stat[:heap_live_slots]}"
        count = 0
      end
    end

    producer.deliver_messages
  end
end
```

Running `rspec --tag functional spec/functional/memory_leak_spec.rb` results in a constant number of live objects. Can you try your code on the latest master?

**Comment by evanchaoli** [comment]
Did you monitor the Ruby process memory usage via 'top' command?

**Comment by dasch** [comment]
Yeah – it looks to be constant.

**Comment by evanchaoli** [comment]
I tested wth the lastest master code, but get same result. During posting 100000000 messages, memory usage kept growing.

**Comment by dasch** [comment]
Can you try with the snippet I posted?

**Comment by evanchaoli** [comment]
The code is exact same as my test program.

**Comment by dasch** [comment]
Would you mind running it anyway, just to rule out any subtle difference? Also, can you try with a different version of Ruby?

**Comment by evanchaoli** [comment]
What ruby version did you test with? I can test. But even if Ruby 2.2 is a problem, it's not easy for us to change our production to upgrade Ruby version.

**Comment by dasch** [comment]
I'm on 2.2.3p173.

**Comment by evanchaoli** [comment]
OK, I'll test it tomorrow.

**Comment by evanchaoli** [comment]
I have tested with ruby 2.2.3 with exact same environment as my previous test, the memory usage is low and consistent.  So the memory leak should ocurred in the Ruby 2.2.0 C code.

**Comment by dasch** [comment]
Thanks! It's good to know that the problem is restricted to that version – not quite sure what's happening, but there's probably not much I can do about it, and since there's a patch level update to that Ruby version people shouldn't have too hard a time updating in production.

:heart:
