### ISSUE TITLE
Handle Kafka server errors in the producer

### ISSUE THREAD

**Issue by Nucc** [zendesk/ruby-kafka#305]
Is there any way to handle error messages on the producer side?

I was thinking on the possible approach, how do you like this way?

```
$kafka_producer.produce(message, topic: 'user_actions').onError do |error_type, message|
  error_handler
  return false # don't retry
end
```

Thanks.

**Comment by Nucc** [comment]
Is there any way to handle error messages on the producer side?

I was thinking on the possible approach, how do you like this way?

```
Kafka::Writer.write(message, topic: 'voice.call_details').onError do |error_type, message|
  error_handler
  return false # don't retry
end
```

Thanks.

**Comment by dasch** [comment]
I'm not sure what you mean by _error messages_ here. Whether to retry deliveries?

**Comment by Nucc** [comment]
error messages that we can see in the STDOUT after calling produce in console. Like Kafka server is unreachable.

```
> kafka_producer.produce(message, topic: 'user_actions')
true
>
> (seconds later)
[kafka] Fetching cluster metadata from kafka://kafka:9092
[kafka] Failed to connect to kafka:9092: getaddrinfo: Name or service not known
[kafka] Failed to fetch metadata from kafka://kafka:9092: getaddrinfo: Name or service not known
```

These messages appear seconds after calling produce, they are from the background job that sends the messages from the message queue to Kafka. We would like to handle this error and do additional steps but we don't find any solution.

**Comment by dasch** [comment]
Are you using an async producer from a background job? That sounds like a bad idea. You should look into either a) not having a background job do this, but send the messages directly to Kafka, or b) at least use the sync producer.

Note that there's a lot of setup and state that is maintained in the client – Kafka was not built for one-off message sends, but for long-lived clients. So if you're setting up and disposing a Kafka client for each job, you're going to get bad performance.

**Comment by Nucc** [comment]
Okay, thanks, I'll try using the sync producer.
