### ISSUE TITLE
ack_messages.producer.kafka not sent

### ISSUE THREAD

**Issue by mrkamel** [zendesk/ruby-kafka#307]
Hi,

it currently seems not possible to get the offset of a produce'd message directly. The comments in `produce_operation.rb` say

```
  # When executing the operation, an `ack_messages.producer.kafka` notification will be
  # emitted for each message set that was successfully appended to a topic partition.
  # The following keys will be found in the payload:
  #
  # * `:topic` — the topic that was written to.
  # * `:partition` — the partition that the message set was appended to.
  # * `:offset` — the offset of the first message in the message set.
  # * `:message_count` — the number of messages that were appended.
```

* but i don't see such message fired, so the comment is probably wrong or outdated?
* Generally, getting the offset **after** a produce request is only possible via `Kafka#last_offset_of`?
* It's not possible/desired to get the topic-partition-infos holding the offsets from the produce-response after `deliver_messages`?

thx

**Comment by mrkamel** [comment]
At least for `Client#deliver_message` it would be great to get back the written offset

**Comment by dasch** [comment]
Indeed that comment is wrong – you'll get an `ack_message.producer.kafka` for _each_ message produced. I'll update the comment.

**Comment by dasch** [comment]
Unfortunately, the Kafka protocol only returns the offset of the first message appended.

**Comment by dasch** [comment]
@mrkamel I've added #308 as a way to get offset info. I _think_ it's correct.

**Comment by mrkamel** [comment]
this is great! thank you. :+1: 

BTW do you know if it can happen that kafka is having gaps in the log or in between rotated logs ? Like offsets: 1 2 3 5 6 7, such that offset 4 is missing?

**Comment by dasch** [comment]
Yup, that can happen either due to messages being removed for being too old or due to log compaction.
