### ISSUE TITLE
Improve API for specifying number of required ACKs

### ISSUE THREAD

**Issue by dasch** [zendesk/ruby-kafka#31]
Currently, users need to pass in a number as the value of `required_acks`. If the number is greater than zero, it is interpreted as the number of replicas (the leader included) that must acknowledge the write before the request succeeds (not greater than the actual number of replicas.) If the number is -1, then *all* replicas must ACK. If the number is 0 then none need to ACK, not even the leader, and no response is sent back to the client (fire-and-forget).

Having the user need to understand these numbers is not good for usability, so I think we should use meaningful names instead. Maybe use a new parameter name for this, e.g. `durability` or `consistency` (**update:** even better, `durability_guarantee`?).

* `none` – no durability guarantees.
* `one` – at least one replica (the current leader) has acknowledged the write.
* `quorum` – a majority of replicas have acknowledged the write.
* `all` – all replicas have acknowledged the write.

**Comment by dasch** [comment]
@osheroff @bsandvik what do you think makes sense here? I feel that specifying `required_acks` as an integer is confusing, but should the option be called `durability`, `consistency` or something else entirely? I guess that since Kafka is single-master (per partition,) it's not a matter of consistency – so long as the value is not `none`, in which case we could in theory be writing to the wrong broker, erroneously thinking it is the leader...

**Comment by osheroff** [comment]
`durability` is fine.  Do note the tradeoff between cleaner semantics and masking what's really going on under the hood, though; arcane parameters are bad but having library consumers understand kafka's replication model is good.

**Comment by dasch** [comment]
I'll document the shit out of it, and may allow reverting to setting `required_acks` directly. Thanks!

**Comment by tcrayford** [comment]
@dasch we could maybe ask the kafka mailing list how they feel about this? It'd be nice to have consistency *and* human friendliness across all the APIs.

**Comment by dasch** [comment]
Yeah, that's probably a good idea. I've sort of parked this for now, as I've been more focused on resilience and performance work.

**Comment by dasch** [comment]
Since the default has been changed to `:all`, I'm going to close this. People changing the setting should have read up on the semantics.
