### ISSUE TITLE
rebalance callbacks support

### ISSUE THREAD

**Issue by piavka** [zendesk/ruby-kafka#310]
Is it possible to implement rebalance callbacks over current ruby-kafka code?
I'm looking for following functionality
http://kafka.apache.org/090/javadoc/org/apache/kafka/clients/consumer/ConsumerRebalanceListener.html
I haven't checked how actually this functionality is implemented in java driver, but 
afaiu this functionality can be built around handling the RebalanceInProgressCode protocol error in the ruby code
wdyt?

**Comment by piavka** [comment]
@dasch  the page http://kafka.apache.org/090/javadoc/org/apache/kafka/clients/consumer/ConsumerRebalanceListener.html
already gives some examples
another example could be reducing(if not eliminating) the number of processed duplicates which are sent downstream during rebalances

**Comment by dasch** [comment]
Closing due to a lack of activity.
