### ISSUE TITLE
Documentation: How to test consumer/producers built with ruby-kafka?

### ISSUE THREAD

**Issue by wflanagan** [zendesk/ruby-kafka#313]
All of the documentation I see on this gem shows how to test this gem, which a great if you're modifying this gem. 

However, if you're using this gem, and specifically want to write a test around your consumer/producer, I don't see a clean way to do it.  

Right now, I run my test (outside of my automated test suite), and then go manually clean up my Kafka broker, and start again.  

I can write specs that handle my "processing logic" that do not require Kafka connections. But, if I am writing a wrapper for a Consumer/Producer that all my workers will use, it would be great to be able to actually test this class, and after I am done, clean up for the next test (a la DatabaseCleaner).  

So, that brings me to the bug. What is the best practice for doing this? 

Thanks, and sorry to open an issue--not sure where else to ask.  

P.s. If someone wants to verbally tell me, I'm happy to transcribe into the Wiki to help others.

**Comment by dasch** [comment]
Good question. This is definitely something that would be valuable. Internally we use something called [FakeBroker](https://github.com/zendesk/ruby-kafka/blob/master/spec/fake_broker.rb) to represent a broker in-memory. If you want to take a stab at creating a similar helper class, geared more towards users of the library, that allow mocking the Kafka backend when testing, I would be more than willing to review :-)

**Comment by dasch** [comment]
I think people should use [Racecar](https://github.com/zendesk/racecar) to process messages, which has simple and easy support for testing.
