### ISSUE TITLE
Passphrase for private key files 

### ISSUE THREAD

**Issue by iam404** [zendesk/ruby-kafka#314]
Hi

I was looking for passing passphrase of a private key file into below code snippet : 

```
kafka = Kafka.new(
  ssl_ca_cert: File.read('my_ca_cert.pem'),
  ssl_client_cert: File.read('my_client_cert.pem'),
  ssl_client_cert_key: File.read('my_client_cert_key.pem'),
)
```
Any help ?

**Comment by dasch** [comment]
@iam404 sorry for the late response. I'm unfortunately not familiar with how you'd do that – @tcrayford would you know this?

**Comment by tcrayford** [comment]
@dasch it looks like http://stackoverflow.com/questions/235759/opening-an-rsa-private-key-from-ruby is the right thing - we'd need another parameter for the passphrase, that's all. @iam404 want to make a PR for that?

**Comment by iam404** [comment]
Ya sure , will test the above solution and create a PR. Thanks.
