### ISSUE TITLE
Consumer fails to subscribe to a topic when connecting via SSL

### ISSUE THREAD

**Issue by edkellena** [zendesk/ruby-kafka#315]
* Version of Ruby: 2.3.1
* Version of Kafka: 0.9.0
* Version of ruby-kafka: 0.3.16

###### Steps to reproduce

```ruby

        kafka = Kafka.new(
          seed_brokers: @kafka_ips,
          client_id: "service-name",
          logger: logger,
          ssl_ca_cert: File.read('ssl/ca-cert.pem'),
          ssl_client_cert: File.read('ssl/client-cert.pem'),
          ssl_client_cert_key: File.read('ssl/client-key.pem')
        )

      @consumer = kafka.consumer(
        group_id: "our-group",
        offset_commit_interval: 10,
        offset_commit_threshold: 1,)

      @consumer.subscribe("topic-name", start_from_beginning: true)
...
```

###### Expected outcome

The consumer would subscribe to the topic and we can handle incoming messages.

###### Actual outcome

We get a Kafka connection error:
```
/usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.3.16/lib/kafka/cluster.rb:212:in `fetch_cluster_info': Could not connect to any of the seed brokers: kafka://kafka1.domain:9092, kafka://kafka2.domain:9092 (Kafka::ConnectionError)
```
and the process dies.  We can successfully connect to and push messages to the same cluster over SSL using the Producer API, but consuming just doesn't want to work here.

Turning on the ActiveNotification monitoring we get this in the logs:

```
Received notification `request.connection.kafka` with payload: {:broker_host=>"kafka1.domain", :api=>:topic_metadata, :request_size=>49, :response_size=>0, :client_id=>"service-name", :exception=>["EOFError", "EOFError"], :exception_object=>#<EOFError: EOFError>}
```

Increasing the logging level on the Kafka cluster itself we see that it is listening to the incoming connection from the consumer service but nothing further than that. ie:
```
[2017-01-23 16:20:55,567] DEBUG Processor 2 listening to new connection from /10.1.1.1:38610 (kafka.network.Processor)
```

(Domains, IPs, etc changed for confidentiality sake...)

**Comment by dasch** [comment]
This sounds to me like a network connection error. Are you 100% certain the host names, certificates, etc. are set up correctly?

**Comment by edkellena** [comment]
Yep, I'm afraid so!

**Comment by dasch** [comment]
@edkellena does simpler operations work, e.g. `kafka.topics`?

**Comment by dasch** [comment]
Is this still an issue?
