### ISSUE TITLE
Ensure that committed offsets are never purged for active consumer groups

### ISSUE THREAD

**Issue by tjwp** [zendesk/ruby-kafka#317]
We have some very low throughput topics where partitions may not receive a new message within the retention period for committed offsets.

Increasing the retention period via the broker setting or per consumer (as represented by https://github.com/zendesk/ruby-kafka/pull/316) helps, but there are limits to how high we want to raise this. We still want committed offsets for topics and consumer groups that are no longer used to be purged within some reasonable time period.

We want to be able to re-commit the previously committed offsets (not just the processed offsets in the offset manager) for consumers groups that are still in use to ensure that the committed offsets never get stale.

We have three basic approaches to suggest:

1. A new, public method in the Consumer API to explicitly re-commit the current offsets. This would combine the processed offsets and the committed offsets held by the offset manager. The intent here is not to open up an interface to manually commit arbitrary offsets. We have already implemented a form of this locally and call it prior to initiating a consumer loop. Our processes are restarted at least every 24 hours, so this ensures that offsets are re-committed at least once a day.
2. Periodically re-commit the previously committed offsets. This would require something like another offset commit interval, and when committing offsets the committed offsets would be combined with the processed offsets if the timeout for the re-commit was reached.
3. Always re-commit the previously committed offsets when committing the processed offsets. There could be some flag specified to the consumer to determine if this is behavior enabled. This approach avoids the need to track multiple intervals but may add overhead to already frequent re-commits of processed offsets (https://github.com/zendesk/ruby-kafka/pull/284).

Please let us know which the of approaches above, or some variant/combination of them, you’d be open to and we’d be happy to produce a PR.

**Comment by dasch** [comment]
If there's an upper limit to the retention forced by Kafka I would be open to _always_ re-committing the offsets within that interval.

**Comment by tjwp** [comment]
It looks like the upper limit on the `offsets.retention.minutes` setting is `Integer.MAX_VALUE` (2_147_483_647), which is over 4000 years.

We would want to re-commit offsets within the configured `offsets.retentions.minutes`. Perhaps offsets should be re-committed at the first commit, and within _half_ of the `offset_retention_time`? If unset, the broker's default of 1 day could be assumed, so offsets would be re-committed twice a day.

**Comment by dasch** [comment]
Sounds reasonable. I'd :heart: a PR!
