### ISSUE TITLE
Major Bottleneck in Instrumentation When Using Acks

### ISSUE THREAD

**Issue by jpaskhay** [zendesk/ruby-kafka#327]
Hey there,

We've been in the process of building a new FluentD/Kafka ingest platform and have recently discovered a major bottleneck when trying to produce messages using `required_acks` of anything other than 0. After tracing through the code, we identified the instrumentation being done on every message in the handle_response method at https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/produce_operation.rb#L130 as the source of the bottleneck.

It would be good to expose some configurable way of skipping that code block to help performance when users want to use ack functionality.

The work-around is to obviously disable acks by setting `required_acks` to 0, but we needed acks for durability and auditing purposes.

We ended up simply wrapping the entire `each_with_index` block with `@logger.on_debug` in our local forked repo, which was good enough for our purposes. We saw a 3x throughput increase, both with `required_acks` set to 1 and even -1/all. This helped us eliminate all buffering that was stacking up in the fluentd kafka plugin.

**Comment by repeatedly** [comment]
Wow, good investigation.
In fluent-plugin-kafka, instrument feature is not needed.
I also hope ruby-kafka supports disabling instrument in some heavy point.

**Comment by dasch** [comment]
If no instrumentation subscribers have been set up, the instrumentation calls should be no-ops – is that not the case, or have you enabled Datadog reporting (which adds a subscriber)?

**Comment by dasch** [comment]
I only think you pay the penalty for event names that are subscribed to - try excluding those events in your regex (or have an explicit whitelist, which is probably better) and see if that fixes the problem.

**Comment by jpaskhay** [comment]
Sorry for the delayed response. Been tied up with load testing and working through some stability issues in our pipeline. Very possible that may work as well. Will give that a shot in the next week or so.

Thanks again for the prompt replies!

**Comment by jpaskhay** [comment]
I played around with the regexes yesterday and tested some more. Looks like there was a bit of confusion in our understanding of the instrumentation/monitoring implementation. We had copied the `ActiveSupport::Notifications.subscriber` example from the README **and** we were also including the Datadog reporter (patched to write plain statsd format so we can forward to Graphite).

So we overlooked the fact the Datadog reporter automatically subscribes to all notifications. That's where the per-message instrumentation was coming from. Having said that, it may be worthwhile to add the ability to disable the per-message instrumentation for the Datadog reporter. It has a big impact on throughput (~20% penalty for us).

I played around with wrapping the `ack_message` instrument block in `produce_operation.rb ` with `@logger.on_debug` vs commenting out the `ProducerSubscriber.ack_message` method and found disabling the entire instrument block in `produce_operation.rb ` was generally a few hundred messages per second faster (~3kB payload). Note we don't incur the `produce_message` instrument hit since we're using the FluentD Kafka plugin that overrides the `produce` method and skips that part.

**Comment by dasch** [comment]
Do you experience the same overhead if you don't include the datadog or statsd subscribers, so that nothing subscribes to the per-message instrumentation events? It's possible to just sample with statsd, so maybe that's a better approach.

**Comment by dasch** [comment]
Also, feel free to contribute the plain statsd subscriber in a PR ;-)

**Comment by dasch** [comment]
Closing this down – if there's a way to get more efficient metrics I'm open to a PR.
