### ISSUE TITLE
Possible memory leak in ruby-kafka

### ISSUE THREAD

**Issue by Kenterfie** [zendesk/ruby-kafka#328]
* Version of Ruby: ruby 2.2.1p85 (2015-02-26 revision 49769) and 2.3.3
* Version of Kafka: 0.10
* Version of ruby-kafka: 0.3.16

After some hours the memory usage increase rapidly. In our example the code needs 6-8 GByte of virtual memory after 16 hours. We have switched our program from logstash to kafka, so we can say the library is the reason of the problem, before the memory usage of the whole process never reached more than 245MByte. We use the default buffer sizes, so no more memory should be used in these case and we have disabled acknowledgements for testing.

###### Steps to reproduce
Only one of the async producer samples are needed. Possible with different threads which writes data constantly (120 messages all 10 seconds in our case).

Has someone else also memory issues with these library?

**Comment by dasch** [comment]
Would you be able to determine the type of objects that are leaking?

**Comment by Kenterfie** [comment]
I was not able to identify exactly which objects. We have moved away from the ruby-kafka library because of these issue. Has caused to many out of memory problems.

**Comment by Kenterfie** [comment]
A hugh difference to the firehouse sample is we dont use multiple producer instance per thread, we use a singleton logger class which is used across all threads and we use many threads.

**Comment by dasch** [comment]
That shouldn't cause memory bloat, although you might get a bottleneck.

**Comment by dasch** [comment]
I'd love to see a gist with your complete Kafka setup – I've been running async producers for a long time and haven't seen the kind of memory leaks that you're describing.

**Comment by Kenterfie** [comment]
This sample shows it. In my case the memory usage increase constantly. https://gist.github.com/Kenterfie/e8f30e12ff1ec64e00b25485609b0120

When you replace the kafka producer by a simple puts/logger no or small increase, but no leak. In my case 2GB memory usage after short time

**Comment by dasch** [comment]
@Kenterfie 

1) Does removing multithreading change anything?
2) Have you tried with `required_acks: 1` – that could be the trigger.

**Comment by Kenterfie** [comment]
@dasch
1. i have removed threads and it happens too. the memory increases infinity with kafka
2. the required_acks change to 0 was one try to fix/minimize the issue, so it hasnt nothing changed

**Comment by Kenterfie** [comment]
When i use the single threaded producer no leak happens.

**Comment by Kenterfie** [comment]
Another example

Single Threaded Logging with one Producer
https://gist.github.com/Kenterfie/2537aa726130bb80ab124cc6da3a358b

Constant increase of memory usage above kafka limits
`MEMORY[23613]: rss: 210316, live objects 53727
MEMORY[23613]: rss: 212268, live objects 53640
MEMORY[23613]: rss: 214448, live objects 53770
MEMORY[23613]: rss: 216784, live objects 53514
MEMORY[23613]: rss: 218908, live objects 53684
MEMORY[23613]: rss: 220896, live objects 53753
MEMORY[23613]: rss: 222944, live objects 53703
MEMORY[23613]: rss: 224880, live objects 53630`

Without kafka only puts output to stderror no increase of memory usage
https://gist.github.com/Kenterfie/a6574246252d163bce033e8bcc46926a

`MEMORY[24187]: rss: 20424, live objects 53570
MEMORY[24187]: rss: 20724, live objects 53701
MEMORY[24187]: rss: 20676, live objects 53715
MEMORY[24187]: rss: 21044, live objects 53697
MEMORY[24187]: rss: 20460, live objects 53443
MEMORY[24187]: rss: 21000, live objects 53620
MEMORY[24187]: rss: 20668, live objects 53597
MEMORY[24187]: rss: 20432, live objects 53674
MEMORY[24187]: rss: 20704, live objects 53548
`

**Comment by Kenterfie** [comment]
Ok, i think i have found the reason. The problem is not the library himself, its the ruby version. I have moved to 2.3.3 and the leak is gone.

2.2.1
`MEMORY[13951]: rss: 42376, live objects 30122
MEMORY[13951]: rss: 43960, live objects 29965
MEMORY[13951]: rss: 45544, live objects 30017
MEMORY[13951]: rss: 47392, live objects 30029
MEMORY[13951]: rss: 49240, live objects 30075
MEMORY[13951]: rss: 51088, live objects 30132
MEMORY[13951]: rss: 52936, live objects 30120
`
2.3.3
`MEMORY[14140]: rss: 21216, live objects 53747
MEMORY[14140]: rss: 21216, live objects 53602
MEMORY[14140]: rss: 21216, live objects 53649
MEMORY[14140]: rss: 21216, live objects 53664
MEMORY[14140]: rss: 21216, live objects 53422
MEMORY[14140]: rss: 21216, live objects 53587
MEMORY[14140]: rss: 21216, live objects 53728
MEMORY[14140]: rss: 21216, live objects 53732
MEMORY[14140]: rss: 21216, live objects 53429
MEMORY[14140]: rss: 21216, live objects 53472`

I will test it a little bit more, but looks ok

**Comment by dasch** [comment]
Great!

**Comment by piavka** [comment]
BTW i've similar issue with producer causing memleak both async and sync producer
(consumer is ok BTW)
and i've tried with 2.2.x and 2.3.x versions and it leaks in both

**Comment by dasch** [comment]
@piavka can you open a separate issue and add some more details there?

**Comment by piavka** [comment]
sure will do soon

**Comment by Kenterfie** [comment]
In my case the memory usage is higher than before with logstash logger but the leak stops now. So i close it. @piavka possible your main thread is locked by thread join or something else, then i notice that the GC not working like it should.
