### ISSUE TITLE
RuntimeError: can't add a new key into hash during iteration

### ISSUE THREAD

**Issue by eldan-klarna** [zendesk/ruby-kafka#330]
* Version of Ruby:           jruby-9.04.0
* Version of Kafka:          0.10.0.1
* Version of ruby-kafka:  0.3.16 

I got "RuntimeError: can't add a new key into hash during iteration" in message_buffer.rb:82 in this line:
@buffer[topic][partition] ||= []

It's not consistent, which is not surprising.. 
another thread must be looping over @buffer[topic] since I'm running JRuby and not MRI, 
having concurrency issues here makes sense

**Comment by dasch** [comment]
Are you sharing a synchronous producer object between threads?

**Comment by eldan-klarna** [comment]
@dasch 
No I'm using AsyncProducer

org/jruby/RubyHash.java:1007 in []=
.../lib/kafka/message_buffer.rb:82 in buffer_for
.../lib/kafka/message_buffer.rb:20 in write
.../lib/kafka/producer.rb:347 in block in assign_partitions!
org/jruby/RubyArray.java:1560 in each
.../lib/kafka/pending_message_queue.rb:36 in each
.../lib/kafka/producer.rb:338 in assign_partitions!
.../lib/kafka/producer.rb:300 in block in deliver_messages_with_retries
org/jruby/RubyKernel.java:1291 in loop
.../lib/kafka/producer.rb:293 in deliver_messages_with_retries
.../lib/kafka/producer.rb:243 in block in deliver_messages
.../lib/active_support/notifications.rb:166 in instrument
.../lib/kafka/instrumenter.rb:19 in instrument
.../lib/kafka/producer.rb:236 in deliver_messages
.../lib/kafka/async_producer.rb:223 in deliver_messages
.../lib/kafka/async_producer.rb:198 in block in run
org/jruby/RubyKernel.java:1291 in loop
.../lib/kafka/async_producer.rb:190 in run
.../lib/kafka/async_producer.rb:143 in block in ensure_threads_running!

**Comment by dasch** [comment]
It shouldn't be a threading problem, then – only one thread has access to the Product object that is wrapped by AsyncProducer. It sounds like a limitation with JRuby's Array implementation.

Would you have time to do a PR that changes how that array manipulation is done such that it works with JRuby?

(also note that you should be able to use the official JVM client from JRuby, which is way faster than this gem.)

**Comment by eldan-klarna** [comment]
@dasch 
Hi, sorry for the late reply,
The reason I think it's a threading issue is because:
1) I'm changing the hash in message_buffer.rb:82 and nowhere in the stack trace am I looping over any hash.
2) The hash is exposed, for an example if another thread calls .to_h on MessageBuffer then he gets exactly the same hash which includes the exact same buffer[topic][partition] hash.

**Comment by dasch** [comment]
Yeah, I'm not sure why this is showing up...
