### ISSUE TITLE
Question about meaning of FetchedBatch#offset_lag

### ISSUE THREAD

**Issue by michaelsauter** [zendesk/ruby-kafka#332]
I'm a bit confused what `FetchedBatch#offset_lag` actually means. Consider this:

```
[5] pry(main)> batch.highwater_mark_offset
=> 6718
[6] pry(main)> batch.first_offset
=> 0
[7] pry(main)> batch.last_offset                                                                     
=> 6717
[8] pry(main)> batch.offset_lag
=> 1
```

The operation fetched all messages that are in the partition. However, the lag is 1. Shouldn't it be 0? I understand this is because the `highwater_mark_offset` is the offset of the next message, and `last_offset` is the offset of the last message in the batch.

But intuitively, if I have read the last message in a partition, shouldn't the lag be 0?

* Version of Ruby: 2.2.4
* Version of Kafka: 0.10.1
* Version of ruby-kafka: 0.3.16

**Comment by dasch** [comment]
That looks like a bug... the lag is supposed to be zero in this case. Care to create a PR?

**Comment by michaelsauter** [comment]
Okay, I'll have a look early next week.
