### ISSUE TITLE
Allow consumers to run with no assigned partitions

### ISSUE THREAD

**Issue by piavka** [zendesk/ruby-kafka#338]
Currently if consumer has no partitions assigned it will get exception and die.
If exception is handled and consumer tries to consume again this causes it to join the group again and trigger rebalance, so if there are more consumers than partitions it would cause endless rebalances. There should be option to keep the consumer alive idle in a group where it could get chance to get some partitions on next rabalance. It should be perfectly ok to run consumers over provisioned.

**Comment by dasch** [comment]
That's reasonable.

**Comment by meinac** [comment]
Do you know why this happens? In my case I have one consumer which is connected to 2 brokers for a topic which has only one partition and I get this error once in a while(eg. in each 4 hours).

**Comment by dasch** [comment]
@meinac it shouldn't happen if there's only one instance of your consumer – it sounds like sometimes you have two instances running simultaneously.

**Comment by meinac** [comment]
Thanks for your quick response, I've figured out we were using same group name on different environments with same kafka cluster 😢 

Btw thanks for this cool gem.

**Comment by dasch** [comment]
No problem :-)

**Comment by jdconley** [comment]
I've run into this issue with the fluentd-kafka plugin. I have three fluentd instances for HA in a kubernetes cluster and they can consume from topics that have fewer than 3 partitions.

https://github.com/fluent/fluent-plugin-kafka/issues/129

I hacked in some exception handling and a random sleep for now, but I do not think this is an exceptional case.

**Comment by dasch** [comment]
@jdconley I'd be open to a PR.

**Comment by mensfeld** [comment]
@dasch  wouldn't a simple configurable sleep and retry on assignment be enough to handle that case?

**Comment by dasch** [comment]
Probably – the consumer would have to wait for another group sync in order to get assigned new partitions.

**Comment by dasch** [comment]
Fixed by #439.

**Comment by mensfeld** [comment]
<3 waited for this one!

**Comment by dasch** [comment]
![](https://media.giphy.com/media/YTbZzCkRQCEJa/giphy.gif)
