### ISSUE TITLE
Consumer API production-ready?

### ISSUE THREAD

**Issue by jonathan-upstart** [zendesk/ruby-kafka#339]
Hi, thanks for your fantastic work on creating this gem. My company is interested in using this gem for our production system, but we're concerned that the consumer API may not be production ready. The readme says, `Warning: The Consumer API is still alpha level and will likely change. The consumer code should not be considered stable, as it hasn't been exhaustively tested in production environments yet.`

Is this still true, and if so when do you expect the consumer API to be stable? Until that happens, we will likely hold off on using this gem.

Thank you!

**Comment by dasch** [comment]
I should probably update that warning – the consumer API has been used in production at Zendesk (and probably a bunch of other places) for quite some time now. However, you should be aware that the current IO engine doesn't work well with very high throughputs or large consumer groups. There are lots of optimizations that need to be done, some of them rather involved, before I'd call the API "high performance". But it should be ready for basic message consumption.

**Comment by dasch** [comment]
I've updated the README.
