### ISSUE TITLE
min_bytes will not be overridden by max_wait_time if max_wait_time is set a value which are more than 10 secs

### ISSUE THREAD

**Issue by gokusleepy2** [zendesk/ruby-kafka#343]
* Version of Ruby: 2.3
* Version of Kafka: 0.10.2-IV0
* Version of ruby-kafka: 0.3.11

I get messages by

    consumer.each_batch(min_bytes: 1024 * 5, max_wait_time: 30) do |message|
      # ...
    end

If the value of max_wait_time I set is less or equal to 10 secs, I will get the message as expected. But, when the value is between 12 and 30, I will not receive any message until the messages size reaches the limit of min_bytes.

Can you give me some tips? Thank you in advance!

**Comment by dasch** [comment]
Can you try this with other versions of Kafka? The client doesn't really do anything here, the broker (i.e. Kafka itself) decides when to return data to the client.

**Comment by gokusleepy2** [comment]
Thanks for your reply!

I have tried an old verion 0.9.0.1 of Kafka, but the issue still exists.

I try to change the heartbeat, session_timeout, but it doesn't work.

**Comment by dasch** [comment]
I think you should try to ask on a Kafka mailing list or add an issue to their repo – I don't think this is related to ruby-kafka, as it just passes those parameters along to the Kafka cluster.

**Comment by gokusleepy2** [comment]
OK, thank you!  Last question, The value about session_timeout and heartbeat_interval in ruby-kafka are refer to sec rather than msec, is this right?

**Comment by dasch** [comment]
Yes, all durations in ruby-kafka are in seconds.

**Comment by zhoplocal** [comment]
@gokusleepy2 how did you solve your issue? I'm facing the same.

**Comment by gokusleepy2** [comment]
@zhoplocal I never solved it. But, if your message requires strictly time limit，you can set max_wait_time less than 10secs, or just set min_bytes as a small value. In my case, the volume of my message is huge, so my key point is min_bytes.

**Comment by dasch** [comment]
:+1:

Closing this.
