### ISSUE TITLE
Weird offset behavior after rebalancing 

### ISSUE THREAD

**Issue by ale7714** [zendesk/ruby-kafka#347]
* Version of Ruby: 2.2.3
* Version of Kafka: 0.9.0.1
* Version of ruby-kafka: master branch

Had an instance consuming from a `topicA/partition0`,  it fails to send a heartbeat but before failing it had committed the offset to X. Then the partition tries to join, gets assigned a different partition and `topicA/partition0` is picked up by another service but the offset is way behind than X (around 8 hours of messages). Causing to have a massive duplication processing. 

This behavior doesn't happen all the time which makes it hard to reproduce locally (been unable to so far). Have someone else experience a similar issue?

**Comment by dasch** [comment]
Do you have logs from the incident?

**Comment by ale7714** [comment]
@dasch I do, here ithttps://gist.github.com/ale7714/1c3836cbf0d00d7e3c82c7c4e79c52f7
You can see how at 8:55:51 analysis-results/0 offset is 6683654259
```
Apr 27 08:55:51 ip-10-20-51-10 docker/wally:  I, [2017-04-27T12:55:51.956537 #1]  INFO -- wally-3760fbc8-306f-4123-a9c1-398980c06a38: Committing offsets: analysis-results/0:6683654259
```
And then at 08:55:55 the offset is 6678540862. 
```
Apr 27 08:55:55 ip-10-20-52-86 docker/wally:  I, [2017-04-27T12:55:55.477133 #1]  INFO -- wally-7d8f1f09-6d1f-42f6-b3f4-adfa8b30a2c1: Consumer: marking analysis-results/0:6678540862 as processed 
```
You can see how some instances failed to send a hearbeat so they join the group again and partitions are re-assigned.

**Comment by dasch** [comment]
Hmm. This could be because the consumer that got assigned the partition after the re-sync had handled that partition some time in the past – and therefore had an out-of-date offset position for it. Would you care to take a look at the consumer and see if you can find some evidence for a bug?

**Comment by ale7714** [comment]
@dasch actually that's a good clue. Looking at logs the instance that picked up analysis-results/0 at a really old offset, had been assigned this partition before.
```
Apr 27 08:55:52 ip-10-20-52-86 docker/wally:  I, [2017-04-27T12:55:52.057410 #1]  INFO -- wally-7d8f1f09-6d1f-42f6-b3f4-adfa8b30a2c1: Committing offsets: analysis-results/7:555092338, analysis-results/0:6678540746
Apr 27 08:55:52 ip-10-20-52-86 docker/wally:  I, [2017-04-27T12:55:52.062228 #1]  INFO -- wally-7d8f1f09-6d1f-42f6-b3f4-adfa8b30a2c1: Runner: flushed buffers offset=555092337
Apr 27 08:55:52 ip-10-20-52-86 docker/wally:  I, [2017-04-27T12:55:52.068908 #1]  INFO -- wally-7d8f1f09-6d1f-42f6-b3f4-adfa8b30a2c1: Committing offsets: analysis-results/7:555092339, analysis-results/0:6678540746
```
As you can see,  the instance was only updating `analysis-results/7` offset pointer but sill had `analysis-results/0` on memory even  when is not changing. 

Could there be an issue in this line https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/consumer.rb#L345?

**Comment by dasch** [comment]
That could be it – you may have to look at the implementation of that method and see if you can break it.

**Comment by ale7714** [comment]
@dasch is there a reason why the gem only clear all the offsets after joining only if the generation_id is different?

**Comment by dasch** [comment]
@ale7714 there's a lot of subtlety in the group membership protocol – I believe that was done in order to not lose the uncommitted checkpoint state if not necessary.

**Comment by dasch** [comment]
There may be a lot of rejoins if the group isn't completely stable (there's a leave/rejoin any time a member comes or goes) and we don't want to keep losing track of the offset positions.

**Comment by ale7714** [comment]
@dasch Right, thank you. I understand that. Although i think another side effect of only processing/committing offset manually is that we get quite often in the situation explained here https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/consumer.rb#L317-L329.
So discussing more about this with one of my coworkers, we were thinking we should be able to choose to clear_offset, either by: 
 * checking if auto-commits are false, and if that the case always clear offsets 
 * or, by passing a new option to the consumer to say `clear_offsets_on_join` 

WDYT?

**Comment by ale7714** [comment]
In our case, handling a few duplicates from kafka is acceptable. Losing messages is not an option, so we prefer to fail and not commit the offset. So we wouldn't mind having a "lower" startup time when the instance is joining the group, if that avoids reading from an old offset.

**Comment by dasch** [comment]
It does sound like this is maybe related to your manual offset marking logic. Can you share a minimal but complete example script that reproduces the issue?

**Comment by ale7714** [comment]
@dasch that's right I've been trying out a couple of things and realize that on my buffer I could have a message from a previously assigned partition. And that would make the consumer have an old offset for a partition that consumer is not assigned anymore. Now that I feel more confident on how should we manage those edge cases when we don't auto commit. I'll open a PR.

**Comment by ale7714** [comment]
i'll close this since this issue was related to our manual offset management.

**Comment by Elyahou** [comment]
@ale7714 I also get this exact behavior on my consumer, when commiting offsets manually... Can you share your thoughts about how it is related to manual offset commit ?

I get this on last version of ruby-kafka `0.7.5`
