### ISSUE TITLE
consumer blocking all threads

### ISSUE THREAD

**Issue by baelter** [zendesk/ruby-kafka#351]
* Version of Ruby: 2.4.0
* Version of Kafka: 0.10.2.0
* Version of ruby-kafka: 0.3.17

###### Steps to reproduce

```ruby
kafka = Kafka.new(...)
consumer = kafka.consumer(group_id: 'my_group')
consumer.subscribe('my_topic')
t1 = Thread.new do
  loop do
    puts "Another thread"
    sleep 5
  end
end
t2 = Thread.new do
  consumer.each_message do |msg|
    ...
    next / sleep 1 / Thread.current.pass / nothing
  end
end

sleep
```

###### Expected outcome

"Another thread" every ~ 5 seconds

###### Actual outcome

Messages are consumed fine, but no other thread gets any cpu time.

**Comment by baelter** [comment]
Nevermind,

**Comment by Paxa** [comment]
Having save issue, how did you solve it?
Also process consumes all CPU

**Comment by mensfeld** [comment]
@Paxa  @baelter 
Don't use the same client from more than one thread.
Probably you will be better going with higher level libs that take care of stuff like that for you. See the https://github.com/zendesk/ruby-kafka#higher-level-libraries section of the readme file.
