### ISSUE TITLE
Latest version support

### ISSUE THREAD

**Issue by vivekmarakana** [zendesk/ruby-kafka#354]
Does this support producers and consumers fully in kafka 0.10.2.1? I'm frequently getting errors `Error committing offsets: Kafka::UnknownMemberId`

**Comment by dasch** [comment]
Can you post some logs that could give more insight into what's happening?

0.10 is supposed to be backwards compatible with 0.9, which is the version we're currently testing against.

**Comment by vivekmarakana** [comment]
This was the issue related to timeout which kicked the worker out of group after some idle time. Got is solved by changing configuration.

**Comment by dasch** [comment]
@vivekmarakana I've just released `v0.5.0.beta1` with support for Kafka 0.10. Would you be willing to run this in production for some time and see if everything works as expected?
