### ISSUE TITLE
Stability and v1.0

### ISSUE THREAD

**Issue by dm123455** [zendesk/ruby-kafka#374]
I had some questions around using Ruby Kafka client for Kafka 0.9:

1. The roadmap states that "This release is running in production at Zendesk, but it's still not recommended that you use it when data loss is unacceptable. It will take a little while until all edge cases have been uncovered and handled." have we determined what work needs to be done to cover edge the cases or to make the client more reliable?

2. Is there a current plan to implement a v1.0? What work remains to get there?

3. Does a runnable task need to be set up which initializes the consumer and executes the poll loop indefinitely until shutdown? If yes how is the community doing it for rails?

**Comment by dasch** [comment]
> The roadmap states that "This release is running in production at Zendesk, but it's still not recommended that you use it when data loss is unacceptable. It will take a little while until all edge cases have been uncovered and handled." have we determined what work needs to be done to cover edge the cases or to make the client more reliable?

I think I'm ready to remove that disclaimer – ruby-kafka has been very stable for quite a while now.

> Is there a current plan to implement a v1.0? What work remains to get there?

v1.0 for me is more a testament to the breadth of the developer community's maturity than the maturity of the code base. Right now there's a very small group of developers and when I'm not around it's difficult to get support. I'll only bump to v1.0 when that changes. You should regard the current releases as stable.

> Does a runnable task need to be set up which initializes the consumer and executes the poll loop indefinitely until shutdown? If yes how is the community doing it for rails?

There's documentation in the README on how to set up a runnable consumer. However, we've recently released [Racecar](https://github.com/zendesk/racecar), which was extracted from a Zendesk code base. This is the recommended way to get started with a Kafka consumer in Ruby. If you end up having more advanced needs, it's not difficult to roll your own.

**Comment by dm123455** [comment]
Thanks for the response.

**Comment by dasch** [comment]
:+1:

**Comment by mensfeld** [comment]
@dasch  just for the record - I use ruby-kafka a lot and despite some minor problems that I've already reported (and you've already fixed) I consider ruby-kafka stable as well. Great job!

**Comment by dasch** [comment]
@mensfeld ❤️
