### ISSUE TITLE
Producer#send_messages signature

### ISSUE THREAD

**Issue by dkatten** [zendesk/ruby-kafka#38]
Looking at Producer#send_messages, we expect the producer instance to already have messages (which makes sense).

However, I was thinking about a more ruby-ish interface could be implemented as well. Something like:

```ruby
producer.send_messages do |buffer|
  buffer << Message.new payload, key: key
end

# ...

def send_messages(&block)
  # ...
  yield block if block_given?
  # ...
  shutdown
end
```
I'm thinking there might be a clean way to relieve the user of the setup/teardown procedure. I am also wondering if you could use Enumerable#lazy on the `buffer` to flush every X number of messages passed in, or even Y number of bytes.

I don't have any concrete ideas, but I've always thought a block was a natural construct for interfacing with kafka (both producer and consumer).

**Comment by dasch** [comment]
I think those are good idea – but for now I want the interface to be as simple as possible. There are many different use cases, and finding the right high-level API for all of them is difficult. The current primitives are the most basic building blocks, it's pretty easy to build on top.

One obvious API is an async producer that you produce messages to but that sends them periodically in the background.

Your example of sending every _n_ messages can also easily be implemented on top of Producer:

```ruby
class AutoSendProducer
  def initialize(producer, max_buffer_size)
    @producer = producer
    @max_buffer_size = max_buffer_size
  end

  def produce(value, **options)
    @producer.produce(value, **options)
    @producer.send_messages if @producer.buffer_size % @max_buffer_size == 0
  end
end
```

**Comment by dasch** [comment]
I may try to implement the block thing on top of `send_messages` in v0.2...

**Comment by dkatten** [comment]
Ooo that's neat too. My other concern is trapping signals to do proper shutdowns. That is something that I always have to do, and would love to abstract away.

Yeah, I would tag it 1.0, if anything. I just want to start the conversation :)

**Comment by dasch** [comment]
Yeah, proper shutdown is something we'll have to figure out, especially for consumers. I'd just like to wait before adding more API until I have a feel for a few more use cases.

**Comment by mensfeld** [comment]
@dasch  for consumers you could trap the signal and commit offset in place where the last message was processed (not consumed) and shutdown pretty fast.

You can check how Karafka handles that: https://github.com/karafka/karafka/blob/master/lib/karafka/process.rb and https://github.com/karafka/karafka/blob/master/lib/karafka/app.rb

One day, when this lib is ready, we will probably switch to it with Karafka so I will try to help you out guys (at least with comments)

**Comment by dasch** [comment]
@mensfeld thanks! I think it makes more sense for a framework such as Karafka to do such things – I'd like to have a clear separation between library and framework, with ruby-kafka being the former. It should provide the means of implementing advanced lifecycle management, but I'm not sure if it should itself install signal handlers.

I'm not sure if it'll work for e.g. `SIGKILL`, but wrapping stuff in `begin ... ensure` handles many cases.

**Comment by mensfeld** [comment]
@dasch  you can leave that then to us ;) as long as we will have possibility to commit offset manually we can handle that. I also think that this should be responsibility of a framework not a driver btw.

**Comment by dasch** [comment]
@mensfeld do you want to throw around some ideas for a Consumer API in #20?

**Comment by mensfeld** [comment]
@dasch  I will drop you some ideas and things that we use in Karafka. API implementation itself won't impact us as we plan to add adapter to this library and hide its internal implementation. As long as the API will allow us to do tihngs that we require, it will be ok :)

**Comment by dasch** [comment]
@mensfeld that's what I mean – I want to make sure that there's enough flexibility for you guys to work with. I've added some initial thoughts to the issue – I'd love some feedback on that.

**Comment by mensfeld** [comment]
@dasch  I will make sure to notify you about any stuff that would be useful for us :-) I also think that thanks to what we do, you could focus on providing a high quality low level driver and we could use that to implement the upper layers (like signal handling, loops, "server" like process, cli, etc)

**Comment by dasch** [comment]
:heart:

I'll most likely include a semi-high-level consumer loop in ruby-kafka, but will also allow other libraries to compose the behavior they want and exact control over e.g. offset commits.

**Comment by mensfeld** [comment]
@dasch  sounds great! fetch_loop definitely  will be used to develop simple consumers. Flexibility on the other hand will allow things like Karafka to use this lib

**Comment by dasch** [comment]
I'm going to close this for now – once more people are using ruby-kafka in production we'll have a better idea as to what the best API is.
