### ISSUE TITLE
Error committing offsets: Kafka::UnknownMemberId

### ISSUE THREAD

**Issue by ryantownsend** [zendesk/ruby-kafka#390]
My very basic consumer is having trouble with committing offsets back to Kafka, I have attempted to resolve this with the Heroku Kafka team, but they believe it to be a bug with `ruby-kafka` so have suggested I post an issue here.

Please refer to this log: [stdout.txt](https://github.com/zendesk/ruby-kafka/files/1217735/stdout.txt)

* Version of Ruby: `2.3.4`
* Version of Kafka: `0.10.2.1`
* Version of ruby-kafka: `0.4.0`

I have verified this problem exists with both `0.4.0` and `master`.

###### Steps to reproduce

```ruby
require 'logger'
require 'kafka'

logger = Logger.new($stdout)

$stdout.puts "=> Configuring Kafka connection"

$kafka = Kafka.new(
  client_id: "#{ENV['KAFKA_PREFIX']}#{ENV['HEROKU_APP_NAME']}-#{ENV['HEROKU_RELEASE_VERSION']}",
  seed_brokers: ENV['KAFKA_URL'].split(','),
  logger: logger,
  ssl_ca_cert: ENV['KAFKA_TRUSTED_CERT'],
  ssl_client_cert: ENV['KAFKA_CLIENT_CERT'],
  ssl_client_cert_key: ENV['KAFKA_CLIENT_CERT_KEY']
)

$stdout.puts "=> Configured Kafka connection"

consumer = $kafka.consumer(group_id: "#{ENV['KAFKA_PREFIX']}product-consumer")

consumer.subscribe("#{ENV['KAFKA_PREFIX']}productchanges")

# Stop the consumer when the SIGTERM signal is sent to the process.
# It's better to shut down gracefully than to kill the process.
trap('TERM') { consumer.stop }

# This will loop indefinitely, yielding each message in turn.
consumer.each_message(max_wait_time: 5) do |message|
  $stdout.puts "=> Received Event #{message.offset}"
  $stdout.puts "     topic: #{message.topic}"
  $stdout.puts "       key: #{message.key}"
  $stdout.puts "     value: #{message.value}"
end
```

###### Expected outcome

It shouldn't throw an error (see lines 42 and 130 in the log), or reprocess the same event (see line 33-26 and 121-124 in the log).

###### Actual outcome

`Error committing offsets: Kafka::UnknownMemberId` is thrown, and the same message is reprocessed multiple times.

**Comment by dasch** [comment]
1. Have you tried setting `max_wait_time` to 5? This could be due to the group having rebalanced while the consumer was busy processing messages.
2. Have many members are there in the group?

**Comment by ryantownsend** [comment]
1. This is already set by `consumer.each_message(max_wait_time: 5)` isn't it? Am I doing that wrong somehow?
2. Just this one consumer and a single producer

**Comment by dasch** [comment]
Sorry, meant setting it to 1.

**Comment by ryantownsend** [comment]
@dasch thanks so much – that's working now.

**Comment by dasch** [comment]
@ryantownsend you can probably increase the connect and socket timeouts in order to allow a higher `max_wait_time`. Note that [Racecar](https://github.com/zendesk/racecar) should shield you from these issues, as it does more validation on your config and in general has fewer sharp edges. Unless you need the raw power of ruby-kafka, you may be better off with a higher-level, opinionated framework built on top of ruby-kafka.

**Comment by ryantownsend** [comment]
@dasch thanks – I've passed the feedback on to Heroku so they can see if this is expected behaviour or whether there is a problem that needs addressing.

I gave Racecar a go prior to using ruby-kafka directly, I had some other issues so thought I'd simplify down to the lower-level library, but my plan is to retry using Racecar now and see how that goes – we definitely need something higher-level for use in our Rails apps.

**Comment by dasch** [comment]
@ryantownsend great! Do let me know if you find a problem with Racecar – it's still relatively early stages, but it also doesn't actually do much aside from loading configuration and handling signals.
