### ISSUE TITLE
[Minor] Kafka::ConnectionError (should be Kafka::AuthenticationError ?)

### ISSUE THREAD

**Issue by sparrovv** [zendesk/ruby-kafka#396]
* Version of Ruby: 2.3
* Version of Kafka: 0.1.2.0
* Version of ruby-kafka: 0.4

Hi, I've been trying to connect to kafka broker over SASL_SSL:

```    
kafka = Kafka.new(
  ssl_ca_cert: File.read('./certs/kafka-ca-cert'),
  sasl_plain_username: 'alice',
  sasl_plain_password: 'secret',
  seed_brokers: seed_brokers,
  client_id: "foobar" 
)

producer = kafka.producer
message = {key: SecureRandom.hex, message: "TEST!", time: Time.now}
producer.produce(message.to_json, topic: "foobar")
producer.deliver_messages
```

and when I was passing the wrong password I was getting:
```
Kafka::ConnectionError: Could not connect to any of the seed brokers:
```

It's minor, but I would expect something more specific than the `ConnectionError`.

**Comment by dasch** [comment]
Hmm. I'm not sure if that's possible.

**Comment by dasch** [comment]
I think https://github.com/zendesk/ruby-kafka/pull/385 will help with this.

**Comment by dasch** [comment]
Closing this for now. I would be open to a PR that improved the error message, if possible.
