### ISSUE TITLE
More/better error handling

### ISSUE THREAD

**Issue by elliotcm** [zendesk/ruby-kafka#406]
Hi there,

We'd like to be able to receive Kafka exceptions to HoneyBadger (or insert hosted exception platform here).  You have your async threads set to terminate on error which is great, but there's a couple of downsides to the library:

- Useful debugging information is left out of error bodies and instead relies on logging (if sent at all), e.g. https://github.com/zendesk/ruby-kafka/blob/887113f590231999b2a43640e8702e1092558f36/lib/kafka/async_producer.rb#L162
- Some exceptions are caught and swallowed to prevent the threads from crashing, but this means they're not accessible to our error handling systems (and sometimes not reported anywhere), e.g. https://github.com/zendesk/ruby-kafka/blob/887113f590231999b2a43640e8702e1092558f36/lib/kafka/producer.rb#L361-L369 and https://github.com/zendesk/ruby-kafka/blob/887113f590231999b2a43640e8702e1092558f36/lib/kafka/async_producer.rb#L215-L226

I'd like to propose an optional error handler class, instance, or block to be passed into the producer options which can be called by the library code whenever an exception is caught and not re-raised.

I'm happy to do this as a PR, what do you think of this approach?

**Comment by dasch** [comment]
I'm not sure this is the best approach, for the simple reason that errors in Kafka are not _exceptional_, and do not necessarily indicate bugs or misconfiguration. During some operations, the cluster will simply be a bit unstable, which will result in errors being returned. The right approach to this is to _monitor_ the error counts and trigger an alert if the errors _persist_. Exception trackers are best for debugging configuration or code bugs.

That being said, it would make sense for the exceptions that _are_ raised to include sufficient information, e.g. BufferOverflow could include more information about the message that was dropped.

**Comment by kyprifog** [comment]
I have to disagree, I think the error handling can definitely be tightened up.  The proposed solution may not be the best one but I find this library very frustrating in that 90% of most errors Ive encountered (with causes ranging across the board) result in a "Could not connect to any of the seed brokers".  My guess is there is a giant forgiving rescue for a broad range of errors somewhere pointing to this error message (I haven't dug into the code for a while).   This makes ruby-kafka really frustrating to use.

**Comment by dasch** [comment]
The reason errors are not bubbles up to clients of the async producer is that it is designed for resilience - your producer be partitioned from the brokers at times, but once a connection has been made everything can continue. In fault tolerant systems, errors are part of the game. 

Do you have a proper monitoring system set up?

**Comment by dasch** [comment]
Closing this for now. ruby-kafka should _not_ just be monitored with exception trackers, you need a full-fledged monitoring solution that lets you look at buffer sizes and error rates, not just individual exceptions.
