### ISSUE TITLE
unable to specify message content Type (ex:- application/json) when delivering message to kafka topic

### ISSUE THREAD

**Issue by ilikecodingg** [zendesk/ruby-kafka#413]
If this is a bug report, please fill out the following:

* Version of Ruby: JRuby 9.1
* Version of Kafka: 2.10-0.10.1.1
* Version of ruby-kafka: 0.3.17

Please verify that the problem you're seeing hasn't been fixed by the current `master` of ruby-kafka.

###### Steps to reproduce

# Please write an example that reproduces the problem you're describing.
```kafka = Kafka.new(...)
kafka.deliver_message("Hello, World!", topic: "greetings")

###### Expected outcome

kafka.deliver_message("Hello, World!", topic: "greetings", content-Type:"application/json")
expected option like content-Type

###### Actual outcome

What actually happened.

but, has no option to specify content type of the message that is put in Kafka topic

**Comment by Elyahou** [comment]
https://github.com/zendesk/ruby-kafka#serialization

**Comment by dasch** [comment]
@ilikecodingg that is not a Kafka feature.
