### ISSUE TITLE
unable to set request headers

### ISSUE THREAD

**Issue by alexandrapersea** [zendesk/ruby-kafka#414]
I need to use some custom headers when connecting to Kafka. Is there a way i could set them in the ruby kafka client?

**Comment by mensfeld** [comment]
@alexandrapersea no. It is a Kafka v0.11.0.0 feature that is not yet implemented.

**Comment by alexandrapersea** [comment]
Thank you!

**Comment by johntdyer** [comment]
@alexandrapersea  Now that a bit of time has passed is there any chance you guys might reconsider this ?

**Comment by mainameiz** [comment]
It is ready https://github.com/zendesk/ruby-kafka/blob/master/CHANGELOG.md#070

> Support record headers (#604).

https://github.com/zendesk/ruby-kafka/pull/604
