### ISSUE TITLE
Request content-type

### ISSUE THREAD

**Issue by alexandrapersea** [zendesk/ruby-kafka#415]
When i'm writing to the kafka topic using the api like so ```curl -X POST -H "Content-Type: application/vnd.kafka.json.v2+json"  --data '{"records":[{"value":{"foo":"bar"}}]}' "http://kafka:port/topics/abc```  it works.

 When i'm trying to write to a topic using the ruby-kafka client i get 
`Failed to fetch metadata from http://kafka:port: Connection error: EOFError`.

My guess would be that the request fails because the content-type headers are not what the cluster expects. 

What are the ruby-kafka client default request content-type headers?
Could this be the reason why te request fails? If not,  am i doing something wrong, is there something I can do to make it work?

**Comment by Elyahou** [comment]
ruby-kafka do not use the http protocol, but kafka protocol, and there is content-type to send when using the kafka protocol.

which seed broker do you use with ruby-kafka ?

**Comment by mensfeld** [comment]
Hey. There were several similar issues. Ruby Kafka is agnostic and does not support headers.

**Comment by Elyahou** [comment]
@alexandrapersea You should use `18.220.190.71:9092` in place of `http://18.220.190.71:9092`

**Comment by alexandrapersea** [comment]
I have changed to protocol because of this error:

`Kafka::ConnectionError: Could not connect to any of the seed brokers:
- kafka://18.220.190.71:9092: Operation timed out`

**Comment by Elyahou** [comment]
it seems your broker is not available, you can check if maybe some firewall block this port

**Comment by dasch** [comment]
@alexandrapersea can you start by following these steps in the README? https://github.com/zendesk/ruby-kafka#setting-up-the-kafka-client
