### ISSUE TITLE
async max_queue_size

### ISSUE THREAD

**Issue by cgeers** [zendesk/ruby-kafka#421]
ruby: 2.3
ruby-kafka: 0.4.2

The async producer's `:max_queue_size` option may be misleading.  [Some of the documentation](https://github.com/zendesk/ruby-kafka/blob/v0.4.2/lib/kafka/async_producer.rb#L23-L36) indicates that it would be unreasonable to expect that any more messages than `:max_queue_size` would ever be in the buffer, but this doesn't seem to be true. In the cases where max_queue_size is reached, *only* an exception is raised without actually pruning the queue down to `:max_queue_size`.

The net effect of this behavior is to allow network interruptions or kafka broker outages/downtime to cause accumulation of messages in the queue indefinitely. This may be desired in some where losing messages is bad, but in cases where it is OK for messages to be dropped, this could lead to memory exhaustion with an unbounded queue.

I'd like to propose one of two options for the async producer:

* Make the queue accessible in order to allow the calling thread to rescue the BufferOverflow and manipulate the queue as they see fit.
* Allow a new option to the async producer that will prune/shift off the queue to keep it's size within `:max_queue_size` when a BufferOverflow is reached.

I'm happy to put in a PR for either approach.  Thanks for your thoughts.

**Comment by dasch** [comment]
The queue is bounded - once the max size is reached, no new messages will be placed in it..

**Comment by cgeers** [comment]
whoops. I see now that is indeed the case.  sorry for the noise
