### ISSUE TITLE
Insufficient #stop behaviour for non busy topics with manual offset commits

### ISSUE THREAD

**Issue by mensfeld** [zendesk/ruby-kafka#424]
This problem is related to all the ruby-kafka versions, since they all have the same ```#stop``` logic.

As described in th docs, the signal gets caught and consumer shuts-down:

```ruby
trap("TERM") { consumer.stop }
```

The problem itself is the trap context which is in a separate thread. It modifies the ```@running``` flag on a consumer and during the next ```consumer_loop``` iteration it stops. It creates a problem with manual offset commitment in a particular case described below. 

This is sufficient enough for:

- the automatic offset commits as they happen upon new messages processing end
- manual offset commit on a busy topics in which we can perform a periodical offset commitment (for example every 10 batches, etc)

However one case is not covered: topics that aren't that busy. Let's assume I get 1 message per 10 minutes and I commit every 10 messages OR during the shutdown process. 

After 5 messages (50 minutes) I get a ```TERM``` upon which I want to commit the offset BUT I won't get any messages for next 10 minutes, which means that my business logic won't get evaluated as it gets evaluated upon new messages arrival.

Theoretically I could try passing last message to the trap context thread and use ```mark_message_as_processed``` from it, however it seems it's not the right way (multithreading same consumer would be crazy).

So the general problem is, that for non busy topics a ```yield``` in a ```consumer_loop``` upon messages is insufficient for handling the manual offset commitment during the shutdown process.

Obviously I cannot commit the offset after the ```#stop``` is sent because consumer is already without any partitions assigned. 

How could we solve it? One of the ideas is to provide an additional callback that could be executed **after** the ```consumer_loop``` (if any)  but **before** the consumer leaves the group. Something like that should be sufficient to commit the offset only during the shutdown:

```ruby
buffer = []

consumer.before_stop do
  consumer.mark_message_as_processed(buffer.last) unless buffer.empty?
  consumer.commit_offsets
end

consumer.each_message(automatically_mark_as_processed: false) do |message|
  buffer << message
end
```

Without being able to provide additional logic (in any way) it's impossible to create long lasting transactions that get committed after a period of time **or** during the shutdown.

**Comment by dasch** [comment]
I really want to avoid having a bunch of callbacks. The issue here seems to be that manual offset management isn't really thought out completely. I must admit that I'm sort of skeptical of adding a bunch of complexity to support what seems to me to be an edge case. Why is manual offset management used here?

I would personally _always_ have a time bound on commits...

**Comment by filiptepper** [comment]
@dasch Not sure if @mensfeld is referring to our case, but what we do is:
- start a consumer,
- start consuming,
- store processed messages locally,
- when a certain file size is reached - we store messages in external store, commit offsets.

Our consumers run in Docker containers and we would really like to make sure that processed are pushed out to external storage on shutdown as well, and for that we also need a reliable manual offset management.

I'm more than happy to hear whether you have an alternative solution that could satisfy our requirements.

Right now we're using JRuby with Kafka jar for this, but for performance / resources we would love to switch to MRI.

**Comment by mensfeld** [comment]
@dasch hello. Good to have you back after the holiday ;)
@filiptepper I have a case like this one as well ;)

> I really want to avoid having a bunch of callbacks. The issue here seems to be that manual offset management isn't really thought out completely.

On the other hand, we cannot use a transaction like multi-batch approach due to this issue (and the transaction spin up for couple of hours for me).

I'm not a huge fan of callbacks as well, but due to how ruby handles signals, I don't see any other way to do this, especially with the current fetching loop implementation.

**Comment by dasch** [comment]
Would it not be possible to do something like this?

```ruby
trap("TERM") { consumer.stop }

consumer.each_message do |message|
  # ...
  manual_offset_stuff
end

commit_offsets # this is always called after the consumer shuts down.
```

**Comment by dasch** [comment]
Is it because you want to use Kafka's offset API but don't want things to be done automatically? Maybe it would be better to use a separate offset database that isn't tied up to the consumer group lifecycle stuff, although you'd lose some double-processing protections.

**Comment by dasch** [comment]
As for this:

```ruby
consumer.before_stop do
  consumer.mark_message_as_processed(buffer.last) unless buffer.empty?
  consumer.commit_offsets
end
```

Calling `mark_message_as_processed(buffer.last)` would essentially drop processing of those messages. Is that what you want?

I'm open to adding a callback as a last resort, I just want to make absolutely sure there isn't a better alternative first.

**Comment by mensfeld** [comment]
@dasch no because the consumer is already without a group:

https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/consumer.rb#L337

it will leave it before I can do anything (aka commit the offset).

What I want to achieve, is possibility to commit the offset manually on the exist. 

I named it shitty ;) I would expect it to run before the consumer is stopped but after I've processed those messages via the ```yield``` api.

**Comment by dasch** [comment]
So the basic use case is a long-running buffer that exceeds individual batches, with processing taking place periodically and unrelated to the Kafka message processing. I think it might be worth exploring using an external offset store and manually seeking the partitions on startup – maybe even store the offsets in your output database alongside your data. Would that be impossible for you?

**Comment by dasch** [comment]
I think it would always be a challenge to shoehorn a processing system that goes beyond the fetch-batch lifecycle. With that being said, have you looked at https://github.com/zendesk/ruby-kafka/pull/369? It might provide a more fitting level of abstraction.

**Comment by mensfeld** [comment]
@dasch I agree but kafka transactions seem really natural and easy to grasp in terms of using them the way I intend. 

The code presented in #369 could do what I need with some additional flavor on my side but on the other hand using that instead of the std api creates more cases to handle (as I have only a single case in which I want a manual offset like that) but I guess it is inevitable. The last question would be about the performance but I guess it should remain the same as it more or less mimics the fetch loop.

**Comment by dasch** [comment]
Yeah, you lose some of the automatic offset handling and error recovery stuff, but once you disable automatic offset management you have to handle a lot of stuff anyway...

**Comment by dasch** [comment]
Can you give it a shot and let me know if the API would work for you? I'm hesitant to merge the PR if it doesn't solve real problems like these.

**Comment by mensfeld** [comment]
@dasch yeah - just give me max 1 week as I'm quite busy till Friday.

The only issue that I see, is that now I will have to do a lot more things that I used to do with the standard consumer API (minus the stop callback) and in terms of amount of work, monkey patching the stop API would be much easier and would require way less work than using manual ```poll```. Nonetheless I will give it a try.

**Comment by mensfeld** [comment]
I'm closing this one after discussion with @dasch. ```#stop``` behavior is still insufficient and other means must be taken to ensure a possibility to do some pre stop stuff, but due to the #438 I will solve it in another way. Also I will further explore #369 to make sure that it also can  be sufficient enough for advanced usage.

Please reopen if needed.
