### ISSUE TITLE
Kafka 0.11.0.0 log format?

### ISSUE THREAD

**Issue by marcosArruda** [zendesk/ruby-kafka#425]
1) Hi guys, do you plan to implement 0.11.0.0 support?

2) Do you know if we change kafka(server) 0.11.0.0 log format to 0.11.0 ruby-kafka works?

Thanks!

**Comment by tcrayford** [comment]
I can't speak to `1`, but as to 2.:

ruby-kafka does work fine with 0.11.0.0 and 0.11.0.1, barring the considerations in kafka's 0.11 upgrade guide: http://kafka.apache.org/documentation.html#upgrade_1100_notable

**Comment by mensfeld** [comment]
@marcosArruda @tcrayford work with 0.11 here as well - at least in mine scope.

**Comment by dasch** [comment]
@marcosArruda I plan to add 0.10 support in the near term – this will provide message timestamp support. It will take a while before 0.11 features will be supported, but ruby-kafka should continue to work with 0.11 brokers.
