### ISSUE TITLE
Non-obvious interaction between max_wait_time and number of brokers

### ISSUE THREAD

**Issue by jturkel** [zendesk/ruby-kafka#433]
* Version of Ruby: 2.4.2
* Version of Kafka: 0.9.0.1
* Version of ruby-kafka: 0.4.2

The `max_wait_time` option for the `Consumer#each_batch`/`Consumer#each_message` methods seems to apply to the fetch from each broker rather than the overall fetch operation. This can lead to frequent session timeouts if there are more than a few brokers and a consumer is fetching from low traffic topics. 

In our setup we're using 5 brokers and the defaults of a 30 second session timeout, 10 second heartbeat interval and 5 second max wait time. This can lead fetch operations that take 25 seconds causing periodic session timeouts since the last heartbeat before the fetch operation may have been up to 9.9 seconds ago. The default settings completely stop working if there are 6 or more brokers since you can wait for 30 seconds which is the session timeout.

I can think of a few potential solutions:

1) Perform fetch requests in parallel using either async i/o or threads so the entire fetch operation is bounded by `max_wait_time`. This is what the Java client does but it's a fair amount of work. Based on other issues it looks like you've explored parallelization in the past.
2) Automatically divide the `max_wait_time` by the number of brokers we're fetching from. This works reasonably well since applications don't need to tune settings as brokers are added/removed. This is the workaround we've implemented on our side.
3) Send heartbeats in between fetches to each broker
4) Document the current behavior. This isn't ideal but it at least makes it a known issue :)

I'm happy to help out with a PR if one of these options sounds good to you.

**Comment by dasch** [comment]
The plan is to fetch from the brokers concurrently, but as you say, it's quite complicated once you have to deal with all the error scenarios. I hope to be able to work on it soon, though.

In the meantime, maybe a change of the defaults would make sense (unfortunately, I believe the session timeout is already as high as is allowed by Kafka) as well as a note in the README. PRs are always welcome.

**Comment by jturkel** [comment]
I've opened #434 to change the default and update the README. Let me know what you think. Thanks!
