### ISSUE TITLE
Frequent opening and closing of connections  and large number of connections with async producer

### ISSUE THREAD

**Issue by spectorar** [zendesk/ruby-kafka#435]
This is a bit of a general question to get a sanity check that what I am seeing is not normal behavior. Note that I am using an async producer.

I am seeing a ton of the following in my ruby-kafka logs:
```
I, [2017-10-18T18:13:37.395237 #20183]  INFO -- : New topics added to target list: application_logs
I, [2017-10-18T18:13:37.395309 #20183]  INFO -- : Fetching cluster metadata from kafka://kafka01.secure.cloudmine.me:9092
D, [2017-10-18T18:13:37.395387 #20183] DEBUG -- : Opening connection to kafka01.secure.cloudmine.me:9092 with client id platform_logstash...
D, [2017-10-18T18:13:37.395708 #20183] DEBUG -- : Sending request 1 to kafka01.secure.cloudmine.me:9092
D, [2017-10-18T18:13:37.395811 #20183] DEBUG -- : Waiting for response 1 from kafka01.secure.cloudmine.me:9092
D, [2017-10-18T18:13:37.396364 #20183] DEBUG -- : Received response 1 from kafka01.secure.cloudmine.me:9092
I, [2017-10-18T18:13:37.396407 #20183]  INFO -- : Discovered cluster metadata; nodes: kafka01.secure.cloudmine.me:9092 (node_id=1), kafka02.secure.cloudmine.me:9092 (node_id=2), kafka03.secure.cloudmine.me:9092 (node_id=3)
D, [2017-10-18T18:13:37.396429 #20183] DEBUG -- : Closing socket to kafka01.secure.cloudmine.me:9092
D, [2017-10-18T18:13:37.396579 #20183] DEBUG -- : Current leader for application_logs/8 is node kafka03.secure.cloudmine.me:9092 (node_id=3)
I, [2017-10-18T18:13:37.396620 #20183]  INFO -- : Sending 1 messages to kafka03.secure.cloudmine.me:9092 (node_id=3)
D, [2017-10-18T18:13:37.396678 #20183] DEBUG -- : Opening connection to kafka03.secure.cloudmine.me:9092 with client id platform_logstash...
D, [2017-10-18T18:13:37.397557 #20183] DEBUG -- : Sending request 1 to kafka03.secure.cloudmine.me:9092
D, [2017-10-18T18:13:37.397747 #20183] DEBUG -- : Waiting for response 1 from kafka03.secure.cloudmine.me:9092
D, [2017-10-18T18:13:37.399995 #20183] DEBUG -- : Received response 1 from kafka03.secure.cloudmine.me:9092
D, [2017-10-18T18:13:37.400065 #20183] DEBUG -- : Successfully appended 1 messages to application_logs/8
```
I might get roughly 50 or more of these blocks per second. What is confusing and concerning is that the app seems to be constantly opening and closing connections to Kafka and that each one of these blocks says "Sending 1 messages". I have configured the async producer to send every 250 messages or every 30 seconds. There are 24 workers on a given server, they each have their own producer, and all producers are logging to this same log, but the frequency is still much higher than I would expect.

Additionally I am seeing what seems to be a very large number of connections to Kafka:
```
$ sudo lsof -i :9092 | wc -l
4289
```

If I `watch` this command I can see the number rising steadily by a handful every half second and at some point it'll drop by hundreds, so seemingly whatever is creating and holding on to these connections is getting cleaned up.

Not asking you guys to solve this problem (although if you have any guesses or tips for what to look at, that would be great), but just want to confirm that this is unusual - that there shouldn't be thousands of Kafka connections, that they shouldn't be opening and closing constantly, and that I shouldn't be sending one message at at time given my configuration. 

Thanks for your help.

**Comment by dasch** [comment]
This is definitely unusual – can you paste a snippet containing the way you set up and keep track of your async producer instances? My guess is that you're instantiating a _new_ async producer whenever you send a message. That would explain that you only send a single message at a time, and that you have so many open connections – each async producer's background worker is keeping a connection open to each broker in your cluster. After a while, the idle connections will be killed by either ruby-kafka or the brokers, thus explaining the sudden drops.

**Comment by dasch** [comment]
Also, is this a Rails app? If so, may I recommend you use [DeliveryBoy](https://github.com/zendesk/delivery_boy), which handles all of this for you?

**Comment by spectorar** [comment]
Thanks for the response. This was my hunch as well but the first 5 times I stared at the function that memoizes the producer it looked fine to me. Took some print statements to find a variable scoping issue that was causing a new producer to be created for each request. I tested a fix and it looks way better. I unfortunately found delivery boy a little while after one of our engineers deployed ruby-kafka but maybe I will take another look at it. Are there any major caveats to using it vs the core gem. Any major capabilities that you lose? Can you still integrate with datadog?

**Comment by dasch** [comment]
Unless you're doing fancy stuff, it should provide all you need. It also gives you some nice options when configuring.

The datadog integration works the same – it's just a wrapper around ruby-kafka.
