### ISSUE TITLE
[suggestion] Producing byte arrays and not only Strings (incl. binary strings)

### ISSUE THREAD

**Issue by syndbg** [zendesk/ruby-kafka#503]
We have an use case where we would want to produce byte arrays.

The following snippet is a small example with bytes array:

```Ruby
require "kafka"

kafka = Kafka.new(
  # At least one of these nodes must be available:
  seed_brokers: ["kafka1:9092", "kafka2:9092"],

  # Set an optional client id in order to identify the client to Kafka:
  client_id: "my-application",
)

# This is where it's important
kafka.deliver_message("ABC".bytes, topic: "example")
```

Obviously the difference is that the current implementation depends on Strings.

**Comment by dasch** [comment]
Closing due to a lack of activity. Please open a new issue if this is still a problem.
