### ISSUE TITLE
Datadog

### ISSUE THREAD

**Issue by klippx** [zendesk/ruby-kafka#513]
Just a friendly question, I dont have strong opinion, but I think it is a question more people could have.

So the question is, **why is DataDog part of RubyKafka client?** 

Wouldn't it have been nice if stuff like this was kept as a separate concern (probably separate gem) that could be opted in to? 

In our case for example, we are using Prometheus+Grafana, and we are relying on instrumentation from Phobos and RubyKafka to drive our metrics gathering as a standalone gem: https://github.com/phobos/phobos_prometheus

Maybe someone else prefers NewRelic, not all users has the same toolbox. 

If the case is that StatsD and/or DataDog code is loaded for us simply by requiring ruby-kafka, then it is bloat for us. Or maybe the case is that the code isn't loaded for us, but still, it would be nicer imo to have a separate gem for this since it is quite a different concern.

**Comment by dasch** [comment]
As per the docs, the code isn't loaded by default – you have to `require "kafka/datadog"`. One day it may be extracted, but for now it's much more convenient to ship it in the same gem, especially as there's a rather large API surface between the two code bases (all the AS::N events).

Feel free to contribute e.g. a Prometheus adapter if the Statsd doesn't work for that.
