### ISSUE TITLE
SSL connection should not require cert

### ISSUE THREAD

**Issue by bradurani** [zendesk/ruby-kafka#515]
Forgive me in advance, I don't much about SSL. I'm connecting to a Confluent-cloud managed cluster on AWS (https://www.confluent.io/confluent-cloud/). They give me SASL PLAIN credentials but no cert and specify HTTPS as the authentication algorithm:
```
ssl.endpoint.identification.algorithm=https
sasl.mechanism=PLAIN
request.timeout.ms=20000
bootstrap.servers=SASL_SSL://xxxxx.us-west-2.aws.confluent.cloud:9092,xxxxxxxx.us-west-2.aws.confluent.cloud:9093,xxxxxxx.us-west-2.aws.confluent.cloud:9094
retry.backoff.ms=500
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="<USERNAME>" password="<API_SECRET>";
security.protocol=SASL_SSL
```
I can't connect normally, however when I comment out this line: https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/client.rb#L546
It works. Should a cert be required to connect via SSL? It doesn't seem to be necessary.

* Version of Ruby: 2.3.0
* Version of Kafka: 1.0
* Version of ruby-kafka: 0.5.1

###### Steps to reproduce

```ruby
  client = Kafka.new(
    seed_brokers: [...],
    sasl_plain_username: 'foo',
    sasl_plain_password: 'bar'
  )

 client.deliver_message(...)
```

###### Expected outcome

It connects over SSL when it authenticates

###### Actual outcome

Errno::ECONNRESET

**Comment by dasch** [comment]
Without a certificate, you'd have no way to guard against man-in-the-middle attacks. Can you contact Confluent support and hear why they don't give out their certificate?

**Comment by dasch** [comment]
@tcrayford what's your take on this?

**Comment by tcrayford** [comment]
@dasch It could be fine if they're using a certificate that's already in the OS' trust store, but if not, it's ripe for MITM.

**Comment by dasch** [comment]
It's pretty unlikely that Confluent has a cert in the OS cert store...

@bradurani try contacting Confluent support first – you can point them here.

**Comment by tcrayford** [comment]
@dasch it seems entirely possible if they use letsencrypt or a wildcard cert

**Comment by dasch** [comment]
Hmm.

**Comment by bradurani** [comment]
After some research, I think I need to find the ca cert used to sign the confluent domain on my local os. Thanks!

**Comment by kunna** [comment]
I had same issue and it was solved by extract cert key from my local mac. and convert it to pem. thank you all.

https://www.digicert.com/ssl-support/p12-import-export-mac-server.htm

**Comment by yazan9** [comment]
@kunna-ujet I lost half a day on this, thanks !
