### ISSUE TITLE
Confusing behavior when consumers in the same group subscribe to different topics

### ISSUE THREAD

**Issue by jturkel** [zendesk/ruby-kafka#525]
* Version of Ruby: 2.3.4
* Version of Kafka: 10.2.1
* Version of ruby-kafka: 0.5.2

When a consumer joins a consumer group, it is only assigned partitions in topics the leader has subscribed to. This leads to the following behavior:

* The consumer won't receive any messages on topics it has subscribed to but the leader hasn't subscribed to
* The consumer will cause reads to stall in partitions in topics that the leader has subscribed to but the consumer hasn't subscribed to

We hit this due to a configuration error which caused us to stop reading certain partitions for awhile. This should either be treated as a configuration error or consumers should only be assigned partitions in topics they have subscribed to.

###### Steps to reproduce

Here's a half baked spec that demonstrates the problem via log output:

```ruby
describe "Consumer Group API", functional: true do
  let(:logger) do
    logger = Logger.new(STDOUT)
    logger.level = Logger::Severity::INFO
    logger.formatter = proc do |_severity, datetime, _progname, msg|
      "#{Thread.current.name} #{datetime}: #{msg}\n"
    end
    logger
  end

  let!(:topic1) { create_random_topic(num_partitions: 2) }
  let!(:topic2) { create_random_topic(num_partitions: 2) }

  before do
    kafka = Kafka.new(seed_brokers: kafka_brokers, client_id: "test", logger: logger)
    kafka.deliver_message("Hello #{topic1} partition 0!", topic: topic1, partition: 0)
    kafka.deliver_message("Hello #{topic1} partition 1!", topic: topic1, partition: 1)

    kafka.deliver_message("Hello #{topic2} partition 0!", topic: topic2, partition: 0)
    kafka.deliver_message("Hello #{topic2} partition 1!", topic: topic2, partition: 1)
    kafka.close
  end

  specify do
    t1 = Thread.new do
      Thread.current.name = 't1'
      logger.info('Starting thread')
      kafka = Kafka.new(seed_brokers: kafka_brokers, client_id: "test", logger: logger)
      begin
        consumer = kafka.consumer(group_id: 'my-group')
        consumer.subscribe(topic1)
        consumer.each_message(max_wait_time: 5) do |message|
          logger.info("Got message: #{message.value}")
        end
      ensure
        kafka.close
      end
    end

    sleep(10)

    t2 = Thread.new do
      Thread.current.name = 't2'
      logger.info('Starting thread')
      kafka = Kafka.new(seed_brokers: kafka_brokers, client_id: "test", logger: logger)
      begin
        consumer = kafka.consumer(group_id: 'my-group')
        consumer.subscribe(topic2)
        consumer.each_batch(max_wait_time: 5) do |message|
          logger.info("Got message: #{message.value}")
        end
      ensure
        kafka.close
      end
    end

    sleep(30)

    t1.kill
    t2.kill
    t1.join
    t2.join
  end
end
```

###### Expected outcome

I couldn't find much in the Kafka doc to indicate the "correct" behavior but it seems like this should either be treated as a configuration error that causes the consumer to crash or the consumer should only be assigned partitions in topics they have subscribed to. If we go with the latter approach than t1 should be assigned all partitions in topic `40edeb182cd479ee-topic-1` and t2 should be assigned all partitions in `40edeb182cd479ee-topic-2`.

###### Actual outcome

The spec outputs the following log statements:

```
# Log format is <thread name> <timestamp>: <message>
t1 2018-01-10 17:27:06 -0500: Starting thread
t1 2018-01-10 17:27:06 -0500: New topics added to target list: 40edeb182cd479ee-topic-1
t1 2018-01-10 17:27:06 -0500: Fetching cluster metadata from kafka://docker.local.host:9092
t1 2018-01-10 17:27:06 -0500: Discovered cluster metadata; nodes: docker.local.host:9093 (node_id=2), docker.local.host:9092 (node_id=1), docker.local.host:9094 (node_id=3)
t1 2018-01-10 17:27:06 -0500: Joining group `my-group`
t1 2018-01-10 17:27:06 -0500: Joined group `my-group` with member id `test-d72c7eb8-7e48-4fff-8cb1-8152be58c624`
t1 2018-01-10 17:27:06 -0500: Chosen as leader of group `my-group`
t1 2018-01-10 17:27:06 -0500: Partitions assigned for `40edeb182cd479ee-topic-1`: 1, 0
t1 2018-01-10 17:27:06 -0500: Got message: Hello 40edeb182cd479ee-topic-1 partition 1!
t1 2018-01-10 17:27:06 -0500: Committing offsets with recommit: 40edeb182cd479ee-topic-1/1:1
t1 2018-01-10 17:27:06 -0500: Got message: Hello 40edeb182cd479ee-topic-1 partition 0!
t2 2018-01-10 17:27:16 -0500: Starting thread
t2 2018-01-10 17:27:16 -0500: New topics added to target list: 40edeb182cd479ee-topic-2
t2 2018-01-10 17:27:16 -0500: Fetching cluster metadata from kafka://docker.local.host:9092
t2 2018-01-10 17:27:16 -0500: Discovered cluster metadata; nodes: docker.local.host:9093 (node_id=2), docker.local.host:9092 (node_id=1), docker.local.host:9094 (node_id=3)
t2 2018-01-10 17:27:16 -0500: Joining group `my-group`
t1 2018-01-10 17:27:16 -0500: Committing offsets: 40edeb182cd479ee-topic-1/1:1, 40edeb182cd479ee-topic-1/0:1
t1 2018-01-10 17:27:16 -0500: Error sending heartbeat: Kafka::RebalanceInProgress
t1 2018-01-10 17:27:16 -0500: Joining group `my-group`
t2 2018-01-10 17:27:16 -0500: Joined group `my-group` with member id `test-005f13ac-323e-4c17-aba1-cd6a26de570b`
t1 2018-01-10 17:27:16 -0500: Joined group `my-group` with member id `test-d72c7eb8-7e48-4fff-8cb1-8152be58c624`
t1 2018-01-10 17:27:16 -0500: Chosen as leader of group `my-group`
t2 2018-01-10 17:27:16 -0500: Partitions assigned for `40edeb182cd479ee-topic-1`: 1
t2 2018-01-10 17:27:16 -0500: There are no partitions to fetch from, sleeping for 5s
t1 2018-01-10 17:27:16 -0500: Partitions assigned for `40edeb182cd479ee-topic-1`: 0
t2 2018-01-10 17:27:21 -0500: There are no partitions to fetch from, sleeping for 5s
t1 2018-01-10 17:27:26 -0500: Committing offsets: 40edeb182cd479ee-topic-1/0:1
t2 2018-01-10 17:27:26 -0500: There are no partitions to fetch from, sleeping for 5s
t2 2018-01-10 17:27:31 -0500: There are no partitions to fetch from, sleeping for 5s
t2 2018-01-10 17:27:36 -0500: There are no partitions to fetch from, sleeping for 5s
t1 2018-01-10 17:27:36 -0500: Committing offsets: 40edeb182cd479ee-topic-1/0:1
t2 2018-01-10 17:27:41 -0500: There are no partitions to fetch from, sleeping for 5s
t2 2018-01-10 17:27:46 -0500: Leaving group `my-group`
t1 2018-01-10 17:27:46 -0500: Committing offsets: 40edeb182cd479ee-topic-1/0:1
t1 2018-01-10 17:27:46 -0500: Leaving group `my-group`
```
Notice that t2 is assigned partitions on topic `40edeb182cd479ee-topic-1` which it did not subscribe to. It's also not assigned any partitions on topic `40edeb182cd479ee-topic-2` which it did subscribe to.

**Comment by dasch** [comment]
When would you want to consumers in the same group to subscribe to different topics? Doesn't that defeat the entire idea of groups?

**Comment by jturkel** [comment]
I can't think of a good reason for having consumers in the same group that subscribe to different topics. We did it by accident due to a configuration error so I would be fine with ruby-kafka explicitly disallowing this configuration. That said I'm not sure if the official Java Kafka client supports this configuration. The most relevant part of the doc I could find is [this](https://kafka.apache.org/0110/javadoc/index.html?org/apache/kafka/clients/consumer/KafkaConsumer.html):

> Each consumer in a group can dynamically set the list of topics it wants to subscribe to through one of the subscribe APIs. Kafka will deliver each message in the subscribed topics to one process in each consumer group. 

The doc doesn't say anything about partition assignment in that scenario but it seems strange to have a consumer not read messages from an assigned partition.

**Comment by dasch** [comment]
I'm not sure if doing what you're proposing – only subscribing to topics that the consumer specified – solves the actual problem here, which is that you're running two different "versions" in the same group for a prolonged period of time.

**Comment by jturkel** [comment]
Can you elaborate on what you mean by different "versions"? Are you referring to consumers in the same consumer group that are doing different things with the message they receive?

**Comment by dasch** [comment]
@jturkel yup.

**Comment by jturkel** [comment]
It shouldn't be a problem if the two different types of consumers that share a consumer group are listening on a disjoint set of topics. The two different types of consumers are performing different kinds of logic but they're doing it on messages from different topics. I'm still not sure why you'd ever want that setup though :) I guess you could end up in a similar scenario temporarily if you're changing the set of topics a consumer is subscribing to as part of a canary deployment.

**Comment by dasch** [comment]
I'd need a concrete use case in order to support something like that. Closing this for now.

**Comment by jturkel** [comment]
To be clear I'm fine with ruby-kafka not supporting this setup. We got ourselves into by accident and I don't think there's a compelling use case for it. The thing feels problematic was our two different types of listeners were happily running without any errors to indicate there was a problem so we stopped reading from certain topic partitions for an extended period of time (definitely a gap in our monitoring!). At a minimum do you think it makes sense to have ruby-kafka log warnings if it detects this scenario? Alternatively it could just crash the consumer to ensure it gets noticed.

**Comment by dasch** [comment]
The only way I think it could work is if each consumer passed a digest of its own source code when joining the group (in the user data segment) and the chosen leader then verified they were all identical before assigning partitions. But that still seems messy, and I'm not sure how to do it.

**Comment by jturkel** [comment]
Could we detect the problem in `Kafka::Consumer#join_group` since we know the topics that consumer has subscribed to and the partitions assigned by the consumer group leader?

**Comment by dasch** [comment]
I'm not quite sure.

**Comment by bellemare** [comment]
While not a critical issue, this is something that has affected us in our application development.

A very reasonable use-case would be that an application is consuming two topics: Event data and Entity Data. For instance, lets say we are a company that bills our partners on how much traffic we drive to their site. For each unique user we drive there, we record the event as an "Engagements" event. We also need to know who to bill -> where do we mail the bill to? This could be under a topic called "Partners" where we track partners keyed on partner ID. We store entity data like this in its own no-expiry-date topic to make it available to any consumer / service in your organization.

```Engagements Topic: (key = null, value = Engagement(contains PartnerId -> the user clicked on this partner)
Partners Topic: (key = PartnerId, value = PartnerInformation)
```
In this use-case, you would create one kafka consumer on both topics, under the same group id. If you receive a Partner event (any upstream updates / creates / deletes are propagated) then you route it in your business logic to your state store - say it's a simple SQL DB. If you receive an Engagement event, you would join it on your SQL DB to get which merchant it is, and perhaps perform some sort of live-billing tabulation or other business processing.

In this case, you would want to use the same consumerGroupId for a variety of reasons:
1) SSL and SASL identification is done at the Group level with default Kafka ACL permissions. You need to permit access to a Group and a Topic, and having multiple topics means you will need to add multiple permissions.
2) A groupId is supposed to be representative of the group of applications running that code. Adding more isn't categorically bad, but it is confusing as other kafka clients that I am familiar with do not behave in this manner.
3) Our own conventions are actually leading us in that direction anyways. To work around these issues we're basically just making almost-identical-but-not-quite groupIDs to work around the problem. ie:
```
group1: live-billing-app-partners
group2: live-billing-app-engagements
```
Then we can tell from the prefix who that consumer group belongs to. For our non-ruby apps we simply use a singular consumer groupId and can differentiate all offsets across all topics for them. While it can be worked around, it is something that we have found frustrating especially during development time, when our knowledge of how groupIDs work on other kafka clients (librdkafka, Java) didn't port over to ruby-kafka and it took us some non-trivial time in debugging the issue.

**Comment by dasch** [comment]
@bellemare in your example it sounds to me like you'd want _one_ consumer that subscribes to multiple topics, and does different things based on which topic a message came from, e.g.

```ruby
consumer.each_message do |message|
  case message.topic
  when "topic-a" then something
  when "topic-b" then something_else
  end
end
```

I'm not trying to make ruby-kafka align perfectly with the Java library, but rather to create a library that is simpler and more approachable to Ruby devs. Sometimes that means not supporting esoteric use cases.

**Comment by mensfeld** [comment]
@bellemare also worth pointing out, that if you need to somehow make them dependent on one another, you can use manual offset management to achieve that - ruby-kafka supports that.

**Comment by lizcschwartz-gas** [comment]
@dasch I believe that our application has a valid use case for ruby-kafka to support this feature. Our application processes requests from many different hosts. Application sends each request to a different kafka topic based on host it receives request from. Some of the hosts are more important than others, so they get a consumer that listens just on that topic, whereas, some of the hosts share a consumer. The multiple consumers with the same group id subscribe to the various topics according to settings and perform the request. The consumers perform the exact same operation on each request.

**Comment by dasch** [comment]
@lizcschwartz-gas there's nothing prohibiting you from running the same code base with different configurations, e.g.

```ruby
# Topics to consume from:
TOPICS = ENV.fetch("TOPICS").split(",")

# Group id:
GROUP_ID = ENV.fetch("GROUP_ID")

kafka = ...
consumer = kafka.consumer(group_id: GROUP_ID)

TOPICS.each do |topic|
  consumer.subscribe(topic)
end

...
```

Then have _n_ different configurations. This will allow you to monitor these processes separately.

**Comment by lizcschwartz-gas** [comment]
@dasch - Yes, there is currently a way to code around it, but, ideally, it should be the same group id as it is the same code performing the same function. By having separate group ids, another level of design/implementation is added as there will have to be a process that generates/monitors all the various group ids.

**Comment by dasch** [comment]
There's no requirement that group id map directly to code base. If you use e.g. Kubernetes, you can define _n_ different Deployments, each pointing to the same image but with different config.

Basically: this problem is not widespread enough to warrant adding support for it, and especially for maintaining that support and complexity.

**Comment by Adithya-copart** [comment]
@dasch Sorry for the ping. We had to deal with this behavior and wanted to see if you can add any input here as this aligns with this issue.
Please let me know if this needs to be reported as a new issue.

The [documentation](https://github.com/zendesk/ruby-kafka#consumer-groups) for consumer groups says:
> Each consumer process will be assigned one or more partitions from each topic that the group subscribes to. In order to handle more messages, simply start more processes.

So, we have multiple processes that subscribe to different topics using the same `group_id`.
Instead of the partitions being shared between the consumers, the processes crash.

The work-around(?) is using the same 'group_id' for the set of consumers subscribed to a particular topic. Sharing the `group_id` is causing issues as shown below. It would be nice if using the same 'group-id' is allowed so that we need not have a topic specific 'group_id' within an application with consumers to different topics.

```ruby
require 'bundler/inline'
gemfile do
  source 'https://rubygems.org'

  gem 'ruby-kafka'
end

class KafkaConsumers

  def start
    thr = []
    # Each topic here has 10 partitions.
    thr << kafka_consumer('topic_1', 'test')
    thr << kafka_consumer('topic_2', 'test')
    thr.map(&:join)
  end

  private

  def kafka
    @kafka ||= Kafka.new(['broker_1', 'broker_2', 'broker_3'],
      logger: Logger.new(STDOUT)
    )
  end

  def kafka_consumer(topic, group_id)
    Thread.new do
      begin
        consumer = kafka.consumer(group_id: group_id)
        consumer.subscribe(topic)
        trap("TERM") { consumer.stop }
        consumer.each_message do |message|
          # do_something
        end
      rescue => e
        puts "Error #{e}: #{e&.backtrace}"
        # retry
      end
    end
  end

end


KafkaConsumers.new.start

```
When we run this script simultaneously at-least two times, the processes crash instead of the partitions being shared by the consumers as mentioned in the documentation.

**Results:**
```bash
adpentela@MB-ADPENTELA ~/Desktop $ ruby -v
ruby 2.7.0dev (2019-03-25 trunk 67344) [x86_64-darwin17]

Traceback (most recent call last):
  24: from /Users/adpentela/.rvm/gems/ruby-head/gems/ruby-kafka-0.7.7/lib/kafka/fetcher.rb:56:in `block in start'
  23: from /Users/adpentela/.rvm/gems/ruby-head/gems/ruby-kafka-0.7.7/lib/kafka/fetcher.rb:111:in `loop'
  22: from /Users/adpentela/.rvm/gems/ruby-head/gems/ruby-kafka-0.7.7/lib/kafka/fetcher.rb:157:in `step'
  21: from /Users/adpentela/.rvm/gems/ruby-head/gems/ruby-kafka-0.7.7/lib/kafka/fetcher.rb:201:in `fetch_batches'
  20: from /Users/adpentela/.rvm/gems/ruby-head/gems/ruby-kafka-0.7.7/lib/kafka/fetch_operation.rb:71:in `execute'
  19: from /Users/adpentela/.rvm/gems/ruby-head/gems/ruby-kafka-0.7.7/lib/kafka/fetch_operation.rb:71:in `flat_map'
  18: from /Users/adpentela/.rvm/gems/ruby-head/gems/ruby-kafka-0.7.7/lib/kafka/fetch_operation.rb:71:in `each'
  17: from /Users/adpentela/.rvm/gems/ruby-head/gems/ruby-kafka-0.7.7/lib/kafka/fetch_operation.rb:81:in `block in execute'
  16: from /Users/adpentela/.rvm/gems/ruby-head/gems/ruby-kafka-0.7.7/lib/kafka/broker.rb:54:in `fetch_messages'
  15: from /Users/adpentela/.rvm/gems/ruby-head/gems/ruby-kafka-0.7.7/lib/kafka/broker.rb:200:in `send_request'
  14: from /Users/adpentela/.rvm/gems/ruby-head/gems/ruby-kafka-0.7.7/lib/kafka/connection.rb:97:in `send_request'
  13: from /Users/adpentela/.rvm/gems/ruby-head/gems/ruby-kafka-0.7.7/lib/kafka/instrumenter.rb:23:in `instrument'
  12: from /Users/adpentela/.rvm/gems/ruby-head/gems/ruby-kafka-0.7.7/lib/kafka/connection.rb:104:in `block in send_request'
  11: from /Users/adpentela/.rvm/gems/ruby-head/gems/ruby-kafka-0.7.7/lib/kafka/connection.rb:165:in `write_request'
  10: from /Users/adpentela/.rvm/gems/ruby-head/gems/ruby-kafka-0.7.7/lib/kafka/protocol/encoder.rb:178:in `encode_with'
   9: from /Users/adpentela/.rvm/gems/ruby-head/gems/ruby-kafka-0.7.7/lib/kafka/protocol/request_message.rb:22:in `encode'
   8: from /Users/adpentela/.rvm/gems/ruby-head/gems/ruby-kafka-0.7.7/lib/kafka/protocol/fetch_request.rb:55:in `encode'
   7: from /Users/adpentela/.rvm/gems/ruby-head/gems/ruby-kafka-0.7.7/lib/kafka/protocol/encoder.rb:82:in `write_array'
   6: from /Users/adpentela/.rvm/gems/ruby-head/gems/ruby-kafka-0.7.7/lib/kafka/protocol/encoder.rb:82:in `each'
   5: from /Users/adpentela/.rvm/gems/ruby-head/gems/ruby-kafka-0.7.7/lib/kafka/protocol/fetch_request.rb:58:in `block in encode'
   4: from /Users/adpentela/.rvm/gems/ruby-head/gems/ruby-kafka-0.7.7/lib/kafka/protocol/encoder.rb:82:in `write_array'
   3: from /Users/adpentela/.rvm/gems/ruby-head/gems/ruby-kafka-0.7.7/lib/kafka/protocol/encoder.rb:82:in `each'
   2: from /Users/adpentela/.rvm/gems/ruby-head/gems/ruby-kafka-0.7.7/lib/kafka/protocol/fetch_request.rb:64:in `block (2 levels) in encode'
   1: from /Users/adpentela/.rvm/gems/ruby-head/gems/ruby-kafka-0.7.7/lib/kafka/protocol/encoder.rb:57:in `write_int32'
/Users/adpentela/.rvm/gems/ruby-head/gems/ruby-kafka-0.7.7/lib/kafka/protocol/encoder.rb:57:in `pack': no implicit conversion of nil into Integer (TypeError)

adpentela@MB-ADPENTELA ~/Desktop $ ruby -v
jruby 9.2.7.0 (2.5.3) 2019-04-09 8a269e3 Java HotSpot(TM) 64-Bit Server VM 25.191-b12 on 1.8.0_191-b12 +jit [darwin-x86_64]

warning: thread "Ruby-0-Thread-4: /Users/adpentela/.rvm/gems/jruby-9.2.7.0/gems/ruby-kafka-0.7.6/lib/kafka/fetcher.rb:54" terminated with exception (report_on_exception is true):
TypeError: wrong argument type NilClass (expected Integer)
            pack at org/jruby/RubyArray.java:4833
     write_int32 at /Users/adpentela/.rvm/gems/jruby-9.2.7.0/gems/ruby-kafka-0.7.6/lib/kafka/protocol/encoder.rb:57
          encode at /Users/adpentela/.rvm/gems/jruby-9.2.7.0/gems/ruby-kafka-0.7.6/lib/kafka/protocol/fetch_request.rb:64
            each at org/jruby/RubyHash.java:1419
     write_array at /Users/adpentela/.rvm/gems/jruby-9.2.7.0/gems/ruby-kafka-0.7.6/lib/kafka/protocol/encoder.rb:82
          encode at /Users/adpentela/.rvm/gems/jruby-9.2.7.0/gems/ruby-kafka-0.7.6/lib/kafka/protocol/fetch_request.rb:58
            each at org/jruby/RubyHash.java:1419
     write_array at /Users/adpentela/.rvm/gems/jruby-9.2.7.0/gems/ruby-kafka-0.7.6/lib/kafka/protocol/encoder.rb:82
          encode at /Users/adpentela/.rvm/gems/jruby-9.2.7.0/gems/ruby-kafka-0.7.6/lib/kafka/protocol/fetch_request.rb:55
          encode at /Users/adpentela/.rvm/gems/jruby-9.2.7.0/gems/ruby-kafka-0.7.6/lib/kafka/protocol/request_message.rb:22
     encode_with at /Users/adpentela/.rvm/gems/jruby-9.2.7.0/gems/ruby-kafka-0.7.6/lib/kafka/protocol/encoder.rb:178
   write_request at /Users/adpentela/.rvm/gems/jruby-9.2.7.0/gems/ruby-kafka-0.7.6/lib/kafka/connection.rb:165
    send_request at /Users/adpentela/.rvm/gems/jruby-9.2.7.0/gems/ruby-kafka-0.7.6/lib/kafka/connection.rb:104
      instrument at /Users/adpentela/.rvm/gems/jruby-9.2.7.0/gems/ruby-kafka-0.7.6/lib/kafka/instrumenter.rb:23
    send_request at /Users/adpentela/.rvm/gems/jruby-9.2.7.0/gems/ruby-kafka-0.7.6/lib/kafka/connection.rb:97
    send_request at /Users/adpentela/.rvm/gems/jruby-9.2.7.0/gems/ruby-kafka-0.7.6/lib/kafka/broker.rb:188
  fetch_messages at /Users/adpentela/.rvm/gems/jruby-9.2.7.0/gems/ruby-kafka-0.7.6/lib/kafka/broker.rb:54
         execute at /Users/adpentela/.rvm/gems/jruby-9.2.7.0/gems/ruby-kafka-0.7.6/lib/kafka/fetch_operation.rb:81
            each at org/jruby/RubyHash.java:1419
        flat_map at org/jruby/RubyEnumerable.java:880
         execute at /Users/adpentela/.rvm/gems/jruby-9.2.7.0/gems/ruby-kafka-0.7.6/lib/kafka/fetch_operation.rb:71
   fetch_batches at /Users/adpentela/.rvm/gems/jruby-9.2.7.0/gems/ruby-kafka-0.7.6/lib/kafka/fetcher.rb:201
            step at /Users/adpentela/.rvm/gems/jruby-9.2.7.0/gems/ruby-kafka-0.7.6/lib/kafka/fetcher.rb:157
            loop at /Users/adpentela/.rvm/gems/jruby-9.2.7.0/gems/ruby-kafka-0.7.6/lib/kafka/fetcher.rb:111
           start at /Users/adpentela/.rvm/gems/jruby-9.2.7.0/gems/ruby-kafka-0.7.6/lib/kafka/fetcher.rb:56
TypeError: wrong argument type NilClass (expected Integer)
            pack at org/jruby/RubyArray.java:4833
     write_int32 at /Users/adpentela/.rvm/gems/jruby-9.2.7.0/gems/ruby-kafka-0.7.6/lib/kafka/protocol/encoder.rb:57
          encode at /Users/adpentela/.rvm/gems/jruby-9.2.7.0/gems/ruby-kafka-0.7.6/lib/kafka/protocol/fetch_request.rb:64
            each at org/jruby/RubyHash.java:1419
     write_array at /Users/adpentela/.rvm/gems/jruby-9.2.7.0/gems/ruby-kafka-0.7.6/lib/kafka/protocol/encoder.rb:82
          encode at /Users/adpentela/.rvm/gems/jruby-9.2.7.0/gems/ruby-kafka-0.7.6/lib/kafka/protocol/fetch_request.rb:58
            each at org/jruby/RubyHash.java:1419
     write_array at /Users/adpentela/.rvm/gems/jruby-9.2.7.0/gems/ruby-kafka-0.7.6/lib/kafka/protocol/encoder.rb:82
          encode at /Users/adpentela/.rvm/gems/jruby-9.2.7.0/gems/ruby-kafka-0.7.6/lib/kafka/protocol/fetch_request.rb:55
          encode at /Users/adpentela/.rvm/gems/jruby-9.2.7.0/gems/ruby-kafka-0.7.6/lib/kafka/protocol/request_message.rb:22
     encode_with at /Users/adpentela/.rvm/gems/jruby-9.2.7.0/gems/ruby-kafka-0.7.6/lib/kafka/protocol/encoder.rb:178
   write_request at /Users/adpentela/.rvm/gems/jruby-9.2.7.0/gems/ruby-kafka-0.7.6/lib/kafka/connection.rb:165
    send_request at /Users/adpentela/.rvm/gems/jruby-9.2.7.0/gems/ruby-kafka-0.7.6/lib/kafka/connection.rb:104
      instrument at /Users/adpentela/.rvm/gems/jruby-9.2.7.0/gems/ruby-kafka-0.7.6/lib/kafka/instrumenter.rb:23
    send_request at /Users/adpentela/.rvm/gems/jruby-9.2.7.0/gems/ruby-kafka-0.7.6/lib/kafka/connection.rb:97
    send_request at /Users/adpentela/.rvm/gems/jruby-9.2.7.0/gems/ruby-kafka-0.7.6/lib/kafka/broker.rb:188
  fetch_messages at /Users/adpentela/.rvm/gems/jruby-9.2.7.0/gems/ruby-kafka-0.7.6/lib/kafka/broker.rb:54
         execute at /Users/adpentela/.rvm/gems/jruby-9.2.7.0/gems/ruby-kafka-0.7.6/lib/kafka/fetch_operation.rb:81
            each at org/jruby/RubyHash.java:1419
        flat_map at org/jruby/RubyEnumerable.java:880
         execute at /Users/adpentela/.rvm/gems/jruby-9.2.7.0/gems/ruby-kafka-0.7.6/lib/kafka/fetch_operation.rb:71
   fetch_batches at /Users/adpentela/.rvm/gems/jruby-9.2.7.0/gems/ruby-kafka-0.7.6/lib/kafka/fetcher.rb:201
            step at /Users/adpentela/.rvm/gems/jruby-9.2.7.0/gems/ruby-kafka-0.7.6/lib/kafka/fetcher.rb:157
            loop at /Users/adpentela/.rvm/gems/jruby-9.2.7.0/gems/ruby-kafka-0.7.6/lib/kafka/fetcher.rb:111
           start at /Users/adpentela/.rvm/gems/jruby-9.2.7.0/gems/ruby-kafka-0.7.6/lib/kafka/fetcher.rb:56
```
