### ISSUE TITLE
Kafka 1.0 Support

### ISSUE THREAD

**Issue by spectorar** [zendesk/ruby-kafka#532]
I know that it's not listed in the compatibility matrix but I'm curious if there is any known usage of this library with a Kafka 1.0. We wouldn't necessarily need new features but we are upgrading our cluster from 0.8.x and want to take it as far as possible. Is there any known successful usage of the client with Kafka 1.0? Is official support on the roadmap?

**Comment by dasch** [comment]
We run the integration test suite against Kafka 1.0, so things should work as expected. I've updated the matrix to document that.

**Comment by spectorar** [comment]
Thanks!
