### ISSUE TITLE
Kafka streams support?

### ISSUE THREAD

**Issue by mensfeld** [zendesk/ruby-kafka#546]
We are interested in using kafka streaming.
Is it on the road map for zendesk kafka ruby library?

**Comment by mensfeld** [comment]
I guess it would require a separate api BUT do you think it would be suitable to combine it within this library? I could take a look into some concepts but wanted to ask before whether it is (from your perspective) feasible to add it here or to build a ruby-kafka-streams or something.

**Comment by dasch** [comment]
I don't think it belongs in ruby-kafka, at the very least. I also think it's a stretch to build such a thing in Ruby, without quite a few resources. There are a _ton_ of edge cases you'll have to deal with once you get into windows, aggregations, state management, etc. But if you're up to it, :+1:. Note that some of the advanced protocol features that underlie Kafka Streams aren't yet supported by ruby-kafka, and adding support for them would be time consuming. The whole message API was basically rewritten in 0.11.

**Comment by mensfeld** [comment]
> I don't think it belongs in ruby-kafka

Though the same.

>  I also think it's a stretch to build such a thing in Ruby, without quite a few resources.

Not the first time I build something without them ;) Karafka wasn't different at the time (badly working poseidon without consumer groups and many more problems).

> There are a ton of edge cases you'll have to deal with once you get into windows, aggregations, state management, etc.

Rather none unless I encounter them for my own usecases ;)

> Note that some of the advanced protocol features that underlie Kafka Streams aren't yet supported by ruby-kafka

Then at some point we will have to do something about that :)

Anyhow, got my answers. Closing, Thank you.

**Comment by ayqazi** [comment]
@dasch Are the conclusions here still accurate for the latest version of ruby-kafka?

**Comment by dasch** [comment]
Yup. ruby-kafka is a low-level Kafka library, not a high-level framework.

**Comment by ayqazi** [comment]
@dasch Sorry for not being specific, I was actually asking about this statement:

> Note that some of the advanced protocol features that underlie Kafka Streams aren't yet supported by ruby-kafka, and adding support for them would be time consuming.
