### ISSUE TITLE
Getting Connection error EOFError: EOFError

### ISSUE THREAD

**Issue by harsh-a1** [zendesk/ruby-kafka#549]
Hi

We are trying to send data to kafka but are geting the following error:

> Could not connect to any of the seed brokers:
> kafka://192.168.1.24:2181: Connection error EOFError: EOFError

Code : 
  ```
require "kafka"
 kafka = Kafka.new(["192.168.1.24:2181"], client_id: "my-client-id")
    # Case 1:
    kafka.deliver_message("Hello, World!", topic: "cohota")

    # Case 2:
    # Instantiate a new producer.
    producer = kafka.producer
    # Add a message to the producer buffer.
    producer.produce("Hello", topic: "cohota")
    # Deliver the messages to Kafka.
    producer.deliver_messages
```
It is working with a node library on the same machine same network but with ruby its throwing the error....sorry for the noob question but please if someone could give any idea as to what we are doing wrong...thanks

ruby-kafka: 0.5.4
rails (5.0.4)
Bundler version 1.16.1
Ruby version 2.4.1
kafka version : 0.9.0.0 , also checked on 0.10.0.0 & also on 1.0.1

**Comment by mensfeld** [comment]
Hey @harsh-a1, did you try one of the higher level libraries for producing and/or consuming like [karafka](https://github.com/karafka/karafka) or [racecar](https://github.com/zendesk/racecar)? The reason I'm asking is that they contain some validations that would ensure that what you are doing is right. If your node code works, than the ruby code should work as well. Also this port does not look like a standard kafka port (but that may be on purpose)

**Comment by harsh-a1** [comment]
Yes it worked, we were using the wrong port, changing to kafka one did it..thanks
