### ISSUE TITLE
Which limitations will I face when using ruby-kafka with kafka 1.1.0?

### ISSUE THREAD

**Issue by wkechel** [zendesk/ruby-kafka#551]
This is a question, not a bug report.

* Version of Ruby: 2.4.x+
* Version of Kafka: 1.1.0
* Version of ruby-kafka:

**Comment by nguyenquangminh0711** [comment]
Hi @wkechel, the current version of ruby-kafka is developed based on Kafka 0.10.0. The newer versions of Kafka still work thanks to the awesome backward compatibility; however, all the new features after the version 0.10.0 are not available. Some of them are new record batch format, transactions, exactly-one delivery, etc.
