### ISSUE TITLE
Consumer#pause doesn't pause processing fetched messages

### ISSUE THREAD

**Issue by tmattia** [zendesk/ruby-kafka#552]
If this is a bug report, please fill out the following:

* Version of Ruby: 2.4.2
* Version of Kafka: 0.11.0.1
* Version of ruby-kafka: 0.5.4

Please verify that the problem you're seeing hasn't been fixed by the current `master` of ruby-kafka.

###### Steps to reproduce

```ruby
require 'ruby-kafka'
kafka = Kafka.new(seed_brokers: ['kafka://127.0.0.1:9092'])
# Rand is on purpose just to prove, that the same message is being fetched
kafka.deliver_message(rand.to_s, topic: 'a')
kafka.deliver_message(rand.to_s, topic: 'a')
kafka.deliver_message(rand.to_s, topic: 'a')
consumer = kafka.consumer(group_id: 'consumer-name')
consumer.subscribe('a')
consumer.each_message(automatically_mark_as_processed: false) do |message|
  p message
  consumer.pause(message.topic, message.partition, timeout: 5)
end
```

###### Expected outcome

I would expect it process the first message from the topic and immediately stop, not continue processing the messages that were already fetched. When resuming, it should resume from the same offset where it stopped (if on a brand new topic, it would be offset 0).

```
$ bundle exec ruby test.rb
#<Kafka::FetchedMessage:0x007f8d7f109eb0 @message=#<Kafka::Protocol::Message:0x007f8d7f8ba3f8 @key=nil, @value="0.9944667197555783", @codec_id=0, @offset=0, @create_time=2018-03-31 11:41:28 +0200, @bytesize=18>, @topic="b", @partition=0>
(... waiting for pause timeout to expire...)
#<Kafka::FetchedMessage:0x007f8d80a8a9c0 @message=#<Kafka::Protocol::Message:0x007f8d7f110990 @key=nil, @value="0.9944667197555783", @codec_id=0, @offset=0, @create_time=2018-03-31 11:41:28 +0200, @bytesize=18>, @topic="b", @partition=0>
(... waiting for pause timeout to expire...)
#<Kafka::FetchedMessage:0x007f8d7f1225c8 @message=#<Kafka::Protocol::Message:0x007f8d7f1185c8 @key=nil, @value="0.9944667197555783", @codec_id=0, @offset=0, @create_time=2018-03-31 11:41:28 +0200, @bytesize=18>, @topic="b", @partition=0>
(... waiting for pause timeout to expire...)
```

I believe this behavior was introduced by https://github.com/zendesk/ruby-kafka/pull/447

###### Actual outcome

It continues processing fetched messages even if the partition has been paused. It only stops after the current batch of fetched messages has been completely processed.

```
$ bundle exec ruby test.rb
#<Kafka::FetchedMessage:0x007fb176be94a0 @message=#<Kafka::Protocol::Message:0x007fb1762f0880 @key=nil, @value="0.9944667197555783", @codec_id=0, @offset=0, @create_time=2018-03-31 11:41:28 +0200, @bytesize=18>, @topic="b", @partition=0>
#<Kafka::FetchedMessage:0x007fb176be9428 @message=#<Kafka::Protocol::Message:0x007fb1762f0268 @key=nil, @value="0.8218395439620431", @codec_id=0, @offset=1, @create_time=2018-03-31 11:41:28 +0200, @bytesize=18>, @topic="b", @partition=0>
#<Kafka::FetchedMessage:0x007fb176be93b0 @message=#<Kafka::Protocol::Message:0x007fb176bebd68 @key=nil, @value="0.720709962080135", @codec_id=0, @offset=2, @create_time=2018-03-31 11:41:28 +0200, @bytesize=17>, @topic="b", @partition=0>
```

**Comment by benjaminoakes** [comment]
I `git-bisect`ed this and got:

```
b4911aced5b3455b93167ad7952bbffce488d476 is the first bad commit
commit b4911aced5b3455b93167ad7952bbffce488d476
Author: Maciej Mensfeld <maciej@mensfeld.pl>
Date:   Tue Oct 24 21:13:21 2017 +0200

   #441

:040000 040000 16f1e067cbeec465970a4c4107087ee6c55e81b5 68ad166725333e2af62cc0fc818cc4d1496d3468 M      lib
bisect run success
```

This line is of particular interest, as commenting it out _seems_ to give the retry behavior we want: https://github.com/zendesk/ruby-kafka/blob/b4911aced5b3455b93167ad7952bbffce488d476/lib/kafka/consumer.rb#L214

**Comment by dasch** [comment]
So... the intended use case here is this:

```ruby
begin
  consumer.each_message do |msg|
    something(msg)
  end
rescue Kafka::ProcessingError => e
  # An exception was raised by `something`, so let's pause the partition:
  consumer.pause(e.topic, e.partition, timeout: 5)
end
```

Would this pattern not work for you? It's cheaper to only check the pause status of a partition before processing the entire batch rather than before each message.

**Comment by tmattia** [comment]
@dasch unfortunately we're pretty committed to the example code in this issue, it's a simplification of the code we use on our internal library to consume events from kafka. It's quite similar to zendesk's Racecar, but takes care of a few other things like connecting to a schema registry and adds some error handling strategies, including pausing partitions.

I haven't ran performance tests on this so I could be wrong, but just looking at the code it looks like it's more expensive to exit the consumer loop and restart it than it is to check the pause status of a partition before each message.

**Comment by dasch** [comment]
> I haven't ran performance tests on this so I could be wrong, but just looking at the code it looks like it's more expensive to exit the consumer loop and restart it than it is to check the pause status of a partition before each message.

Exceptions should be exceptional, so it's probably better to pay that price seldomly rather than pay a lower price constantly.

**Comment by Vachman** [comment]
@dasch current implementation of `pause` doesn’t make a lot of sense for us too, because every time when we want to pause consumption from topic we need to raise an exception which will break `each_message` which will rebalance assigned partitions to other consumers.

So that means that pausing some topic/partition on `consumer A` will immediately trigger processing of same topic/partition on `consumer B`.

Intention of pausing topic is “not processing it” but currently it behaves as “process on other node”.

About our use case:
We are implementing back preasure mechanism which should ensure that we are not consuming more messages from topic/partition that we can process.

Maybe you can recommend us better way how we can pause topic for our use case.
Thanks.

**Comment by dasch** [comment]
I'll have to take a look at redesigning the pause system. Probably by moving the pause policy into the consumer loop itself rather than having external code rescue exceptions and call `pause`.

**Comment by Vachman** [comment]
Hi @dasch is there any news about this topic?
Thanks.

**Comment by dasch** [comment]
Unfortunately not. I simply don’t have enough time to keep up with the work
here.
