### ISSUE TITLE
Updating a topic's configuration

### ISSUE THREAD

**Issue by raulvc** [zendesk/ruby-kafka#559]
Is it possible to use this lib to alter an existing topic's configuration (like retention and segment size)?

If not, my proposal is to (if at all possible concerning the current kafka API) have a *create_or_update* or a flag allowing configuration to be overridden in *create* (currently fails due to existing topic exception)

**Comment by dasch** [comment]
[Kafka::Client](http://www.rubydoc.info/gems/ruby-kafka/Kafka/Client) has a method for updating the partition count of a topic: `#create_partitions_for`. Other than that, there's currently no support for updating a topic's config. I'd be open to a PR that implements e.g. `#alter_topic` using the [AlterConfigs API](https://kafka.apache.org/protocol#The_Messages_AlterConfigs).

**Comment by nguyenquangminh0711** [comment]
Hi @dasch and @raulvc , I'm in the mid way of that Alter Configs API implementation and hasn't finished yet. It would be ready in some days and I'll open a pull request then.

**Comment by dasch** [comment]
❤️

**Comment by dasch** [comment]
Fixed by #569.
