### ISSUE TITLE
async producer crash

### ISSUE THREAD

**Issue by costa** [zendesk/ruby-kafka#560]
If this is a bug report, please fill out the following:

* Version of Ruby: jruby 9.1.8.0 (2.3.1)
* Version of Kafka: 0.11.0.1 (landoop/fast-data-dev)
* Version of ruby-kafka: 0.5.4

Please verify that the problem you're seeing hasn't been fixed by the current `master` of ruby-kafka.

I'm sorry, I haven't done that.

###### Steps to reproduce

I'm not sure, it just happens in the middle of the server's up time. Will be happy to co-operate if the issue isn't obvious with the stack trace.

###### Expected outcome

All good.

###### Actual outcome
```
NoMethodError: undefined method `partition' for nil:NilClassWarning
/usr/local/bundle/gems/ruby-kafka-0.5.4/lib/kafka/producer.rb:337:in `block in assign_partitions!'
org/jruby/RubyArray.java:1734:in `each'
/usr/local/bundle/gems/ruby-kafka-0.5.4/lib/kafka/pending_message_queue.rb:36:in `each'
/usr/local/bundle/gems/ruby-kafka-0.5.4/lib/kafka/producer.rb:336:in `assign_partitions!'
/usr/local/bundle/gems/ruby-kafka-0.5.4/lib/kafka/producer.rb:297:in `block in deliver_messages_with_retries'
org/jruby/RubyKernel.java:1298:in `loop'
/usr/local/bundle/gems/ruby-kafka-0.5.4/lib/kafka/producer.rb:286:in `deliver_messages_with_retries'
/usr/local/bundle/gems/ruby-kafka-0.5.4/lib/kafka/producer.rb:236:in `block in deliver_messages'
/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/notifications.rb:166:in `instrument'
/usr/local/bundle/gems/ruby-kafka-0.5.4/lib/kafka/instrumenter.rb:19:in `instrument'
/usr/local/bundle/gems/ruby-kafka-0.5.4/lib/kafka/producer.rb:229:in `deliver_messages'
/usr/local/bundle/gems/ruby-kafka-0.5.4/lib/kafka/async_producer.rb:241:in `deliver_messages'
/usr/local/bundle/gems/ruby-kafka-0.5.4/lib/kafka/async_producer.rb:199:in `block in run'
org/jruby/RubyKernel.java:1298:in `loop'
/usr/local/bundle/gems/ruby-kafka-0.5.4/lib/kafka/async_producer.rb:191:in `run'
/usr/local/bundle/gems/ruby-kafka-0.5.4/lib/kafka/async_producer.rb:148:in `block in ensure_threads_running!'
09 Apr 2018 11:57:55.3962018-04-09 08:57:55 UTC severity=ERROR, Async producer crashed!
```

**Comment by dasch** [comment]
I haven't tested ruby-kafka with JRuby – you may be better off using the Java library.

**Comment by costa** [comment]
@dasch Thanks, do you have any leads for that? `jruby-kafka` is dead for some reason, unfortunately.

**Comment by dasch** [comment]
Is there no way to use the JVM library directly from JRuby?

**Comment by costa** [comment]
@dasch there most probably is, it is just not as straightforward as one could hope it to be, i wish someone had time to revive jruby-kafka, it could be extremely useful (i didn't seem to find any other working gems either)

**Comment by film42** [comment]
Just ran into this issue today as well. I also noticed that the perpetually growing until the process ran out of memory. 

![image](https://user-images.githubusercontent.com/1043908/41609114-0be221bc-73b8-11e8-876f-91b73f39db24.png)

This was me printing out:
```
kafka_async_producer.instance_eval { @worker.instance_eval { @producer.buffer_size + @queue.size  } }
```

The max async queue size was set to 1000 at the time.

PS: I'm posting these as notes so we can make ruby-kafka work for jruby as well. I would guess off the top of my head that this is some kind of race condition, but I'll keep doing some digging.

**Comment by mattbooks** [comment]
From the README:

> the asynchronous producer should be safe to use in a multi-threaded environment. 
...
> the asynchronous producer has been designed in such a way to only a single background thread operates on this data while any foreground thread with a reference to the producer object can only send messages to that background thread over a safe queue. Therefore it is safe to share an async producer object between many threads.

However I am not sure that that is true. The code that does that is in `AsyncProducer#ensure_threads_running!`

```ruby
@worker_thread = nil unless @worker_thread && @worker_thread.alive?
@worker_thread ||= Thread.new { @worker.run }
```

however it's not synchronized, and `||=` is not atomic, so if two threads call `produce` and the worker_thread has died or has not started yet, you could end up with more than 1 worker thread and then you can easily hit this issue where messages are cleared in one thread while being consumed in another.
