### ISSUE TITLE
Allow setting a max message size for Producer

### ISSUE THREAD

**Issue by dasch** [zendesk/ruby-kafka#567]
* Avoid situations where a message is rejected by the broker and stuck in a buffer.
* Make sure not to create too large message batches.

**Comment by nguyenquangminh0711** [comment]
I used to got this error in production. My solution is to fetch `max.message.bytes` via `client#describe_topic` and reject new messages if a message size exceeds this threshold or the whole batch exceed this threshold. This method would be more accurate than using the user setting because there could be a mismatch between user settings and actual configuration in Kafka clusters, especially when this configuration could be broker-scoped or topic-scoped.

**Comment by dasch** [comment]
Good point.

**Comment by jrpilat** [comment]
It's worth noting here that, as of 0.11.0.0, Kafka brokers apply their `max.message.bytes` limitation config to batches of messages, and not just individual messages within a batch, so the functionality here would need to make sure that the batches being sent don't exceed in bytes what the user specified (or what you retrieve via `client#describe_topic`, if that's the way you're going about it.

**Comment by jwilger** [comment]
Out of curiosity, is anyone actively working on this already? We seem to be running into this same issue, and I agree that basing the limit off of the broker setting would be ideal (with a modification to https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/async_producer.rb#L255 to trigger delivery when approaching that threshold, perhaps?) I'd be willing to take a stab at it if no one else is already attempting to address this; I just want to avoid duplicating efforts.

**Comment by nguyenquangminh0711** [comment]
Hi @jwilger, it's on my personal list to implement in ruby-kafka. But I haven't touched it yet. So, we are happy that you can go ahead and implement that feature ❤️. 

There are some notes about this feature:
- The batch messeage byte can be fetched via `Client#describe_topic`, but that's topic's scope, and each topic can have their own variable. 
- The limit is record batch size, that's different from the total size of messages in the queue. There are some overhead in each batch. 
- In case an individual message exceeds topic's limit. It should be elimiated before adding to the queue, to prevent forever stuck.

**Comment by ramunas-peleckas** [comment]
Any updates on this?

**Comment by dasch** [comment]
Feel free to take a stab – last time I looked at it, the error applied to the whole batch, so finding the specific message(s) that caused the error isn't straightforward. Maybe remove the largest message and then retry?

This behavior needs to be opt-in for the sync producer, though, as it violates delivery guarantees. The async can set the behavior by default, since there aren't any hard delivery guarantees there.

**Comment by marvin-bitterlich** [comment]
To loop back on this issue, can confirm that this issue still exists
