### ISSUE TITLE
Roadmap 0.11 support

### ISSUE THREAD

**Issue by klippx** [zendesk/ruby-kafka#572]
At our company we have started the upgrade to Kafka 0.11 in our clusters, and in the future (soon?) they want to bump the message format as well.

I think it would be nice to hear your plans for supporting 0.11 (and eventually even 1.0). I have a suggestion: would it not be cool to create projects 0.11 and 1.0? I am talking about https://github.com/zendesk/ruby-kafka/projects 
- We get a structure
- We can list what needs to be done
- We can set goals for releases, let's make an example that "in 0.7.0 we want to go for full 0.11 support" and "in 1.0.0 we want to go for full kafka 1.0 support"
- People interested in this gem could get an overview and join the discussion
- In some cases being able to contribute is easier with a good project/structure

Let's say this happens, and that we have v0.7.0.beta branches, then we would be interested/willing to help test stuff out and most likely even contribute with code if needed. It would be easier and more reassuring than just going cowboy and hoping 0.11 will eventually/probably be supported at some point in time.

@nguyenquangminh0711 has already started with PR #548 which means we are off to a great start, but there is also the transactions feature for producers, I am sure there are more stuff needed. But there is currently no transparency when and if this will be merged, and what release it is planned to be cut into.

Interested in your thoughts @dasch - And to all you watchers, WDYT?

**Comment by dasch** [comment]
Good idea – I'll create projects for 0.11 and 1.0. Note, however, that fully supporting 0.11 would take a very big effort. You can use ruby-kafka with Kafka 0.11 even if it doesn't support the on-disk format, it just means that the brokers have to translate back to the 0.10 format on the fly.

**Comment by thijsc** [comment]
Do let me know if hijacking this conversation is not ok, but: I've been working on a new wrapper gem around librdkafka. It has support for all the new 1.0 stuff. I'd love to get some feedback on it from everybody here.

https://github.com/appsignal/rdkafka-ruby

**Comment by dasch** [comment]
:+1:

I'd be very interested in rdkafka-ruby if you can get it battle tested. Maintaining the network API and protocol code is a lot of work, and quite error prone.

**Comment by thijsc** [comment]
That was my thinking exactly. The amount of effort and attention to detail that goes into librdkafka is huge, it is extremely challenging to get to that level on a part-time basis.

We are currently using this gem in production at AppSignal with significant traffic already. Also some other companies use it. I plan to get to feature completeness the coming weeks, you can follow that here: https://github.com/appsignal/rdkafka-ruby/milestone/1

**Comment by thijsc** [comment]
By default it will use the C lib's partitioner on the key. You can override that manually by providing a partition when producing. `librdkafka` also has an option to provide a custom partitioner, haven't worked on that since we don't have that use case ourselves. How do you partition?

I've already spent quite a bit of time on making sure the API docs are nice. Any feedback or contributions are appreciated.

**Comment by dasch** [comment]
A typical use case is producing messages to a compacted topic where the key is significant. If you e.g. want to always write a set of related keys to the same partition, the partitioner cannot simply look at the key – you need to be able to specify that some messages belong on the same partition. Specifying the partition directly requires the producer to know ahead of time the number of partitions in the topic, which is wrong in my opinion (as you may want to change the partition count without changing your application code). A custom partitioner would work, but is a bit low-level.

The partition key concept can be implemented with a custom partitioner, though, e.g. by having the client pass a partition key (different from the message key), then `digest(partition_key) modulo num_partitions`.
