### ISSUE TITLE
Support Transaction API

### ISSUE THREAD

**Issue by dasch** [zendesk/ruby-kafka#573]
https://www.confluent.io/blog/transactions-apache-kafka/

**Comment by nguyenquangminh0711** [comment]
This is the most informative and well-maintained document about transactions in Kakfa. Hope this would help: https://docs.google.com/document/d/11Jqy_GjUGtdXJK94XGsEIK7CP1SnQGdp2eF0wSw9ra8/edit#heading=h.7mkuz62dyql

**Comment by nguyenquangminh0711** [comment]
The support for transactional production is already merged into production. So, this issue can be closed now.
