### ISSUE TITLE
Interruptible consumer loop

### ISSUE THREAD

**Issue by kirs** [zendesk/ruby-kafka#578]
Consider this example:

```ruby
require "kafka"

kafka = Kafka.new(
  seed_brokers: ENV.fetch("KAFKA_BROKERS"),
  logger: Logger.new($stderr),
)

consumer = kafka.consumer(group_id: "myconsumer")
consumer.subscribe("insights", start_from_beginning: false)

started_at = Time.now
kafka.each_message(topic: "mytopic") do |message|
  break if Time.now > started_at + 60 # seconds
  puts message.value
end
```

In the example, I want to yield over `each_message` but for no longer than 60 seconds. The issue is that while there are no messages in the Kafka topic, the block to `each_message` would never be called. When the topic is empty, `each_message` would run forever, polling for messages in the topic.

For the context, I want `each_message` / `each_batch` to run for no longer than N seconds because it's called from a unit of work that has a fixed run time limit.

`max_wait_time` or `min_bytes` would not help here because they control how long the client polls for events inside the loop, but not for how long the loop runs.

## Proposed solution

Would contributors be open to accept a PR that would add an argument to `each_message` / `each_batch` to indicate when we want to stop polling for new events in the log?

It could look like this:

```ruby
started_at = Time.now
kafka.each_message(topic: "mytopic", exit_if: -> { Time.now > started_at + 60  }) do |message|
  puts message.value
end
```

**Comment by kirs** [comment]
@dasch looking forward for your opinion :blush:

**Comment by dasch** [comment]
I think #369 provides a way to implement these kinds of scenarios without encumbering `each_*`.

**Comment by kirs** [comment]
Thanks, I had no idea about #369.
