### ISSUE TITLE
Partition's Offsets Changes Depending on Consumer Host??

### ISSUE THREAD

**Issue by bradurani** [zendesk/ruby-kafka#581]
* Version of Ruby: 2.5.0
* Version of Kafka: 1.0.0
* Version of ruby-kafka: 0.5.4

Shot in the dark here, every time I restart my consumers the offsets for each partition jump up and down:

<img width="617" alt="screen shot 2018-05-05 at 11 06 07 am" src="https://user-images.githubusercontent.com/4195952/39666644-c146f3e6-505b-11e8-8c16-03835aa9b58c.png">

I'm actually committing the offsets this time, unlike the last time I opened an issue 😃. the weird thing is, there's a symmetry to the offset jumps. An offset for a given partition will jump up or down, then when I restart, go back to where it was. Turns out, this is related to which consumer host consumes that partition! I have 4 hosts, and run a consumer app in a Docker container on each host. If graph lag by `consumer_id`, `partition` and `hostname`, you can see that the lines are straight:
<img width="1062" alt="screen shot 2018-05-05 at 11 05 38 am" src="https://user-images.githubusercontent.com/4195952/39666669-52b8d916-505c-11e8-8da1-104bc69ce863.png">

Any idea why the offset would change depending on the consumer host????

**Comment by dasch** [comment]
The consumer lag is the difference between the offset currently being processed and the "highwater mark" of the partition, i.e. the last offset in the partition. As such, it changes not only in response to messages being processed, but also to messages being produced to the end of the partition. As such, it's not always easy to understand what's going on.

I've started graphing the changes to the current offset per topic/partition (`derivative` of `ruby_kafka.consumer.offset`) – under normal operations, this number should be positive, but when a consumer group "jumps back" in a partition, it shows as the line getting negative on the graph.

There are a number of cases where this might happen, e.g. if the group needs to re-sync but a member hasn't committed its offsets in a while – it actually won't be allowed to until after the re-sync, in which case it's likely that a different member of the group will be assigned the partition, resuming from the last checkpoint, which will be farther back in the partition.

However, there may be other reasons why this happens, and some of them may be bugs in ruby-kafka. If you can, please see if you can correlate these phenomena with other events and report here.

**Comment by bradurani** [comment]
This hasn't occurred recently, I think we misdiagnosed this.
