### ISSUE TITLE
Handling delivery errors with AsyncProducer?

### ISSUE THREAD

**Issue by awseward** [zendesk/ruby-kafka#588]
Based on https://github.com/zendesk/ruby-kafka#buffering-and-error-handling, it seems that if you wanted to log to an error reporting service, you could rescue `Kafka::DeliveryFailed` and do so there.

This is great for a synchronous producer, but how about when using an async producer? I poked around and didn't see any kind of error hook that could give a chance to get access to delivery errors.

I noticed that a `sync_producer` could be passed into `AsyncProducer`, and was hopeful that I could just pass in my own synchronous producer that would do the error reporting then reraise. However, since `Client#async_producer` doesn't take one and instead creates its own, that won't really work:
https://github.com/zendesk/ruby-kafka/blob/1e621d0a3512ccb9fe2878bad72525ed1e2aca35/lib/kafka/client.rb#L253-L255

I'm curious if I could get your thoughts on the best way to go about this.

Thanks in advance! 😄

**Comment by mensfeld** [comment]
The passing of a producer to the async would be indeed a good idea. We would benefit from it as well.

**Comment by dasch** [comment]
Is the current level of instrumentation not enough? What do you need an exception for?

**Comment by dasch** [comment]
Delivery errors are not exceptional, unfortunately.

**Comment by mensfeld** [comment]
@dasch I would appreciate that to build up a failvoer and persistence layers.

**Comment by dasch** [comment]
In that case, I would very much appreciate it if you started out by building your own async producer based on a sync producer. The current async producer is _not_ designed with failover and persistence in mind, and I don't think I want to add those concerns. But if you read the code, it's actually not that complicated. Maybe a future based async producer?

**Comment by film42** [comment]
I think https://github.com/zendesk/ruby-kafka/pull/603 might solve your problem. You can now subscribe to async producer errors and forward them to your logging service.

**Comment by nguyenquangminh0711** [comment]
The instrumenter for async producers is now available in stable releases. I'll close this issue now. Please feel free to re-open it in case you have further questions. The documents will be fulfilled soon.
