### ISSUE TITLE
Avro Support ?

### ISSUE THREAD

**Issue by omartell** [zendesk/ruby-kafka#59]
Just wondering if you have any plans to add `Avro` support and have an `AvroProducer` and `AvroConsumer` that integrate with the `SchemaRegistry`. 

I'd be happy to help with the implementation if needed.

**Comment by dasch** [comment]
I don't think this would be the place to do it, but creating a wrapper around this library should be rather simple. I'm trying to avoid putting any serialization concerns into ruby-kafka.

By the way, [AvroTurf](https://github.com/dasch/avro_turf) (written by yours truly) already offers integration with the Schema Registry. Using it with ruby-kafka should be pretty easy:

```ruby
# You need to pass the URL of your Schema Registry.
avro = AvroTurf::Messaging.new(registry_url: "http://my-registry:8081/")

# Encoding data has the side effect of registering the schema. This only
# happens the first time a schema is used.
data = avro.encode({ "title" => "hello, world" }, schema_name: "greeting")

# Now it's going into Kafka!
producer.produce(data, topic: "greetings")
```

**Comment by omartell** [comment]
Oh nice, will take a look at that, :+1:

**Comment by OpakAlex** [comment]
@dasch do you known how todo it with protobufs?))

**Comment by dasch** [comment]
I don't have a ready example, buy you basically need to encode your protobuf data to a string and pass it as the `data` argument.
