### ISSUE TITLE
Producing messages when one broker is down

### ISSUE THREAD

**Issue by mmustala** [zendesk/ruby-kafka#605]
Hi,

We recently had one of our brokers down because of a bug with the cached zkVersion. During that time our producer was not able to produce messages (at least to some partitions). Started to think should we use `required_acks: 1` to avoid similar issues in the future? Or should the producer be smart enough to realize that one broker is down and not waiting for ack from all replicas?

This also happened when one of our brokers went down due to out of memory.

If the downed broker was the leader of the partition, I think there is nothing we can do except wait for a new leader to be elected.

**Comment by mmustala** [comment]
We hadn't set that to anything, so it was at the default value.

The error message we received was:
```
Kafka::DeliveryFailed: Failed to send messages to topic-name/206
File "/var/app/current/vendor/bundle/ruby/2.3.0/gems/ruby-kafka-0.6.3/lib/kafka/producer.rb" line 330 in deliver_messages_with_retries
File "/var/app/current/vendor/bundle/ruby/2.3.0/gems/ruby-kafka-0.6.3/lib/kafka/producer.rb" line 238 in block in deliver_messages
File "/var/app/current/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.4/lib/active_support/notifications.rb" line 168 in instrument
File "/var/app/current/vendor/bundle/ruby/2.3.0/gems/ruby-kafka-0.6.3/lib/kafka/instrumenter.rb" line 21 in instrument
File "/var/app/current/vendor/bundle/ruby/2.3.0/gems/ruby-kafka-0.6.3/lib/kafka/producer.rb" line 231 in deliver_messages
```

**Comment by dasch** [comment]
Ah, you're using the synchronous producer? In that case, you need to implement your own retries. I suggest using the async producer unless you really need synchronous behavior.

**Comment by mmustala** [comment]
Yeah, we need synchronous because the order of our messages is very important. So, doesn't synchronous producer handle this scenario where one broker is down?

**Comment by dasch** [comment]
Not directly – it flags its cluster info as stale, so the next attempt will re-fetch it (including new leadership info). But you may need to back off a bit and allow the cluster to recover first. So, rescue the exception, then sleep a bit, then try again.

The async producer does this automatically.

**Comment by mmustala** [comment]
We were receiving those errors for an hour. So it really seem to require the full cluster to be healthy in order to produce, at least to those partitions that have one of its replicas on the broker that is down. I suppose. I just had an impression that using Kafka is much more error tolerant. I would have assumed that the cluster recognizes that one of us is down, let's cope with the rest of the servers, elect new leader for some partitions and resume operations.

But to be honest, I don't know what responsibility is on the producer and what on the cluster.

We do create a new producer each time we produce messages, so I think it should get new info from the cluster regarding which broker is the leader for each partition.

**Comment by dasch** [comment]
It's on the cluster to replicate messages – you may want to set e.g. `required_acks: 2` if you're okay with just 2 replicas.

BTW, you may want to keep the producer around instead of creating a new one each time. It's not very performant.

**Comment by mmustala** [comment]
Our topics have replication factor 2, so I think we would need to use `required_acks: 1`.
