### ISSUE TITLE
Cluster metadata not refreshed after a topic has been reassigned

### ISSUE THREAD

**Issue by ttamimi** [zendesk/ruby-kafka#610]
We were using `Kafka::Client#each_message` to consume from `__consumer_offsets` in order to report consumer lag. When we migrated the topic to a new set of brokers (as part of an upgrade), our script stopped receiving new offsets due to `Kafka::UnknownTopicOrPartition`. The script kept retrying and kept receiving the same error, because the cluster metadata is never refreshed in that situation.

The fix is simple: https://github.com/zendesk/ruby-kafka/pull/609/files

**Comment by dasch** [comment]
Fixed by #609.
