### ISSUE TITLE
Consumer Retry Bug

### ISSUE THREAD

**Issue by bradurani** [zendesk/ruby-kafka#617]
* Version of Ruby: 2.5.0
* Version of Kafka:
* Version of ruby-kafka: 0.6.6

```
consumer.each_batch(automatically_mark_as_processed: false) do
   # error is raised here sending message to external service
   consumer.mark_message_as_processed(batch.messages.last) # never reached
   consumer.commit_offsets # never reached
rescue
   # report error
end
```
In this scenario, the offset advances with every batch. It never retries messages that were not processed due to errors until you restart the consumers and they pick up at the last committed offset.
I was surprised by this behavior because I thought it would retry at the same offset until a message is marked as processed.

Thanks!

**Comment by dasch** [comment]
Yeah, that sounds like a gem. If you have time, it would be great if you could look into it.

**Comment by dasch** [comment]
Wait – are you using the new `do ... rescue ... end` syntax? That's not supported by ruby-kafka – it expects to handle exceptions raised by the loop on its own.

**Comment by bradurani** [comment]
This turned out to be expected behavior. Thanks for looking at it!
