### ISSUE TITLE
Use a thread for sending heartbeats

### ISSUE THREAD

**Issue by dorner** [zendesk/ruby-kafka#618]
This is to track a functionality change whereby instead of sending heartbeats inline with message processing, they are sent via a separate thread.

This introduces the `poll_timeout` configuration variable, which will force the consumer to time out if it is reached and a new message has not been received within that time.

PR is imminent!

**Comment by theturtle32** [comment]
Yeah, the existing inline behavior has bitten us in the ass many, many, many times! I'll be very grateful to see this moved to a thread. I'm glad you're already working on this, as I was thinking of taking a stab at a PR myself.

**Comment by dorner** [comment]
@theturtle32 Well, not sure when I'll be able to get around to rewriting it entirely :) If you're willing to take a stab, please do!
