### ISSUE TITLE
Slow CRC32C checksum

### ISSUE THREAD

**Issue by nguyenquangminh0711** [zendesk/ruby-kafka#620]
* Version of Kafka: 0.11.0
* Version of ruby-kafka: 0.7.x beta

In ruby-kafka from version 0.7.x beta, we makes use of the gem digest-crc to support new checksum mechanism for Kafka record batch format. However, in the gem, all the implementation is in pure ruby (https://github.com/postmodern/digest-crc/blob/master/lib/digest/crc32.rb#L110). That leads to the huge amount of time spent in the checksum operation, both while producing or consuming. The total fragment could take up to 25% to 50% total time. This is the main reason why the new 0.7.x branch is nearly 50% slower than the current stable version.

![screen shot 2018-07-27 at 13 47 15](https://user-images.githubusercontent.com/11613517/43306245-b12234b4-91a4-11e8-86f4-a1dc9c95cbca.png)
![screen shot 2018-07-27 at 13 47 35](https://user-images.githubusercontent.com/11613517/43306247-b15720ac-91a4-11e8-8dc3-e81791f6e18b.png)

To improve this slowness, I think we should move the CRC32C checksum calculation to a C extension, directly in this gem. This would increase the complexity of the gem bundling progress. So I want to know whether it is worth to solve, or just accept this slowness? 

cc @dasch

**Comment by dasch** [comment]
I'd rather the C extension be done in the CRC gem so that it can benefit everyone.

**Comment by emschwar** [comment]
I believe zlib, which is part of  the standard library, has a CRC implementation in C:

https://ruby-doc.org/stdlib-2.5.1/libdoc/zlib/rdoc/Zlib.html#method-c-crc32

I can make a PR if you're still interested.

**Comment by dasch** [comment]
That would be great!

**Comment by nguyenquangminh0711** [comment]
I had a double-check, it looks like the Zlib's crc32 method is still CRC32. We are looking for CRC32C checksum instead.

**Comment by mperham** [comment]
```ruby
require 'zlib'
Zlib.crc32(string)
```

**Comment by postmodern** [comment]
@emschwar let's move any digest-crc development talk over to postmodern/digest-crc#13. There's a lot of hidden work here that I want to fully digest...

**Comment by postmodern** [comment]
One question about this profiling data. What was the average size and repetition of the messages being sent/received which `Digest::CRC32C` had to digest? I'm writing benchmarks for all of the `Digest::CRC` classes and want to use a realistic message size and/or repetition count.

**Comment by klippx** [comment]
> To improve this slowness, I think we should move the CRC32C checksum calculation to a C extension, directly in this gem. This would increase the complexity of the gem bundling progress. So I want to know whether it is worth to solve, or just accept this slowness?

@nguyenquangminh0711 Maybe we can accept the slowness by default, I am not sure exactly how slow it is. Instead a solution could be to make the ruby-kafka CRC32C checksum pluggable. So, in case user want to have a solution that invloves a gem with native C extension, he can set that explicitly in his own Gemfile and plug that into ruby-kafka adapter in whatever way. Could be via yml config, could be a new ruby-kafka-crc32c-native gem that if present ruby-kafka will automatically use it.

Then you can link to this gem from this repo readme, and in the new gem readme explain how it is installed and just about how much performance gain there would be for regular users. Maybe even steps on how to find out.

**Comment by dasch** [comment]
Yeah, definitely not something I want to do. Users should have to jump through hoops to have this be performant.

**Comment by postmodern** [comment]
Finally got some OSS time and took a stab at writing C extensions for the majority of the algorithms. Note, these are _optional_ C extensions, meaning that if the C extensions cannot be compiled it will skip them and only load the extensions if present. This means that users without a C compiler, or without ruby-dev/ruby-devel packages installed, or even JRuby users will continue using the pure Ruby code. Preliminary benchmarks show a ~90% performance increase on MRI with the C extensions loaded. Will want to get extra eyes on this significant and clever (see the discussion) enhancement before releasing a 0.6.0 or 0.7.0 release.

* Commit: https://github.com/postmodern/digest-crc/commit/b8e724e32d1bc99d07b850af2c5ba6d302341ec7
* Discussion and Benchmarks: https://github.com/postmodern/digest-crc/issues/13#issuecomment-595087605

**Comment by postmodern** [comment]
[digest-crc 0.6.0.rc1](https://github.com/postmodern/digest-crc/blob/0.6.0/ChangeLog.md#060--2020-06-16) has been released with the optional C extensions, which boosts performance under CRuby by ~40x. If the C extensions fail to compile for whatever reason (no compiler, no ruby-dev, JRuby, etc), digest-crc will fall back to the pure-Ruby implementation. Please test away.

    gem install digest-crc -v 0.6.0.rc1

**Comment by postmodern** [comment]
digest-crc 0.6.0 is out! bundle update digest-crc should improve performance on CRuby, when C extensions can be compiled; assuming a compiler is installed and ruby headers are present (if ruby was installed from apt/dnf, ruby-dev/ruby-devel packages must be installed).

**Comment by dasch** [comment]
Do we need a change to the ruby-kafka dependency or will the update take care of itself?
