### ISSUE TITLE
max_queue_size seems to be incorrect by about half

### ISSUE THREAD

**Issue by jgeiger** [zendesk/ruby-kafka#631]
If this is a bug report, please fill out the following:

* Version of Ruby: 2.4.4
* Version of Kafka: 1.0.1
* Version of ruby-kafka: 0.6.7

Please verify that the problem you're seeing hasn't been fixed by the current `master` of ruby-kafka.

###### Steps to reproduce

Not perfect code, but is a similar setup to what is failing.

```ruby
producer = Kafka.new().async_producer(max_queue_size: 5000)
(1..4000).each { |i| producer.produce({a:"b-#{i}"}.to_json, topic: "topic", parition_key:i % 10) }
```

###### Expected outcome
It enqueues all 4000 messages without crashing.

###### Actual outcome
```
irb(main):002:0> (1..4000).each { |i| producer.produce({a:"b-#{i}"}.to_json, topic: "topic", parition_key:i % 10) }

Kafka::BufferOverflow: Cannot produce to topic, max queue size (5000 messages) reached
        from app/services/app/metrics/producer.rb:6:in `produce'
        from (irb):2:in `block in irb_binding'
        from (irb):2
```
It seems like for every message you enqueue, it doubles it. If I use 2500, it works. 2501 fails.

**Comment by nguyenquangminh0711** [comment]
@jgeiger I could not reproduce the bug from your example code. I have to change a little bit to make 
it works:

```ruby
producer = Kafka.new(seed_brokers: ['localhost:9092']).async_producer(max_queue_size: 5000)
(1..5001).each { |i| producer.produce({a:"b-#{i}"}.to_json, topic: "topic", parition_key:i % 10); producer.deliver_messages }
```

It's true that the `max_queue_size` is not respected 100%, but not significant in most cases. The async producer runs in other threads. They share a common command queue with the main thread. Whenever you call `producer.producer(...)` or `producer.deliver_messages`, etc. It pushes those commands into this common queue. Unfortunately, the max queue size is checked based on this command queue. So, unless you manually trigger `deliver_messages` too many times, or the `delivery_interval` option is too small; it is unlikely this issue happens. The fix would take some efforts to re-write the communications between threads. Therefore, if this is not a big issue to you, I think we won't touch this in near future.

**Comment by jgeiger** [comment]
Thanks. It is an issue to the point where we can't use the async producer because we fill up the queue and it never sends within the correct intervals. We're stuck using the sync producer and calling deliver after every call because we can't afford to deal with the exceptions.

I'll see if I can come up with a better example that clearly shows the issue, but not  in the very near future. Thank you for your help. I'll create a new issue once I get the time to create the example.
