### ISSUE TITLE
Consumer do not honor offset with different deliver implementation

### ISSUE THREAD

**Issue by pascalmail** [zendesk/ruby-kafka#635]
* Version of Ruby: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin17]
* Version of Kafka: 1.1.0
* Version of ruby-kafka: 0.7.0

###### Steps to reproduce

```ruby
require 'kafka'

brokers = ['127.0.0.1:9092']
topic = 'xyz'
group_id = 'SSD'

def deliver1(producer, topic)
  (1..4).each do |i|
    puts "deliver1 produce #{i}"
    producer.produce("msg#{i}", topic: topic)
    producer.deliver_messages
 end
end

def deliver2(producer, topic)
  (1..4).each do |i|
    puts "deliver2 produce #{i}"
    producer.produce("msg#{i}", topic: topic)
 end
 producer.deliver_messages
end

client = Kafka.new(brokers)
client.delete_topic(topic) rescue nil

producer = client.producer

# different deliver implementation will change the output
deliver1(producer, topic)
# deliver2(producer, topic)

consumer = client.consumer(group_id: group_id)
consumer.subscribe(topic)

counter = 0
consumer.each_message(automatically_mark_as_processed: false) do |msg|
   puts "Offset :#{msg.offset} - Value:#{msg.value}\n"
   consumer.mark_message_as_processed(msg)
   consumer.commit_offsets
   counter += 1
   consumer.stop if counter == 3
end

puts 'New consumer'
consumer2 = client.consumer(group_id: group_id)
consumer2.subscribe(topic)

trap('TERM') { consumer2.stop }

consumer2.each_message do |msg|
  puts "Offset :#{msg.offset} - Value:#{msg.value}\n"
end
```

###### Expected outcome
Running the script while using `deliver2` created confusing behaviour, it is as if the `consumer2` do not honour the offset checkpointed by `consumer`

Output using `deliver1`
```
deliver1 produce 1
deliver1 produce 2
deliver1 produce 3
deliver1 produce 4
Offset :0 - Value:msg1
Offset :1 - Value:msg2
Offset :2 - Value:msg3
New consumer
Offset :3 - Value:msg4
```

Output using `deliver2`
```
deliver2 produce 1
deliver2 produce 2
deliver2 produce 3
deliver2 produce 4
Offset :0 - Value:msg1
Offset :1 - Value:msg2
Offset :2 - Value:msg3
New consumer
Offset :0 - Value:msg1
Offset :1 - Value:msg2
Offset :2 - Value:msg3
Offset :3 - Value:msg4
```

**Comment by nguyenquangminh0711** [comment]
@pascalmail I investigated the situation. It is true that there is a bug in the fetcher. Internally, there are some differences between two implementations.
- In the first scenario, there are 4 new record batches (internal message batching presentations). Each time you commit the offsets, the commitment is **at the end** of the record batch.  
- In the second scenario, there is just 1 new record batches. When you commit the offsets, they are **in the middle** of the record batch. 

When the clients send the requests to Kafka to fetch the records, say topic Hello, partition 0, from offset 3, it is expected that Kafka would return the records from offset 3 only. Surprisingly, it also returns **all the records** in the same record batch. The client doesn't handle this case for now and causes the processing duplication.

I'm working on the bug fix and hope that would be done and released in the next day. 

Thanks for you report. Really nice bug reproduction by the way 👍.
