### ISSUE TITLE
Consumer fails with kafka 1.1.1

### ISSUE THREAD

**Issue by Jakanapes** [zendesk/ruby-kafka#646]
If this is a bug report, please fill out the following:

* Version of Ruby:  2.4.4
* Version of Kafka:  1.1.1
* Version of ruby-kafka:  0.7.1

Please verify that the problem you're seeing hasn't been fixed by the current `master` of ruby-kafka.

###### Steps to reproduce

```ruby
kafka = Kafka.new [URL], client_id: 'console_test'

consumer = kafka.consumer(group_id: "myconsumer")

consumer.subscribe("dpx", start_from_beginning: false)

consumer.each_message do |message|
   puts message.offset
end
```

###### Expected outcome

message offsets would be output

###### Actual outcome

NoMethodError: undefined method `headers' for #<Kafka::Protocol::Message:0x00007fac38a08c50>
from /Users/patricksharp/.gem/ruby/2.4.4/gems/ruby-kafka-0.7.1/lib/kafka/fetched_message.rb:39:in `headers'

**Comment by Jakanapes** [comment]
I was able to bump it down 0.6.7 and it worked, but having an up to date version would be great.  Meanwhile, I'm pushing for a kafka upgrade, but that's a harder ask due to dependencies in other projects.  Thanks!

**Comment by Jakanapes** [comment]
👍   It works!

**Comment by nguyenquangminh0711** [comment]
@Jakanapes The patch is merged into master and will be available in the next release. Please watch the release page to use in your project. I'll close this issue now. Feel free to re-open it in case you have other question.
