### ISSUE TITLE
Unbalanced Consumer Assignment with Unbalanced Topics

### ISSUE THREAD

**Issue by psycotica0-shopify** [zendesk/ruby-kafka#647]
This is mostly a question to make sure I'm understanding the code.

I was looking at the [RoundRobinAssignmentStrategy](https://github.com/zendesk/ruby-kafka/blob/cc52504bc2b8dc59dbccbebc1e0e64a7c1aaeda8/lib/kafka/round_robin_assignment_strategy.rb#L20-L50) and it _looks_ like it's slicing at the partition level.

So if I have 3 topics, the first has 4 partitions, and the other two each have 1, and I have 3 consumers, I think it'll assign as follows:

| Consumer | Assignment |
| - | - |
| consumer0 | `t0p0, t1p0, t2p0, t0p3` |
| consumer1 | `t0p1` |
| consumer2 | `t0p2` |

Which doesn't _feel_ right.
It's Round Robin-y from the perspective of a single topic, but not overall.

It also limits such a group's scalability to highest number of partitions.
In theory there are 6 partitions here that _could_ be assigned, but I can't scale higher than 4 consumers because it always gives 3 of them to the first consumer.

Am I way off?

**Comment by nguyenquangminh0711** [comment]
@psycotica0-shopify In real life environment, like production, this barely happens. If the number of partitions increases, like 10 partitions per topic, the imbalances between consumers fade out. And IMO, that's way better in term of partition consuming distribution. The rule of thumb is that number of partitions should be greater than number of consumers, for each topic.

**Comment by Elyahou** [comment]
@nguyenquangminh0711 

In the case of
- 3 topics with 20 partitions each
- 1 consumer group with 60 members

If I understand it correctly, the current algorithm will assign 3 partitions (1 for each topic) to 20 members, and the 40 remaining will be without any assignment

Maybe we can enhance this by evenly distribute to members, and in that case assign 1 partition for each member

**Comment by nguyenquangminh0711** [comment]
@Elyahou Yes, that's true that the current round-robin strategy doesn't work well in that case. It's not hard to fix this issue. I'm just curious about your concrete use case. In your described configuration, do all 3 topics have the same schema and meanings? In most of my use cases, I usually split into 3 different consumer groups, each consumer group consumes from a topic:
- Group 1 (20 members) consumes from topic 1 (20 partitions)
- Group 2 (20 members) consumes from topic 2 (20 partitions)
- Group 3 (20 members) consumes from topic 3 (20 partitions)

The reason for this is that the topic schemas and meanings are different from each other. At beginning, they may share the same processing logics, but they will diverse quickly. Splitting into 3 consumer group helps me to isolate them, prevent logic mess in future. Another important reason is that the traffic from these topics are usually different. I can perform the scaling independently and predictable, either consumer number or partition number, depending on the metrics from the monitoring. Mixing them together is hard to observe and control the scaling as we need.

Of course, this is from my own use cases and experience. Is this approach a good fit for you?

**Comment by nguyenquangminh0711** [comment]
This issue is done in https://github.com/zendesk/ruby-kafka/pull/681. It would be in the next minor release. I'll close this issue. Please feel free to re-open it.
