### ISSUE TITLE
Add `GroupLoadInProgress` to known error codes

### ISSUE THREAD

**Issue by AWaselnuk** [zendesk/ruby-kafka#663]
The stacktrace in a bug report I was looking into resolved to `Kafka::UnknownError: unknown error with code 14` and pointed to [this line](https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/protocol.rb#L151) in the kafka protocol library.

Browsing the Kafka guide, it seems as though code 14 is a legitimate error code that has to do with offset fetch requests. [See `GroupLoadInProgressCode` here](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-PossibleErrorCodes:.5)

If I understand correctly, improving this error message might be as simple as adding a mapping to the known error codes in the `protocol` file.

**Comment by nguyenquangminh0711** [comment]
Yes, that's true. Currently, we are adding the errors that we are handling explicitly in the source code. The others are unknown. But I'm thinking of mapping all the existing errors on Kafka to make it cleaner. Perhaps the PR will be available in some days.

**Comment by nguyenquangminh0711** [comment]
@AWaselnuk The PR is merged into master with a longer list of errors. The GroupLoadInProgress is renamed to CoordinatorLoadInProgress in newer version of kafka. So, I'll use that name.
