### ISSUE TITLE
Connection error while fetching messages: Connection error EOFError: EOFError

### ISSUE THREAD

**Issue by loda507** [zendesk/ruby-kafka#673]
* Version of Ruby: 2.4.2
* Version of Kafka: 0.10.0.1
* Version of ruby-kafka:  0.6.8

I am trying to use ruby-kafka consumer

###### Steps to reproduce

```ruby
kafka = Kafka.new(...)
consumer = kafka.consumer(group_id: "group_test")
consumer.subscribe("test")
consumer.each_message do |message|
  puts message.topic, message.partition
  puts message.offset, message.key, message.value
end
```
###### I am getting error

```ruby
I, [2018-10-29T11:31:45.259635 #13478]  INFO -- : Fetching cluster metadata from kafka://173.17.190.235:9092
D, [2018-10-29T11:31:45.259680 #13478] DEBUG -- : Opening connection to 173.17.190.235:9092 with client id ruby-kafka...
E, [2018-10-29T11:31:47.246783 #13478] ERROR -- : Connection error while fetching messages: Connection error EOFError: EOFError
E, [2018-10-29T11:31:47.246997 #13478] ERROR -- : Connection error while fetching messages: Connection error EOFError: EOFError
D, [2018-10-29T11:31:47.247085 #13478] DEBUG -- : No batches to process
E, [2018-10-29T11:31:47.261637 #13478] ERROR -- : Timed out while trying to connect to 173.17.190.235:9092: Connection timed out
D, [2018-10-29T11:31:47.261705 #13478] DEBUG -- : Closing socket to 173.17.190.235:9092
E, [2018-10-29T11:31:47.261782 #13478] ERROR -- : Failed to fetch metadata from kafka://173.17.190.235:9092: Connection timed out
I, [2018-10-29T11:31:47.261813 #13478]  INFO -- : Fetching cluster metadata from kafka://172.17.190.236:9092
D, [2018-10-29T11:31:47.261878 #13478] DEBUG -- : Opening connection to 172.17.190.236:9092 with client id ruby-kafka...
D, [2018-10-29T11:31:47.262268 #13478] DEBUG -- : Sending topic_metadata API request 1 to 172.17.190.236:9092
D, [2018-10-29T11:31:47.262397 #13478] DEBUG -- : Waiting for response 1 from 172.17.190.236:9092
D, [2018-10-29T11:31:47.263189 #13478] DEBUG -- : Received response 1 from 172.17.190.236:9092
```
It is ok to get topics use kafka.topics
Does anyone know what's the problem?

**Comment by loda507** [comment]
> Ruby-Kafka does not support Kafka 0.10.
it seems like  Ruby-Kafka v0.5.x or v0.6.x  support  Kafka 0.10  according to the Compatibility Description 
![image](https://user-images.githubusercontent.com/19513868/47638809-a1280080-db9a-11e8-87bd-85dcff10e58b.png)

is there something wrong? 
which client should I use with 0.10.0.1

**Comment by mensfeld** [comment]
Sorry, it seems, that the initial version of the message didn't include ruby-kafka version, so I assumed the most recent one:

![zrzut ekranu z 2018-10-29 10-00-37](https://user-images.githubusercontent.com/392754/47639423-85543880-db61-11e8-93ed-f7eb28ae766f.png)

**Comment by loda507** [comment]
sorry, ruby-kafka version  is  0.6.8
![image](https://user-images.githubusercontent.com/19513868/47639646-cddd1780-db9c-11e8-9a53-f15a034e2e0c.png)
and I have tried 0.5.4,  Throw the same error

**Comment by nguyenquangminh0711** [comment]
@loda507 Hi, in your issue, I noticed that the first connecting attempt to `kafka://173.17.190.235:9092` fails, then the second attempt to `kafka://173.17.190.236:9092` succeeded. So, is the functionality works like you expected?

**Comment by loda507** [comment]
@nguyenquangminh0711 
What I expected was both kafka://173.17.190.235:9092  and kafka://173.17.190.236:9092  can be connected，should not rails Connection error
But fetching messages always raise Connection error, can not consume any message

**Comment by nguyenquangminh0711** [comment]
@loda507 In that case, could you try the consumers in other language? Or use kafka command line to test the your first broker at `kafka://173.17.190.235:9092`? If two brokers have the same configuration, and the client can connect to the second one, I'm thinking that the problems comes from other sources, like the first broker doesn't respond anymore, network policy, or even there is an obsolete process is binding to opening port (I used got this error), etc.
