### ISSUE TITLE
Support Request: `buffer_overflow': Cannot produce to measurements, max queue size (1000 messages) reached (Kafka::BufferOverflow)

### ISSUE THREAD

**Issue by SebastianStehle** [zendesk/ruby-kafka#685]
Hi,

I try to understand the problem. We get a lot of exceptions like this in our error log:

```
/bundle/gems/ruby-kafka-0.7.3/lib/kafka/async_producer.rb:166:in `buffer_overflow': Cannot produce to measurements, max queue size (1000 messages) reached (Kafka::BufferOverflow
Kafka::BufferOverflow (Cannot produce to measurements, max queue size (1000 messages) reached)
```

We have increased the buffer size:

```
  $kafka_producer = kafka.async_producer(
    # Max msg count for kafka queue
    max_buffer_size: 5_000,
      
    # Trigger a delivery once 100 messages have been buffered.
    delivery_threshold: 100,

    # Trigger a delivery every 30 seconds.
    delivery_interval: 4,
  )
```
but it still shows the old warning. We send a few messages per second to kafka, so the amount should not be a problem. It starts to happen after some time, as if the queue is never cleared. The message size is only 100-200 bytes.

This is how we produce the messages:

    $kafka_producer.produce(content.to_json, topic: "measurements", partition_key: self.id)

**Comment by nguyenquangminh0711** [comment]
Hi @SebastianStehle, does this happen constently or just on production only? Could you try to create a code snippet that re-produce thi issue in local environment? And can you increase the log level and bring the logs here to see what happens before the queue is filled?

**Comment by SebastianStehle** [comment]
I think I found the issue. There was another part of the code where we used `partition` instead of `partition_key` and therefore the events could not be sent to kafka and flooded the queue. At least this is my theory.

**Comment by nguyenquangminh0711** [comment]
Hi @SebastianStehle, how's it going with this bug? Is your theory true?

**Comment by SebastianStehle** [comment]
Yes, don't know, but it works since I fixed it ;)

**Comment by nguyenquangminh0711** [comment]
So, I'll close this one. Please feel free to re-open it.
