### ISSUE TITLE
Fetcher stopped at startup (racing condition?)

### ISSUE THREAD

**Issue by PChambino** [zendesk/ruby-kafka#688]
If this is a bug report, please fill out the following:

* Version of Ruby: 2.5.3
* Version of Kafka: 1.1.1
* Version of ruby-kafka: 0.7.3

Please verify that the problem you're seeing hasn't been fixed by the current `master` of ruby-kafka.

###### Steps to reproduce

This is a racing condition, so hard to reproduce. `Fetcher` will set `@running = true` after creating the thread which means if the thread runs before `@running` is set, then the thread exits.

Line: https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/fetcher.rb#L60

###### Expected outcome

Fetcher thread should run until we stop the consumer.

###### Actual outcome

Fetcher thread exited at startup which means the consumer was up but not actually reading any messages.

**Comment by mensfeld** [comment]
May be related to the #686

**Comment by PChambino** [comment]
I don't think so. There was no error in our case, we can see the fetcher thread stopping just after a restart.

**Comment by nguyenquangminh0711** [comment]
@PChambino I confirm this bug happens because of the race condition. There is a pull request that fixes this issue. I already merge it. So, please feel free to re-open it. Thanks for reporting ❤️
