### ISSUE TITLE
individual exceptions for connect timeouts / socket wait timeouts

### ISSUE THREAD

**Issue by mrkamel** [zendesk/ruby-kafka#69]
Hi again,

question:

when i fetch messages, i regularly get a "connection timed out" after 10 seconds filling up my logfile. Increasing `max_wait_time` doesn't help because it's the connect/socket timeouts firing.
Sure, i could increase these timeout values, but when i plug off power from my kafka node, my client will timeout later than i'd like it to. So, what i'd really want is to know whether the timeout occurred while connecting/sending the fetch messages request to kafka or while waiting for messages. However, currently it seems i get a `Errno::ETIMEDOUT` for all cases. Maybe it's possible to subclass `Errno::ETIMEDOUT` for the individual cases of ConnectTimeout, ReadTimeout, WriteTimeout?

**Comment by dasch** [comment]
The socket timeouts do need to be longer than the max wait time, otherwise your connections will be killed. Do you experience hangs when you kill your broker? Typically the error happens instantly as the connection fails.

**Comment by mrkamel** [comment]
hm, maybe you misunderstood, this is a feature request. sure, if i kill -9 my broker manually, the client will recognize instantly, but when a real outage occurs, e.g. due to a power failure, it will not. thus, i don't want to increase timeouts, because i want my consumer to fail fast for server outages. instead i want to know if the timeout occurred while connecting/writing/requesting to kafka or while reading from kafka (i.e. while waiting messages).

use case:

```ruby
loop do
  begin
     messages = kafka.fetch_messages(...)
  rescue Kafka::ConnectTimeout, Kafka::WriteTimeout, StandardError
     # write error to logfile or even notify

     retry
  rescue Kafka::ReadTimeout
    # this a very frequent/regular exception, do nothing

    retry
  end
end
```

Without individual exceptions: a) my log/notification system would be way to verbose OR b) i'd have to decide to simply don't log/notify, but then i will not know about potential issues. I simply want to get to know when something goes wrong, but a timeout while waiting for messages is nothing that i consider "wrong".
Hope that clarifies it a bit.

**Comment by dasch** [comment]
If the max wait timeout occurs, you'll simply get back an empty batch of messages - no exception will be raised.

**Comment by mrkamel** [comment]
The socket timeout raises a ConnectionError

**Comment by mrkamel** [comment]
let's skip this for now, lowering max_wait_time below the socket timeout will probably be fine.

**Comment by mrkamel** [comment]
but imho it would be sane default to set max_wait_time somewhat lower than socket time, currently it's 10 seconds, same as socket timeout. and i experienced: sometimes the socket timeout fires, sometimes max_wait_time

**Comment by dasch** [comment]
That's a good idea - I'm thinking about changing the API a bit, as it doesn't make much sense to have the same defaults for a producer as for a consumer. Note that the fetch API is also subject to change.

**Comment by dasch** [comment]
I've though about re-thinking the socket timeout as an extra value that is added to the server side timeout for a given operation (with that being zero for ops with no server side timeout). Otherwise the user must set the socket timeout to be longer than the longest server side timeout, so e.g. metadata operations are allowed too much time. On the other hand there's a complexity cost here. I'm still not quite decided.
