### ISSUE TITLE
Invalid magic byte: 2 when updating kafka client protocol to 0.11

### ISSUE THREAD

**Issue by Kwisatx** [zendesk/ruby-kafka#696]
* Version of Ruby: 2.5.1
* Version of Kafka: 1.0.2
* Version of ruby-kafka: 0.7.4

We updated to ruby-kafka 0.7.4 recently to allow us to upgrade the kafka client protocol to 0.11 (we had been running in 0.10 for a while).

When we updated the client protocol, however, we encountered crashes on one of our partitions with: `Kafka::Error: Invalid magic byte: 2` [magic_byte_crash.txt](https://github.com/zendesk/ruby-kafka/files/2648317/magic_byte_crash.txt)

After adding some debug logs, we were able to determine that we had a magic byte equal to 1 in the message set at [fetch_response.rb](https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/protocol/fetch_response.rb#L96), but that we were getting a magic byte equal to 2 in one of the messages of the message set at [message.rb](https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/protocol/message.rb#L77) (in our case the fifth message of the set).

What's particularly strange is that according to [the protocol](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-Messagesets) records don't even have the magic byte like messages in the previous versions, but I suppose we might have ended up reading a byte by chance that decoded to 2.

We had to drop the kafka packet to keep treating data, and have not encountered the problem since.

Has anyone encountered something similar? Do you think this is just an issue that occurred while switching protocols that we hopefully won't see again?

Thanks!
Jeremy

**Comment by nguyenquangminh0711** [comment]
@Kwisatx Hi, I used to encounter that issue before, when upgrading from message set format to record batch format. And the same as you, I have to drop some batches (like ~5 or something), then nothing weird happens again. I fetched the raw format of record and could not decode it myself (I'm the one who implemented the record batch format btw). At that time I was assuming that there are some message corruption during the transition. If you can share the raw package, I'll be able to re-investigate again to see what happened.

**Comment by Kwisatx** [comment]
Hi!

Thanks for the information, we'll consider the problem a one-time issue with the upgrade then (and reopen the issue if it reappears).
Sadly we did not save the packet in question but in a few weeks we'll be doing the upgrade in a different environment, so if the problem reappears we'll make sure to save the new example and share it with you.
