### ISSUE TITLE
Test Failures on Master / Ruby 2.5.3, Ubuntu 18.10

### ISSUE THREAD

**Issue by jwilger** [zendesk/ruby-kafka#702]
* Version of Ruby: 2.5.3 (and 2.6.0)
* Version of Kafka: ?
* Version of ruby-kafka: master branch as of f07764f86589c4a020586dc8a3f78a3232538c27

###### Steps to reproduce
1. check out the master branch
2. run bin/setup
3. run rake spec

###### Expected outcome

Tests should all pass.

###### Actual outcome

```
Failures:

  1) Kafka::SSLSocketWithTimeout.open times out if the server doesn't accept the connection within the timeout
     Failure/Error:
       expect {
         Kafka::SSLSocketWithTimeout.new(host, port, connect_timeout: timeout, timeout: 1, ssl_context: OpenSSL::SSL::SSLContext.new)
       }.to raise_exception(Errno::ETIMEDOUT)
     
       expected Errno::ETIMEDOUT, got #<Errno::ENETUNREACH: Network is unreachable - connect(2) for 172.16.0.0:4444> with backtrace:
         # ./lib/kafka/ssl_socket_with_timeout.rb:52:in `rescue in initialize'
         # ./lib/kafka/ssl_socket_with_timeout.rb:35:in `initialize'
         # ./spec/ssl_socket_with_timeout_spec.rb:14:in `new'
         # ./spec/ssl_socket_with_timeout_spec.rb:14:in `block (3 levels) in <top (required)>'
         # ./spec/ssl_socket_with_timeout_spec.rb:13:in `block (2 levels) in <top (required)>'
     # ./spec/ssl_socket_with_timeout_spec.rb:13:in `block (2 levels) in <top (required)>'

  2) Kafka::SocketWithTimeout.open times out if the server doesn't accept the connection within the timeout
     Failure/Error:
       expect {
         Kafka::SocketWithTimeout.new(host, port, connect_timeout: timeout, timeout: 1)
       }.to raise_exception(Errno::ETIMEDOUT)
     
       expected Errno::ETIMEDOUT, got #<Errno::ENETUNREACH: Network is unreachable - connect(2) for 172.16.0.0:4444> with backtrace:
         # ./lib/kafka/socket_with_timeout.rb:49:in `rescue in initialize'
         # ./lib/kafka/socket_with_timeout.rb:32:in `initialize'
         # ./spec/socket_with_timeout_spec.rb:14:in `new'
         # ./spec/socket_with_timeout_spec.rb:14:in `block (3 levels) in <top (required)>'
         # ./spec/socket_with_timeout_spec.rb:13:in `block (2 levels) in <top (required)>'
     # ./spec/socket_with_timeout_spec.rb:13:in `block (2 levels) in <top (required)>'

Finished in 1.39 seconds (files took 0.16865 seconds to load)
276 examples, 2 failures

Failed examples:

rspec ./spec/ssl_socket_with_timeout_spec.rb:4 # Kafka::SSLSocketWithTimeout.open times out if the server doesn't accept the connection within the timeout
rspec ./spec/socket_with_timeout_spec.rb:4 # Kafka::SocketWithTimeout.open times out if the server doesn't accept the connection within the timeout

Randomized with seed 18785
```

I could naively just update the spec to accept either class of exception, but I'm not quite sure that's right, since the exception that is coming back isn't really a timeout, but it's what you get from the system network stack on (at least this version of) Linux when trying to hit an non-routable network address. I'm not sure what would need to be done to mimic a network timeout short of stubbing call to the underlying library; maybe that's the right answer here?

Happy to submit a PR, just looking for some direction on what you would consider the appropriate way to handle this.

**Comment by dasch** [comment]
Hmm, I remember this host specifically being something you can connect to but that would time out (since no-one is waiting for connections). Not sure what changed.

**Comment by dasch** [comment]
Maybe change the spec to actually set up a socket in a background thread that `SSLSocketWithTimeout` can try to connect to?

**Comment by jwilger** [comment]
> Hmm, I remember this host specifically being something you can connect to but that would time out (since no-one is waiting for connections). Not sure what changed.

Yeah, and I still get that behavior in our own internal CI that runs tests for our fork of this project. I think maybe it has something to do with the specific version of the underlying network libraries on the host system (I'm getting the failure on a fully-up-to-date Ubuntu 18.10 machine.)

> Maybe change the spec to actually set up a socket in a background thread that `SSLSocketWithTimeout` can try to connect to?

I'm not sure how to do that in a way that would result in the timeout being raised. From my little experimentation in irb, it seems that once you create the server end of the socket, if the client end will (in the absence of some other error) connect at the networking level even if you never write any code to respond to the client.

It seems like the only way to reliably test the behavior of this code on newer/different networking libraries might be to stub out the call to `IO.select` in the spec, so that it returns false. I don't love that, since it leaks a pretty big implementation detail into the spec, but it would at least force the behavior that you are otherwise trying to test. :-/

**Comment by dasch** [comment]
I guess an alternative is to remove the spec – this behavior is pretty stable, and the spec isn't providing a lot of value anymore.

**Comment by jwilger** [comment]
I just ran across this project, which might be useful here: https://github.com/Shopify/toxiproxy
