### ISSUE TITLE
Internal sync producer in the AsyncProducer will always keep failed messages in it

### ISSUE THREAD

**Issue by gilibelz2** [zendesk/ruby-kafka#703]
* Version of Ruby: 2.4.2
* Version of Kafka: 2.0
* Version of ruby-kafka: 0.7.5

Please verify that the problem you're seeing hasn't been fixed by the current `master` of ruby-kafka.

###### Steps to reproduce

We are using the AsyncProducer to send messages to Kafka, we noticed on some cases where a certain message will fail to send, the internal sync producer will keep it in the buffer and will retry sending it when the Time class sends a deliver_messages event. In our case, the message will always fail to send and will be forever stuck in the buffer along with all the messages for the same topic and partition.

###### Expected outcome

The buffer should be cleaned from failed messages.

###### Actual outcome

Failed messages are stuck in the buffer along with all the messages for the same topic and partition.

**Comment by dasch** [comment]
This is a known limitation of the current design. Not sure what e.g. the JVM producer does in this case. Maybe a max number of retries?

**Comment by gilibelz2** [comment]
We've checked about java KafkaProducer and it seems that the message is
taking out from the queue after all retries are exhausted.

**Comment by dasch** [comment]
I think an optional `max_retries` parameter to `produce` would make sense, with the default being infinite retries (`nil`), but then we'd need to keep track of the remaining retries for each message.

PR is welcome :)

**Comment by gilibelz2** [comment]
I think that the two cases should be in different PRs:

1. Empty the internal `sync_producer`  buffer from messages that failed to send to Kafka (i.e.,  `Kafka::CorruptMessage`) and will always be failed.
2. Add an optional `max_retries` and `retry_backoff` to the `async_producer` and limit the number of retries in the `produce` method in the `async_producer` - in a separate issue and PR :)

**Comment by dasch** [comment]
Should be fixed in most recent beta.
