### ISSUE TITLE
OpenSSL::SSL::SSLError with "unknown protocol"

### ISSUE THREAD

**Issue by ifyouseewendy** [zendesk/ruby-kafka#704]
If this is a bug report, please fill out the following:

* Version of Ruby: 2.4.4 (should be any)
* Version of Kafka: ?
* Version of ruby-kafka: 0.7.5

###### Error details

Sorry that I cannot follow the issue template as the error is not really reproducible. It's a rare error happening on our production every once a while. It crashes our consumer and gets recovered later. Right now, I'd love to consider it as a retriable exception, but I'd love to write it down and wait for more voices on it.

The error happens when `producer.deliver_messages` and here is the full error message

```rb
OpenSSL::SSL::SSLError
SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: unknown protocol
```

By looking to the code base, I believe the exception is rescued and re-raised here https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/ssl_socket_with_timeout.rb#L139 which is brought into the code base almost three years ago in https://github.com/zendesk/ruby-kafka/pull/116. I'm really curious about the code here

```rb
module Kafka
  class SSLSocketWithTimeout
    def write(bytes)
      loop do
        written = 0
        begin
          written += @ssl_socket.write_nonblock(bytes)
        rescue Errno::EFAULT => error
          raise error
        rescue OpenSSL::SSL::SSLError, Errno::EAGAIN, Errno::EWOULDBLOCK, IO::WaitWritable => error
          # Why do we filter and retry on this error message? 
          if error.is_a?(OpenSSL::SSL::SSLError) && error.message == 'write would block'
            if select_with_timeout(@ssl_socket, :write)
              retry
            else
              raise Errno::ETIMEDOUT
            end
          else
            raise error
          end
        end
  ..
```

Thanks

**Comment by thanhj** [comment]
I have the same problem on ruby-kafka v0.4.3.

@ifyouseewendy,
Have you solved the issue yet?
