### ISSUE TITLE
Support OAuthBearer Authentication

### ISSUE THREAD

**Issue by psycotica0-shopify** [zendesk/ruby-kafka#705]
With [KIP-255 OAuth Authentication via SASL/OAUTHBEARER](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=75968876), Kafka now supports OAuth tokens as a method of authentication.

For us to use it on the brokers requires the library to support it, so I'm creating this issue here in case someone beats us to it (or it's already done somewhere I haven't found)

**Comment by pt2pham** [comment]
I am currently working on adding OAuthBearer support!
