### ISSUE TITLE
fetch_messages doesn't  refresh metadata / doesn't add target topic

### ISSUE THREAD

**Issue by mrkamel** [zendesk/ruby-kafka#71]
and thus under certain cases thinks a topic doesn't exist, because it operates on incomplete memoized cluster info. See:

```ruby
irb> kafka = Kafka.new(...)
irb> producer = kafka.get_producer

irb> kafka.fetch_messages :topic => "my-topic", :partition => 0, :offset => 0
=> [#<Kafka::FetchedMessage:...>, #<Kafka::FetchedMessage:...>, ...]

# so far so good, let's produce a message

irb> producer.produce "message", :topic => "other-topic"
irb> producer.send_messages

# now fetching no longer works:

irb> kafka.fetch_messages :topic => "my-topic", :partition => 0, :offset => 0
Kafka::UnknownTopicOrPartition: no topic "my-topic"
	from .../lib/kafka/protocol/metadata_response.rb:99:in `find_leader_id'
	from .../lib/kafka/broker_pool.rb:87:in `get_leader_id'
	from .../lib/kafka/broker_pool.rb:66:in `get_leader'
	from .../lib/kafka/fetch_operation.rb:46:in `block (2 levels) in execute'
	from .../lib/kafka/fetch_operation.rb:45:in `each'
        ....
```

FetchOperation#execute should IMHO call `@broker_pool.add_target_topics(target_topics)` to refresh topic metadata like a producer does

**Comment by dasch** [comment]
I agree that `add_target_topics` should be called – I'll add a fix for that. However, the `fetch_messages` API is intentionally low-level and shouldn't make any assumptions about e.g. retries, so if you expect fetching from a non-existing topic to work, you'll have to be prepared to handle a range of exceptions (at the very least Kafka::LeaderNotAvailable) and back off until the cluster has had time to propagate the new topic and elect a leader for the partitions. In the high level consumer API that's on the roadmap such matters will be taken care of automatically, but for the simple `fetch_messages` API the user needs to stay in control of such things.

**Comment by mrkamel** [comment]
sure, that's totally fine.
