### ISSUE TITLE
Plan to support transactional producer?

### ISSUE THREAD

**Issue by linyaoli** [zendesk/ruby-kafka#713]
Hi, is there a plan to invoke the transactional producer from `ruby-kafka`?

**Comment by nguyenquangminh0711** [comment]
Hi @linyaoli, the feature already exists in the source code of ruby-kafka, but not documented in README yet. Sorry about that, I'm current busy as hell 😓. You can view the tests for the usage. I'll try to deliver the documentations soon.

**Comment by linyaoli** [comment]
@nguyenquangminh0711 Got it, thanks for the update!
