### ISSUE TITLE
Number of fetched messages lower than last_offset_for

### ISSUE THREAD

**Issue by RD-Mobile-Admin** [zendesk/ruby-kafka#715]
RUBY VERSION: 2.5.3 (2018-10-18 patchlevel 105) [x86_64-linux]
ruby-kafka (0.7.6)
kafka: confluentinc/cp-kafka:5.0.0-2

> vals = k.last_offsets_for(topic)[topic]
> vals.each do |p,c|
> puts %(Count: #{c} - Size: #{k.fetch_messages(topic:topic, partition:p, offset:0).size})
> end

Count: 187 - Size: 111
Count: 186 - Size: 128
Count: 235 - Size: 157
Count: 220 - Size: 125

What is truly mind boggling is this:
2.5.3 :021 > k.last_offset_for topic,0
 => 179
2.5.3 :022 > k.fetch_messages(topic:topic, partition:0, offset:165).size
 => 13
2.5.3 :023 > k.fetch_messages(topic:topic, partition:0, offset:164).size
 => 1
2.5.3 :024 > k.fetch_messages(topic:topic, partition:0, offset:160).size
 => 5

If i create a consumer that goes through all messages from the offset 0, it returns all of them, but with fetch_messages it has some road blocks where the number of fetched messages goes from the offset to some magic numbers in the partition.

Update:
It looks like the solution is to fetch multiple times from max_fetched_messages_offset + 1 until you reach last_offset_for and concatenate the results, though I'd like to know why this is the case.

**Comment by RD-Mobile-Admin** [comment]
We're using cp-kafka:5.0.0-2 from confluent which would translate to 2.0.0

**Comment by dasch** [comment]
`fetch_messages` does not promise to return _all_ the messages, since that would be an unbounded data set.

**Comment by dasch** [comment]
I would suggest using a real consumer.
