### ISSUE TITLE
0.7.6 tagging breaks logging when passing a hash to a logger (instead of a string)

### ISSUE THREAD

**Issue by entropywtf** [zendesk/ruby-kafka#719]
* Version of Ruby: ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin17]
* Version of Kafka: confluentinc/cp-kafka:5.0.0
* Version of ruby-kafka: 0.7.6

###### Steps to reproduce
Small background story: in our application we use LogStashLogger to log kafka events and to take care of the rest application logs. Therefore we distinguish who is who by the attribute we called :logtype (which can be either :applog or :eventlog), which is then used as an index in elastic search.
```ruby
irb(main):005:0> Rails.logger.formatter
=> #<LogStashLogger::Formatter::JsonLines:0x00007f9999ea2420 @customize_event=nil, @datetime_format=nil>
irb(main):005:0> Rails.logger.info({logtype: :eventlog, msg: 'event produced'}) => true
```
In my config/application.rb I have a small customization which speaks for itself:
```ruby
LogStashLogger.configure do |config|
  config.customize_event do |event|
    event[:logtype] ||= :applog
  end
end
```
When :eventlog events were no more landing in elastic search, I found out, that logger event (from the code above) is now wrongly formatted. Logs were not lost, but they all were getting a wrong index :applog :
Instead of:
```ruby
[1] pry(Manager::Application)> event
=> #<LogStash::Event:0x00007f89bf7f1480
 @cancelled=false,
 @data=
  {:logtype=>:eventlog,
   :msg=>'event produced',
   "@timestamp"=>"2019-03-29T11:09:18.183+01:00",
   "@version"=>"1",
   "severity"=>"INFO",
   "host"=>"shire"}>
```
it was:
```ruby
[1] pry(Manager::Application)> event
=> #<LogStash::Event:0x00007fdd98117b50
 @cancelled=false,
 @data=
  {"message"=>
    "{:logtype=>:eventlog, :msg=>'\event produced\',
   "@timestamp"=>"2019-03-29T11:07:13.510+01:00",
   "@version"=>"1",
   "severity"=>"INFO",
   "host"=>"shire"}>
```

###### Expected outcome

If I pass a hash to a log, I get an original hash from event.instance_variable_get('@data').

###### Actual outcome

Console outcome above.

Kafka::TaggedFormatter#call overrides the LogStashLogger::Formatter::Base#call with
(interpolating hash into a string), which the original formatter cannot handle, which means for now I've downgraded ruby-kafka version back to 0.7.5 and hope this issue will be fixed in the next release (otherwise 🐵 patching).

    def call(severity, timestamp, progname, msg)
      super(severity, timestamp, progname, "#{tags_text}#{msg}")
    end

Thank you in advance! 🤘

**Comment by dasch** [comment]
@dorner I believe https://github.com/zendesk/ruby-kafka/pull/697 introduced this issue – would you be able to help out here?

**Comment by dorner** [comment]
@dasch see my comments in #716 - we can back out the original PR for now and try another way to get this in.
