### ISSUE TITLE
timestamp_delta & create_time

### ISSUE THREAD

**Issue by RD-Mobile-Admin** [zendesk/ruby-kafka#721]
* Version of Ruby: 2.5.3
* Version of Kafka: 
* Version of ruby-kafka: 0.7.6

Some messages in a topic have, for some reason, create time that is well into the future. While digging into this issue, I've noticed there seems to be a correlation between that and the timestamp_delta.
In short, 'good' messages have a timestamp_delta==0, while the messages from the future have a timestamp_delta that appears to be equal to the number of seconds in the future.
Fetching the timestamps with kafka-console-consumer returns timestamps as expected.

Any thoughts on why this difference between timestamps happen and how to deal with it (other than customizing the gem)?

>mm= k.fetch_messages(topic:topic,partition:partition,offset: :earliest)
> 
> #<Kafka::FetchedMessage:0x0000559f96995eb8
>  @message=
>   #<Kafka::Protocol::Record:0x0000559f969a4d28
>    @attributes=0,
>    @bytesize=153,
>    @create_time=2021-01-02 21:02:27 +0000,
>    @headers={},
>    @is_control_record=false,
>    @key="81888377-c0bf-48b9-9e45-f9bcac1e1e25",
>    @offset=1,
>    @offset_delta=1,
>    @timestamp_delta=73927219,
> 
> 
> kafka-console-consumer --topic topic --bootstrap-server server:9092 --offset 0 --partition 81 --property print.timestamp=true
> 
> CreateTime:1535768055634  81888377-c0bf-48b9-9e45-f9bcac1e1e25

 DateTime.strptime("1535768055",'%s')
 => Sat, 01 Sep 2018 02:14:15 +0000

(mm[1].create_time - 73927219)
 => 2018-08-31 05:42:08 +0000

**Comment by Elyahou** [comment]
What is the version of kafka ?

**Comment by RD-Mobile-Admin** [comment]
> What is the version of kafka ?

2.0.0 (using confluent 5.0.0)

**Comment by Elyahou** [comment]
I had exactly the same issue with precedent ruby-kafka version and fixed it with this: 

https://github.com/zendesk/ruby-kafka/pull/706

Can you maybe debug it  further and check what is the `first_timestamp` of the record batch in this case ?

**Comment by RD-Mobile-Admin** [comment]
What appears to have happened is that some messages were produced in batches and somehow those timestamp_deltas were random high numbers. The first message in the batch has the correct date (and a delta of 0), the following have dates way into the future (equal to create_time of M1 + timestamp_delta seconds)
My understanding is that timestamp_delta would typically be a small number and the 'create_time' of a message would depend on the create_time of the first message in the batch and the timestamp_delta.
I've solved my issue by adding a getter to timestamp_delta and subtracting it from create_time, but my guess is that it FetchedMessage.create_time should take timestamp_delta into account.
My hunch (but i have not tested it yet) is that my previous reported issue (when the number of fetched messages is lower than the messages count) is related to this issue of having timestamps from the future.
