### ISSUE TITLE
create_topic method argument default values overriding kafka's default settings 

### ISSUE THREAD

**Issue by Vachman** [zendesk/ruby-kafka#725]
We configured kafka `default.replication.factor` and `num.partitions` in server.properties,
but create_topic method is probably overriding kafka server default setting by sending create_topic method arguments default values.
Is there any specific reason why it's done like that or we can change it?

https://github.com/zendesk/ruby-kafka/blob/0f29b7605bdfc58808b880163acd5dc18ec7e409/lib/kafka/client.rb#L552

**Comment by dasch** [comment]
What happens if you pass in `nil` to those params?

**Comment by Vachman** [comment]
```

**Comment by dasch** [comment]
Can you dig around the Kafka spec to see if passing nulls is allowed?
