### ISSUE TITLE
AsyncProducer backoff behavior differs from its documented behavior

### ISSUE THREAD

**Issue by jasonrosendale** [zendesk/ruby-kafka#727]
* Version of Ruby: 2.5.3
* Version of Kafka: 1.1.0
* Version of ruby-kafka: 0.7.6

###### Issue being reported
Although the documentation suggests that `retry_backoff` sets a linear backoff, the async_producer is implementing an exponential backoff.

###### Steps to reproduce
It seems clear that the backoff is exponential from https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/async_producer.rb#L256, but I was able to verify it by replacing the `retry_backoff` parameter with a test spy that wrote to a log whenever it was exponentiated:
```ruby
retry_backoff = 'the integer 2'
class << retry_backoff
  def fout
    @fout ||= File.open("backoff_log.txt", "w")
  end
  def **(other)
    fout.puts "exponentiating with #{other} at #{Time.now}"
    2 ** other
  end
end

client = Kafka.new(['localhost:9092'])
producer = client.async_producer(
    delivery_interval: 1,
    max_queue_size: 1000,
    max_retries: 8,
    retry_backoff: retry_backoff
    )
100000.times { producer.produce('hi', topic: 'arbitrary_topic') }
```
The contents of backoff_log.txt after executing:
```
exponentiating with 1 at 2019-04-23 20:04:49 +0000
exponentiating with 2 at 2019-04-23 20:04:51 +0000
exponentiating with 3 at 2019-04-23 20:04:55 +0000
exponentiating with 4 at 2019-04-23 20:05:03 +0000
exponentiating with 5 at 2019-04-23 20:05:19 +0000
exponentiating with 6 at 2019-04-23 20:05:51 +0000
exponentiating with 7 at 2019-04-23 20:06:55 +0000
exponentiating with 8 at 2019-04-23 20:09:03 +0000
```
###### Expected outcome
I would expect the backoff to be linear: that is, I would expect a retry every `retry_backoff` seconds. I base this on the documentation at https://github.com/zendesk/ruby-kafka#understanding-timeouts which says:

> retry_backoff configures the number of seconds to wait after a failed attempt to send messages to a Kafka broker before retrying. The max_retries setting defines the maximum number of retries to attempt, and so the total duration could be up to max_retries * retry_backoff seconds.

###### Actual outcome
The backoff is exponential and the total duration could be up to `retry_backoff ** (max_retries + 1)` seconds.

**Comment by dasch** [comment]
Thanks for reporting this! Would you be willing to provide a PR?
