### ISSUE TITLE
Latest version 0.7.7 breaks fluentd/td-agent's Kafka plugin

### ISSUE THREAD

**Issue by rchady** [zendesk/ruby-kafka#735]
If this is a bug report, please fill out the following:

* Version of Ruby: ruby-2.1.10 (embedded with td-agent)
* Version of Kafka: doesn't matter
* Version of ruby-kafka: 0.7.7

The recent PR that allows for host verification control breaks when used with the Kafka buffered output plugin for td-agent.  I'll open a ticket with them as well, but the error received is:

2019-05-21 09:58:06 -0400 [error]: unexpected error error_class=NoMethodError error=#<NoMethodError: undefined method `verify_hostname=' for #<OpenSSL::SSL::SSLContext:0x007f27a066b3f8>>

Which makes me suspect it is using an older openssl library, but figured you should be aware it causes this issue for others.

**Comment by dasch** [comment]
Should be fixed in master.
