### ISSUE TITLE
ssl connection issue for ruby < 2.4

### ISSUE THREAD

**Issue by Elyahou** [zendesk/ruby-kafka#741]
* Version of Ruby: < 2.4
* Version of Kafka: -
* Version of ruby-kafka: >= 0.7.7

Attempting to instanciate a ruby kafka instance with ssl cause an error: `NoMethodError: undefined method `verify_hostname=' for #<OpenSSL::SSL::SSLContext:0x00007fbb1b5a2520>`

`verify_hostname` is supported only from 2.4.0, so the ruby version should be enforced in ruby-kafka or should be supported at the implementation level.

**Comment by dorner** [comment]
+1'ing this. We can't ugprade past 0.7.6 because of this error.
