### ISSUE TITLE
Fail to connect with openssl 1.1.1

### ISSUE THREAD

**Issue by CharlieYe0205** [zendesk/ruby-kafka#747]
* Version of Ruby: 2.6.3 (should be any)
* Version of Openssl: 1.1.1b
* Version of Kafka: 2.2
* Version of ruby-kafka: 0.7.8

Connection failed when using openssl 1.1.1b. openssl 1.1.1b somehow restricts the ssl_version of ssl socket to TLSv1.3 which kafka has not supported yet. An exception of 'Crashed: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: wrong version number' will be raised. After downgrade openssl to 1.0.2s, the connection is fine.

**Comment by dasch** [comment]
Can you try with latest master?

**Comment by CharlieYe0205** [comment]
No, still the same error

Crashed: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: wrong version number
/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/bundler/gems/ruby-kafka-dce5db4d6ef7/lib/kafka/ssl_socket_with_timeout.rb:69:in `connect_nonblock'

The ssl version of @ssl_socket is still TLSv1.3

**Comment by edmeister** [comment]
@CharlieYe0205 did you find a solution for this issue?

**Comment by milonjames** [comment]
@edmeister check this - https://github.com/fluent/fluent-plugin-kafka/issues/305

**Comment by edmeister** [comment]
Thx @milonjames. I found out the same thing a few weeks ago.
