### ISSUE TITLE
Question: How to reset an offset?

### ISSUE THREAD

**Issue by rchady** [zendesk/ruby-kafka#754]
I have a consumer that I need to reset the offset on.  I have not found a way to do this because the start_from_beginning parameter to subscribe() only works if the consumer hasn't been checkpointed before.  Can this be done without having to change the group_id?

**Comment by dezka** [comment]
You can reset the offsets for a consumer group by running: 

```
kafka-consumer-groups --bootstrap-server <kafkahost:port> --group <group_id> --topic <topic_name> --reset-offsets --to-earliest
```

Would that work for you?

**Comment by rchady** [comment]
I was hoping to be able to do it via ruby-kafka programatically...

**Comment by dezka** [comment]
Oh, okay. I'm in the same boat as you on that one then, and have been doing it through the CLI like above.
