### ISSUE TITLE
Custom logger can no longer be used in 0.7.9.

### ISSUE THREAD

**Issue by brettburley** [zendesk/ruby-kafka#756]
* Version of Ruby: 2.4.6
* Version of ruby-kafka: 0.7.9

###### Steps to reproduce

```ruby
kafka = Kafka.new(['localhost:9092'], logger: MyLogger.new)

TypeError: no implicit conversion of MyLogger into String
/usr/local/rvm/rubies/ruby-2.4.6/lib/ruby/2.4.0/open-uri.rb:37:in `open'
/usr/local/rvm/rubies/ruby-2.4.6/lib/ruby/2.4.0/open-uri.rb:37:in `open'
/usr/local/rvm/rubies/ruby-2.4.6/lib/ruby/2.4.0/logger.rb:744:in `open_logfile'
/usr/local/rvm/rubies/ruby-2.4.6/lib/ruby/2.4.0/logger.rb:736:in `set_dev'
/usr/local/rvm/rubies/ruby-2.4.6/lib/ruby/2.4.0/logger.rb:671:in `initialize'
/usr/local/rvm/rubies/ruby-2.4.6/lib/ruby/2.4.0/logger.rb:387:in `new'
/usr/local/rvm/rubies/ruby-2.4.6/lib/ruby/2.4.0/logger.rb:387:in `initialize'
~/.bundle_local/ruby/2.4.0/gems/ruby-kafka-0.7.9/lib/kafka/tagged_logger.rb:63:in `new'
~/.bundle_local/ruby/2.4.0/gems/ruby-kafka-0.7.9/lib/kafka/tagged_logger.rb:63:in `initialize'
~/.bundle_local/ruby/2.4.0/gems/ruby-kafka-0.7.9/lib/kafka/tagged_logger.rb:56:in `new'
~/.bundle_local/ruby/2.4.0/gems/ruby-kafka-0.7.9/lib/kafka/tagged_logger.rb:56:in `new'
~/.bundle_local/ruby/2.4.0/gems/ruby-kafka-0.7.9/lib/kafka/client.rb:75:in `initialize'
~/.bundle_local/ruby/2.4.0/gems/ruby-kafka-0.7.9/lib/kafka.rb:366:in `new'
~/.bundle_local/ruby/2.4.0/gems/ruby-kafka-0.7.9/lib/kafka.rb:366:in `new'
```

###### Expected outcome

A custom logger class can be used.

###### Actual outcome

It appears that as a result of #716, when using a custom logger (that does not extend from `::Logger`), it attempts to create a `::Logger` instance, which can only accept a log device: https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/tagged_logger.rb#L63

**Comment by dorner** [comment]
... -_-
Ruby has an actual built-in Logger class, why are there so many other frameworks that don't use it? 🤦‍♂ 
I'll try to take a look at this in the next week or so.

**Comment by dorner** [comment]
Opened #762 to fix this, hopefully finally. My apologies for the last fix. I thought I was testing with Phobos but I forgot that I'd separately monkey-patched a fix in Phobos itself. :(

**Comment by dasch** [comment]
Thanks @dorner!
