### ISSUE TITLE
start_from_beginning not working after a consumer has checkpointed not intuitive

### ISSUE THREAD

**Issue by rchady** [zendesk/ruby-kafka#757]
* Version of Ruby: All
* Version of Kafka: All
* Version of ruby-kafka: All

The **_start_from_beginning_** flag to subscribe() seems to suggest it should start from the beginning.  Per the documentation this is ONLY true on the first time a consumer connects.  Once it checkpoints, that flag is no longer looked at which is not intuitive.  Even worse, since there is no current way to programmatically reset the offset for a consumer group, you are forced to use a new consumer group id or use an external tool to reset the offsets.

Can we make subscribe() always honor the **_start_from_beginning_** flag?  Either that, or add a new flag that lets you reset the offset when you subscribe?

**Comment by dasch** [comment]
The suggested way of solving the problem is to use a new group id. The behavior you suggest has a ton of tricky error conditions.

**Comment by rchady** [comment]
Could a way be introduced that separately would reset the offset then?  It is challenging to update the group_id programmatically across multiple consumers.  If a separate call could be introduced that would let you reset the offsets for a consumer group, it would work well.

**Comment by dasch** [comment]
Doing that correctly is very difficult. What is your use case? I would recommend against trying to go against the “Kafka model” when it comes to consumers.

**Comment by rchady** [comment]
The issue I am running in to is I have to periodically reset consumers in a group to start from the beginning of the topic and replay through.  Without a way to programmatically either reset the offset or  just start from the beginning when it subscribes I have no way to do this across multiple consumers.

**Comment by dasch** [comment]
I would restart the consumers with a new group id. That’s the safest solution.
