### ISSUE TITLE
Kafka::BufferOverflow being thrown with async_producer

### ISSUE THREAD

**Issue by rchady** [zendesk/ruby-kafka#758]
* Version of Ruby: 2.6
* Version of Kafka: 2.1
* Version of ruby-kafka: 0.7.9

I have a relatively simple program that reads from a consumer, does some transformations and then produces back to another topic.  No matter what variables I tweak, the async_producer() always ends up spitting out Kafka::BufferOverflow saying I reached 1000 messages (even if max_buffer_size is set to 5000).

I did some digging on this and it appears that what is really happening is when the producer tries to deliver the messages, it sends the entire batch of messages and if it exceeds the 1MB message limit it dies and ruby-kafka reports the BufferOverflow error instead.

Maybe I'm doing something wrong though, so are there any examples of a fast consumer/transformation/producer program that uses the async_producer without running in to this issue?

**Comment by dasch** [comment]
I would recommend against using the async producer for that use case. There’s currently no support for blocking writes to the async producer, so you’ll have better luck with the sync one.
