### ISSUE TITLE
KeyError when running different consumers of the same group subscribed to different topics

### ISSUE THREAD

**Issue by lairtonlelis** [zendesk/ruby-kafka#764]
* Version of Ruby: 2.6.3
* Version of Kafka: 2.1.1
* Version of ruby-kafka: 0.7.9 (master)

###### Steps to reproduce
Save the following script:
```ruby
# app.rb
require 'kafka'

client_id = ARGV[0]
group_id = ARGV[1]
topic = ARGV[2]

kafka = Kafka.new(
  ENV.fetch('KAFKA_BROKERS', 'localhost:9092').split(','),
  client_id: client_id
)

consumer = kafka.consumer(group_id: group_id)

consumer.subscribe(topic)

trap('TERM') { consumer.stop }
trap('INT') { consumer.stop }

consumer.each_message do |message|
  puts message.offset, message.key, message.value
end
```
Start the two commands below simultaneously:
```
ruby app.rb my-client group my-topic
```
```
ruby app.rb my-client-2 group my-topic-2
```
Stop them using CTRL+C, and try to start them again simultaneously 

###### Expected outcome
Both consumers can subscribe to their respective topics, like the first time they are run.

###### Actual outcome
The following exception is raised on the second consumer:

```

Traceback (most recent call last):
  17: from app.rb:28:in `<main>'
  16: from /home/user/.rvm/gems/ruby-2.6.3/gems/ruby-kafka-0.7.9/lib/kafka/consumer.rb:211:in `each_message'
  15: from /home/user/.rvm/gems/ruby-2.6.3/gems/ruby-kafka-0.7.9/lib/kafka/consumer.rb:403:in `consumer_loop'
  14: from /home/user/.rvm/gems/ruby-2.6.3/gems/ruby-kafka-0.7.9/lib/kafka/instrumenter.rb:35:in `instrument'
  13: from /home/user/.rvm/gems/ruby-2.6.3/gems/ruby-kafka-0.7.9/lib/kafka/instrumenter.rb:23:in `instrument'
  12: from /home/user/.rvm/gems/ruby-2.6.3/gems/ruby-kafka-0.7.9/lib/kafka/consumer.rb:404:in `block in consumer_loop'
  11: from /home/user/.rvm/gems/ruby-2.6.3/gems/ruby-kafka-0.7.9/lib/kafka/consumer.rb:212:in `block in each_message'
  10: from /home/user/.rvm/gems/ruby-2.6.3/gems/ruby-kafka-0.7.9/lib/kafka/consumer.rb:519:in `fetch_batches'
   9: from /home/user/.rvm/gems/ruby-2.6.3/gems/ruby-kafka-0.7.9/lib/kafka/consumer.rb:475:in `join_group'
   8: from /home/user/.rvm/gems/ruby-2.6.3/gems/ruby-kafka-0.7.9/lib/kafka/consumer.rb:475:in `each'
   7: from /home/user/.rvm/gems/ruby-2.6.3/gems/ruby-kafka-0.7.9/lib/kafka/consumer.rb:476:in `block in join_group'
   6: from /home/user/.rvm/gems/ruby-2.6.3/gems/ruby-kafka-0.7.9/lib/kafka/consumer.rb:476:in `each'
   5: from /home/user/.rvm/gems/ruby-2.6.3/gems/ruby-kafka-0.7.9/lib/kafka/consumer.rb:480:in `block (2 levels) in join_group'
   4: from /home/user/.rvm/gems/ruby-2.6.3/gems/ruby-kafka-0.7.9/lib/kafka/consumer.rb:492:in `seek_to_next'
   3: from /home/user/.rvm/gems/ruby-2.6.3/gems/ruby-kafka-0.7.9/lib/kafka/offset_manager.rb:103:in `next_offset_for'
   2: from /home/user/.rvm/gems/ruby-2.6.3/gems/ruby-kafka-0.7.9/lib/kafka/offset_manager.rb:183:in `resolve_offset'
   1: from /home/user/.rvm/gems/ruby-2.6.3/gems/ruby-kafka-0.7.9/lib/kafka/offset_manager.rb:188:in `fetch_resolved_offsets'
/home/user/.rvm/gems/ruby-2.6.3/gems/ruby-kafka-0.7.9/lib/kafka/offset_manager.rb:188:in `fetch': key not found: "my-topic" (KeyError)
```

If there is any trouble reproducing the bug, I've created a repository with more detailed instructions: https://github.com/lairtonlelis/ruby-kafka-bug

**Comment by mensfeld** [comment]
That's one of ruby-kafka limitations (as far as I remember). You should not run same consumer group for different topics.

**Comment by dasch** [comment]
What’s the point of using a single consumer group if the consumers aren’t subscribing to the same topics?

**Comment by Elyahou** [comment]
That is the case when you have a rolling deployments (kubernetes for example) and adding or removing a topic for your consumer group... This is causing us lot of hassle lately....

**Comment by dasch** [comment]
Ah, I see!

I would welcome a PR that fixes the issue, then – it'll be a while before I will have time to do one myself.

@Elyahou by the way, I would recommend against doing rolling deploys of consumers.

**Comment by OpakAlex** [comment]
Hello, any news about this one? I think it's cool if you can use one group for different topics.

**Comment by dasch** [comment]
@OpakAlex you can already subscribe to multiple topics, this was about having different members of the same group subscribed to _distinct_ topics.

**Comment by OpakAlex** [comment]
@dasch i have one group which subscribed to 2 topics, but this group owns 10 topics (per each staging), and then i have issue, that i didnt subscribe from staging 3 to topic which must be in staging 1. For this i think i need create diff groups per staging, then it will work fine. right?
