### ISSUE TITLE
How do I set auto.offset.reset config for my consumer?

### ISSUE THREAD

**Issue by komal-SkyNET** [zendesk/ruby-kafka#765]
I use ruby-kafka in my fluentd kafka plugin. Looking for a way to set the auto.offset.reset config  on my consumer so that I can make it consume from latest if the previously checkpointed offset for the consumer group is out of range/or doesn't exist anymore. 

Version.
fluent-plugin-kafka (0.10.0)
ruby-kafka (0.7.8)

**Comment by dasch** [comment]
I'm not sure how fluent configures that. [This is how](https://github.com/zendesk/ruby-kafka#topic-subscriptions) you'd do it using the ruby-kafka API directly.
