### ISSUE TITLE
Question about instantiating producers

### ISSUE THREAD

**Issue by bradurani** [zendesk/ruby-kafka#776]
Hi, I have a question

The README states clearly that the synchronous producers are not thread-safe and the asynchronous producers are. Is the safest thing to do just to instantiate a new producer every time one wants to write a message? Is there a performance penalty to instantiating producers on every write (besides the tiny insignificant cost of a few object allocations). In the synchronous case, is there an advantage to using the same instance in every thread versus instantiating a new one? In the async case, does it do any intialization logic to communicate with the queueing thread that would cause a penalty if I were to instantiate on every write?

Thanks

**Comment by dasch** [comment]
You should reuse the producer instances, just don't share them between threads. There's significant connection setup costs involved in creating a producer.

**Comment by bradurani** [comment]
Thanks!
