### ISSUE TITLE
Feature Request: AsyncProducer post-delivery callback with delivery IDs

### ISSUE THREAD

**Issue by johnnyshields** [zendesk/ruby-kafka#777]
I have a use case where I want to make sure the items I am producing are actually delivered when using an `AsyncProducer`

It would be really nice if there was a way that I could assign a unique ID to each item on the call to `#produce`, and then get a callback containing the array of IDs once `#deliver_messages` is triggered, e.g. by the timer/threshold.

Pseudo code example:

```ruby
async_producer = $kafka.async_producer(callback: ->(token_ary){ do_something })

async_producer.produce(value, token: 'abc123')
async_producer.produce(value, token: 'def456')

async_producer.deliver_messages #=> invokes my callback Proc with ['abc123', 'def456']
```

Could also add a failed-to-deliver callback as well.

I will probably just hack this by sub-classing AsyncProducer...

**Comment by edgurgel** [comment]
Yeah! This would be great!

**Comment by johnnyshields** [comment]
@dasch can you please reopen this and give it consideration?

**Comment by edgurgel** [comment]
I can try to send a PR if this is something that the project would benefit from?

**Comment by johnnyshields** [comment]
@edgurgel I'd definitely use it. should consider to implement with Promises
https://ruby-concurrency.github.io/concurrent-ruby/1.1.5/Concurrent/Promise.html

**Comment by dasch** [comment]
We want to keep ruby-kafka free from big dependencies like concurrent-ruby, but if there's a lightweight way to do this then I'd be open to it.

Alternatively, you can take a look at `rdkafka-ruby`, which supports this exact usage pattern.
