### ISSUE TITLE
Pause when a consumer loop is executing

### ISSUE THREAD

**Issue by priyanka-padlia** [zendesk/ruby-kafka#783]
I see the pause functionality has been implemented to pause processing messages for a partition. But the use case I have is to pause the consumer loop for indefinite time and resume later. This will pause processing of any message until notified to resume. Is there a way to do this using ruby-kafka.

https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/consumer.rb#L204

**Comment by dasch** [comment]
Not currently.
