### ISSUE TITLE
Expose a consumer group offsets method in the client

### ISSUE THREAD

**Issue by rkrage** [zendesk/ruby-kafka#785]
For tooling / automation scripts, it would be super helpful to expose a method in the client object for querying consumer group offsets. It looks like this information is available via an `OffsetFetchRequest`.

If this is something that makes sense to add, I can take a stab at writing it.

Another interesting question, should this be a new method or an enhancement to the existing `describe_group` method?

**Comment by dasch** [comment]
Go for it! Not sure where it belongs, depends on the use cases.

**Comment by rkrage** [comment]
@dasch what would be the process for bumping the protocol version for the `OffsetFetchRequest`? Currently It's hard-coded to use version 1, but we need version 2 or higher to retrieve offsets for _all_ partitions of consumer group.

https://kafka.apache.org/protocol#The_Messages_OffsetFetch

Relevant bit:

> Topics to fetch offsets. If the topic array is null fetch offsets for all topics.

**Comment by rkrage** [comment]
I guess the logic could also be conditional and we'd use version 2 if topics is nil

**Comment by dasch** [comment]
> @dasch what would be the process for bumping the protocol version for the `OffsetFetchRequest`? Currently It's hard-coded to use version 1, but we need version 2 or higher to retrieve offsets for _all_ partitions of consumer group.
> 
> https://kafka.apache.org/protocol#The_Messages_OffsetFetch
> 
> Relevant bit:
> 
> > Topics to fetch offsets. If the topic array is null fetch offsets for all topics.

It depends on whether API version 1 is still used in the Kafka versions supported by ruby-kafka.
