### ISSUE TITLE
Kafka::GroupAuthorizationFailed

### ISSUE THREAD

**Issue by dvora-worthy** [zendesk/ruby-kafka#788]
If this is a bug report, please fill out the following:

* Version of Ruby: 2.5.1
* Version of ruby-kafka: 0.7.9

I'm trying to consume messages on heroku remote server and get the error `Kafka::GroupAuthorizationFailed`
in my local env it works as excepted.

###### my code looks like

```ruby
 register_topics.each do |topic, data|
      @consumer.subscribe(topic)
      p "topic #{topic} subscribed"
      @topic_router[topic] = data
    end

    begin
      @consumer.each_message do |message|
          p 'message', message
      end
    rescue Exception => e
      p "each_message exception #{e.cause}"
      raise "Error! failed processing message: #{e.message}"
    end
```

@stevenjm @dasch @dgmcguire Can someone advice what can cause this?
Thanks in advance.

**Comment by tjwp** [comment]
Based on the prefix on the topic name in the log, it looks like you are using Heroku's multi-tenant Kafka offering. On that plan, consumer groups must be created using Heroku's CLI.  Take a look at `heroku help kafka:consumer-groups:create`.

I believe you'll see the `GroupAuthorizationFailed` error if you have not created the consumer group.

**Comment by dvora-worthy** [comment]
@tjwp thatnks for your answer

what do you mean? 
should I create the consumer group via cli and then passing the group_id when declaring the consumer?
