### ISSUE TITLE
Interruptible consumer loop

### ISSUE THREAD

**Issue by andrewjamesbrown** [zendesk/ruby-kafka#794]
We currently run kafka consumers in a jobs framework, where the expectation is that jobs complete in a certain period of time (e.g. 60s).  As it is right now, the `each_batch` or `each_message` block will block indefinitely until there are messages on the topic.  We understand that is generally desirable in the common case, and that our use-case is slightly outside the norm, but that is what it is 🤷‍♂ 

@dasch what's your preference here:
- encumber the `each_message` and `each_batch` methods with a `timeout` function described in https://github.com/zendesk/ruby-kafka/issues/578 (which, BTW we've been running as a fork for quite a long time successfully)
- re-open https://github.com/zendesk/ruby-kafka/pull/369 and work to get that merged

Thanks and we appreciate your time and effort into supporting ruby-kafka ❤️

**Comment by dasch** [comment]
I definitely think the poll approach would be best.
