### ISSUE TITLE
Possible flaky create partitions test

### ISSUE THREAD

**Issue by andrewjamesbrown** [zendesk/ruby-kafka#796]
If this is a bug report, please fill out the following:

* Version of Ruby: `circleci/ruby:2.5.1-node`
* Version of Kafka: `2.1.1`
* Version of ruby-kafka: `master`

Please verify that the problem you're seeing hasn't been fixed by the current `master` of ruby-kafka.

###### Steps to reproduce

I've been getting failing tests for the `create partitions` test in CI but only on a single version of Kafka, which _feels_ to me like a flaky test due to async operations or something like that

@dasch how would you like to see this fixed?
Ideas:
- Add a static `sleep(1)` between the `create_partitions_for` and `partitions_for` check
- Add a retry so we check several times (e.g. by adding https://github.com/NoRedInk/rspec-retry or https://github.com/rstacruz/rspec-repeat)
- Other?

**Comment by andrewjamesbrown** [comment]
Failing test: https://circleci.com/gh/Shopify/ruby-kafka/295?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by dasch** [comment]
I think the retry approach could work well. I'd love to see a PR.
