### ISSUE TITLE
OpenSSL Certificate Verification Failed

### ISSUE THREAD

**Issue by davidpatters0n** [zendesk/ruby-kafka#799]
If this is a bug report, please fill out the following:

* Version of Ruby: 2.3.4
* Version of ruby-kafka: v0.7.10

Please verify that the problem you're seeing hasn't been fixed by the current `master` of ruby-kafka.

###### Steps to reproduce

Ruby Kafka client defined as followed: 

```ruby
 Kafka.new(
  %w[kafka1:9093],
  logger: Rails.logger,
  ssl_ca_cert: File.read('config/ccpa/root_ca.pem'),
  ssl_client_cert: File.read('config/ccpa/privacy-sor.pem'),
  ssl_client_cert_key: File.read('config/ccpa/privacy-sor.pem')
)
```

# Please write an example that reproduces the problem you're describing.
I'm encoding a message via Avro am trying to do deliver this message, in doing so when I try to deliver this message I get an error that the certificate couldn't be verified. In addition to this I've confirmed that the issue isn't with the certs because when I run: 

```
openssl s_client \
-host kf0002.cf.prd349.preprod3.bar.foo \
-port 9093 \
-CAfile root_ca.pem \
-state -debug \
-cert privacy-sor.pem \
-key privacy-sor.pem
```

I get: `Verify return code: 0 (ok)`

###### Expected outcome

My expected outcome is certificate verification doesn't fail. 

###### Actual outcome

When I try to deliver a encoded avro message to my topic I got the following: 

```ruby
New topics added to target list: privacy.prd2293.datadictionary.v0.qa
Fetching cluster metadata from kafka://kf0002.cf.prd349.dev3.bar.foo:9093
[topic_metadata] Opening connection to kf0002.cf.prd349.dev3.bar.foo:9093 with client id ruby-kafka...
Closing socket to kf0002.cf.prd349.dev3.bar.foo:9093
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed
from /Users/home/Code/web/.bundle/ruby/2.3.0/gems/ruby-kafka-0.7.10/lib/kafka/ssl_socket_with_timeout.rb:69:in `connect_nonblock'
```

**Comment by mensfeld** [comment]
@q-cloud-ll I think:

```
OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE
```

but also keep in mind this library is no longer maintained (please see the readme note on alternatives recommended)

**Comment by q-cloud-ll** [comment]
> @q-cloud-ll我认为：
> 
> ```
> OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE
> ```
> 
> 但也请记住，该库不再维护（请参阅上述文件中有关推荐替代方案的说明）

Traceback (most recent call last):
	21: from main.rb:16:in <main>'
	20: from /home/rtb/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.5.0/lib/kafka/producer.rb:254:in deliver_messages'
	19: from /home/rtb/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.5.0/lib/kafka/instrumenter.rb:23:in instrument'
	18: from /home/rtb/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.5.0/lib/kafka/producer.rb:261:in block in deliver_messages'
	17: from /home/rtb/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.5.0/lib/kafka/producer.rb:385:in deliver_messages_with_retries'
	16: from /home/rtb/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.5.0/lib/kafka/cluster.rb:59:in add_target_topics'
	15: from /home/rtb/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.5.0/lib/kafka/cluster.rb:105:in refresh_metadata!'
	14: from /home/rtb/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.5.0/lib/kafka/cluster.rb:405:in cluster_info'
	13: from /home/rtb/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.5.0/lib/kafka/cluster.rb:424:in fetch_cluster_info'
	12: from /home/rtb/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.5.0/lib/kafka/cluster.rb:424:in each'
	11: from /home/rtb/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.5.0/lib/kafka/cluster.rb:425:in block in fetch_cluster_info'
	10: from /home/rtb/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.5.0/lib/kafka/cluster.rb:425:in each'
	 9: from /home/rtb/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.5.0/lib/kafka/cluster.rb:432:in block (2 levels) in fetch_cluster_info'
	 8: from /home/rtb/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.5.0/lib/kafka/broker.rb:44:in fetch_metadata'
	 7: from /home/rtb/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.5.0/lib/kafka/broker.rb:200:in send_request'
	 6: from /home/rtb/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.5.0/lib/kafka/connection.rb:100:in send_request'
	 5: from /home/rtb/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.5.0/lib/kafka/instrumenter.rb:23:in instrument'
	 4: from /home/rtb/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.5.0/lib/kafka/connection.rb:101:in block in send_request'
	 3: from /home/rtb/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.5.0/lib/kafka/connection.rb:130:in open'
	 2: from /home/rtb/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.5.0/lib/kafka/connection.rb:130:in new'
	 1: from /home/rtb/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.5.0/lib/kafka/ssl_socket_with_timeout.rb:69:in initialize'
/home/rtb/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.5.0/lib/kafka/ssl_socket_with_timeout.rb:69:in connect_nonblock': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (ok) (OpenSSL::SSL::SSLError)    ===== >>> I am ruby-kafka referenced in the fluentd-kafka plug-in. I must pass the tls verification of the ssl certificate to connect to kafka. The current ruby ​​version can only support the ruby-kafka plug-in. Is there a way to solve the above error? 
very grateful u

**Comment by mensfeld** [comment]
Unfortunately, I am unsure if there is a way, and I will not be able to assist you. Sorry.
