### ISSUE TITLE
Manually fetch messages

### ISSUE THREAD

**Issue by thiamsantos** [zendesk/ruby-kafka#805]
There is a way to manually fetch messages in a consumer? Looking at the code seems that only public method is `#each_message`. I would like a way to manually fetch the batches of messages. We have a way to do that without having to rely on the internal implementation of the consumer?

**Comment by dasch** [comment]
Have you looked at https://www.rubydoc.info/gems/ruby-kafka/Kafka%2FClient:fetch_messages ?

**Comment by thiamsantos** [comment]
Thanks @dasch , I will test it, and see if it is enough for our requirements. And sorry for not founding that on the documentation :see_no_evil: :stuck_out_tongue:
