### ISSUE TITLE
Datadog Statsd constants moved again

### ISSUE THREAD

**Issue by tjwp** [zendesk/ruby-kafka#809]
Datadog has released a new version (4.7.0) of the dogstatsd-ruby gem that moves the constants for DEFAULT_HOST and DEFAULT_PORT. 

This will break the following again: https://github.com/zendesk/ruby-kafka/blob/e4bef8053712fdda70a5909a1cc08c2fbceebeb6/lib/kafka/datadog.rb#L80-L86

This is the latest location of the constants: https://github.com/DataDog/dogstatsd-ruby/commit/fc849eaf69daf90bfad3e2257186947d13aeac3d#diff-b20e3c6dba19c28da3f38d94fea3e9c7R8-R9

**Comment by jonmagic** [comment]
For now I opened https://github.com/zendesk/ruby-kafka/pull/810 to lock to the versions before the move.

**Comment by tjwp** [comment]
Fixed by https://github.com/zendesk/ruby-kafka/pull/810
