### ISSUE TITLE
Does 1.0 work with Kafka 0.10?

### ISSUE THREAD

**Issue by fxn** [zendesk/ruby-kafka#816]
Hi, the README says that there is full support for 0.10 in the 0.5.x series. However, it is not 100% clear to me from the wording that future versions can't talk to Kafka 0.10.

I see in the CHANGELOG for newer versions of `ruby-kafka` things that seem generic improvements per se.

I need to consume from Kafka 0.10, should I stay with 0.5.5?

**Comment by PragTob** [comment]
:wave: 

Hello my friend @fxn :)

I came here with a similar question. The [changelog for 0.7.0](https://github.com/zendesk/ruby-kafka/blob/master/CHANGELOG.md#070) states that support for kafka 0.10 was dropped there:

> Drop support for Kafka 0.10 in favor of native support for Kafka 0.11.

BUT in a project I'm on at the moment and have a mixture of ruby-kafka versions running that should be incompatible from their official kafka version support but somehow work (0.5.x - 0.7.x) and are currently running against 1.0 and 2.3 but I believe they ran against 0.10 before (not sure).

So what I'm trying to say I'm also interested in the answer to this question but I suspect the answer is "it's not supported but it might work as long as you don't use certain features aimed at newer kafka versions".

**Comment by fxn** [comment]
Awesome @PragTob 😄 .
