### ISSUE TITLE
Can this be changed to debug?

### ISSUE THREAD

**Issue by jonmagic** [zendesk/ruby-kafka#820]
We've been tuning our logging lately and noticed this was set to `info` but wondering if it could be changed to `debug`?

https://github.com/zendesk/ruby-kafka/blob/fff91eff27665b0650231432d48055a13f56c84e/lib/kafka/produce_operation.rb#L107

**Comment by dasch** [comment]
Wouldn't you want to be able to see that info when looking into past incidents?

**Comment by jonmagic** [comment]
> Wouldn't you want to be able to see that info when looking into past incidents?

For us that message doesn't include enough information to be all that helpful in debugging. We tend to lean more on metrics (datadog) and error reporting (sentry) to discover and debug an incident.
