### ISSUE TITLE
Retrying to deliver messages does't make sense for Kafka::MessageSizeTooLarge error

### ISSUE THREAD

**Issue by iprlic** [zendesk/ruby-kafka#821]
* Version of Ruby: 2.6.5
* Version of Kafka: 5.2.2
* Version of ruby-kafka: 0.7.8

###### Steps to reproduce

If we try to deliver a message with a payload too large we'll get `
Kafka::MessageSizeTooLarge` and then https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/async_producer.rb#L238 ensures there will be a retry. This causes an endless loop since the message will not get any smaller no matter the retries. There might be other errors where retrying makes no sense.

```ruby
WaterDrop::AsyncProducer.call('a'*1_000_000, topic:'test')
```

###### Expected outcome

Error is logged and the attempts of delivery are stopped.

###### Actual outcome

There is an endless loop of trying to deliver the message and failing with `Kafka::MessageSizeTooLarge`

**Comment by dasch** [comment]
I believe there was some work done at some point on identifying the message in question and removing it, subject to configuration. Not sure where that ended. It would be great if you could do an investigation of possible routes forward.
