### ISSUE TITLE
How about to add a custom exception process hook to Kafka::AsyncProducer::Worker

### ISSUE THREAD

**Issue by xuxiangyang** [zendesk/ruby-kafka#829]
How about to add a custom exception process hook in the under two catch? 

 https://github.com/zendesk/ruby-kafka/blob/0d64a9b05326c02c5f148c710f5da25990a84d0b/lib/kafka/async_producer.rb#L233-L241

If some exception happened, now this gem only generate a log, it is too silence. with a custom exception process hook, we could use some error tracking system (like sentry).

Here is a real example, I write some code like this

```ruby
$kafka.produce("data", topic: :test)
```

this will generate a `Unexpected Kafka error NoMethodError: undefined method 'bytesize' for :test`, then the broker with reconnect, Because  I have many topic, other topic work fine and this topic is not so busy, so I only observe that  AsyncProducer queue is always increasing. after check log, I find this exception.

I think it is necessary to report produce exception to error track system, so, we cloud monitor this exception more reliably

**Comment by xuxiangyang** [comment]
I think you should not `rescue Exception`,  spell error will be rescued too. see this answer

https://stackoverflow.com/questions/10048173/why-is-it-bad-style-to-rescue-exception-e-in-ruby

**Comment by dasch** [comment]
Hmm, I'd rather the entire process crashed in that case.

**Comment by xuxiangyang** [comment]
> Hmm, I'd rather the entire process crashed in that case.

yes, so you should only catch `StandardError`, and with a hook to custom process or monitor exception
