### ISSUE TITLE
NameError: uninitialized constant Kafka::Consumer::Concurrent on v1.1.0

### ISSUE THREAD

**Issue by fernandes** [zendesk/ruby-kafka#840]
If this is a bug report, please fill out the following:

* Version of Ruby: 2.6.6p146
* Version of Kafka: 2.5.0
* Version of ruby-kafka: 1.1.0

Please verify that the problem you're seeing hasn't been fixed by the current `master` of ruby-kafka.

It it's not, still showing using [Concurrent::Map](https://github.com/zendesk/ruby-kafka/blob/703bf8065390a6c2c01268d08a245b53b045f738/lib/kafka/consumer.rb#L79)

###### Steps to reproduce

1. Use ruby kafka outside rails (In my case it's a racecar consumer)

###### Expected outcome

Was expected to run normally

###### Actual outcome

=> Crashed: NameError: uninitialized constant Kafka::Consumer::Concurrent
vendor/bundle/ruby/2.6.0/gems/ruby-kafka-1.1.0/lib/kafka/consumer.rb:79:in `initialize'

###### Possible solution

In my case I solved adding `concurrent-ruby` as dependency and then `require 'concurrent/map'` on my lib file.

I suspect this is caused because ActiveSupport install `ruby-concurrency` as its dependency and it's being installed as dev dependency on the [gemspec](https://github.com/zendesk/ruby-kafka/blob/master/ruby-kafka.gemspec#L39) so it wouldn't break in development/tests.

My suggestion is to add `ruby-concurrent` as a runtime dependency

**Comment by TJC** [comment]
I just hit this bug independently!

Likewise, the fix was to add a `require "concurrent/map"
