### ISSUE TITLE
undefined method `monotonic_time' for Concurrent:Module (NoMethodError)

### ISSUE THREAD

**Issue by TJC** [zendesk/ruby-kafka#842]
* Version of Ruby: 2.7.1
* Version of Kafka: (not applicable)
* Version of ruby-kafka: 1.1.0

###### Steps to reproduce

```ruby
require "kafka"
require "kafka/datadog"

kafka = Kafka.new(brokers, client_id: "example")
consumer = kafka.consumer(group_id: "example_group")
consumer.subscribe("my_topic")
consumer.each_message do |msg|
  puts "hi!"
end
```

Attempt to run above code, and receive error:
```
undefined method `monotonic_time' for Concurrent:Module
```

##  Fix

Include this extra require prior to the kafka/datadog import:

```
require "concurrent/utility/monotonic_time"
require "kafka/datadog"
```

**Comment by TJC** [comment]
Hi,
I know this issue was closed 20 days ago, but the issue is still present in the current stable release  - 1.1.0.

Are there any plans to release a new version that contains the fix?

**Comment by dasch** [comment]
v1.2.0 has just been released.
