### ISSUE TITLE
Stop Consumer from a script without having to send SIGTERM to PID

### ISSUE THREAD

**Issue by abhinay2891** [zendesk/ruby-kafka#843]
If this is a bug report, please fill out the following:

* Version of Ruby: 2.5.1
* Version of Kafka: 1.0.0
* Version of ruby-kafka: 1.0.0

###### Steps to reproduce

```ruby
class KafkaClient
  def initialize(topic = "test")
    logger = Logger.new("log/kafka.log")
    @kafka = Kafka.new(['remote_broker:9092'],
                       logger: logger)
    @topic = topic
  end
def consume_data(args = {})
    consumer = @kafka.consumer(group_id: group_id)
    consumer.subscribe(@topic, start_from_beginning: from_beginning)
    consumer.each_message do |message|
      Log.debug [:offset, message.offset, :value, message.value]
      consumer.mark_message_as_processed(message)
    end

    **trap("TERM") consumer.stop**
  end

# Please write an example that reproduces the problem you're describing.
```

Why can't the consumer be stopped without actually having to trap a SIGTERM/ Kill the PID running the consumer. I would like consumer.stop alone to shut down the consumer.

###### Actual outcome
I have to send SIGTERM every time I need the consumer to trap the signal and stop. My script doesnt have access to kill a process.

**Comment by dasch** [comment]
Your script can stop the consumer at any time – but you’d probably need to do it from a different thread or from within the consumer loop (`each_message`) because the loop continues until shutdown.

**Comment by abhinay2891** [comment]
Basically I wanted to control the consumer and stop it after a set of tests for a given duration.

I override the Kafka::Consumer.each_message method inside my KafkaClient Class.
`consumer.stop`  is called after a specified interval of time, which is decided by the stop_time: parameter passed to each_message.
          
`module Kafka
  class Consumer
    def each_message(min_bytes: 1, max_bytes: 10485760, max_wait_time: 1, automatically_mark_as_processed: true, stop_time: 60)
.....
......
      if Time.now.to_i > start_time + stop_time
          Log.debug("Consumer Stopped after #{stop_time} Seconds")
          stop
       end`
