### ISSUE TITLE
Time.at(Float) is quite slow

### ISSUE THREAD

**Issue by eregon** [zendesk/ruby-kafka#844]
* Version of Ruby: ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux]

When consuming a message from Kafka, a Time object is built using `Time.at(Float)`:
https://github.com/zendesk/ruby-kafka/blob/6ccbb0f61ea174812814c51b6948ea3f279ffb46/lib/kafka/protocol/message.rb#L100

This seems innocuous but it's actually pretty slow, because internally `Time.at` will try to get an exact number for that Float to not lose any nanoseconds due to Float errors, which creates a Rational (which is not a cheap conversion) and potentially some large heap-allocated Integers, etc.

A trivial benchmark on MRI 2.6,
`benchmark { Time.at(232132.123) }` shows ~1.7Mips,
while `benchmark { Time.at(232132, 123_000) }` shows ~6Mips.
Similar difference on TruffleRuby.

Something like `Time.at(timestamp / 1000, timestamp % 1000 * 1000)` should work.

The Float version is also slightly inaccurate:
`Time.at(232132.123).nsec # => 122999999`

cc @fxn

**Comment by eregon** [comment]
Somewhat related: https://bugs.ruby-lang.org/issues/16470
One more reason to not use `Time.at(Float)` basically.

**Comment by dasch** [comment]
@eregon thanks! Would you be able to do a PR? I’m too busy these days for most dev work, unfortunately.

**Comment by eregon** [comment]
@dash Was this closed for inactivity?

**Comment by dasch** [comment]
Yup. Feel free to open a PR.
