### ISSUE TITLE
Retry topic subscription in a different thread?

### ISSUE THREAD

**Issue by fxn** [zendesk/ruby-kafka#850]
Hi! Opening this issue because I am not 100% sure the caveats about thread-safety mentioned in the README apply to my use case.

I have an application that only consumes using a consumer group. In order to avoid strict deploy ordering between producers and this application when new topics are created, I'm thinking about the following:

1. Instantiate a consumer, and put it on a `each_message` block.
2. Pass the consumer and the list of topics to subscribe to a thread.
3. In that thread, the consumer checks for topic existence and subscribes to topics if/when they exist, with spaced retries for missing topics.
4. When all topics have been joined, the thread exits, and the main loop will be processing everything.

Would that be thread-safe?

**Comment by dasch** [comment]
Do you need a consumer for that? I _think_ this will work:

```ruby
kafka = Kafka.new(...)

# List of required topics.
topics = ["topic-1", ...]

until topics.empty?
  topics.each do |topic|
    topics.delete(topic) if kafka.has_topic?(topic)
  end

  sleep 10 # let's wait a bit
end

# start your app here!
```

**Comment by fxn** [comment]
Problem is, I have several services creating topics at different times. When a deploy happens, if service A has started to produce, I want to consume. If service B starts producing 10 minutes later, then I'll consume too, but meanwhile A has been processed.

**Comment by dasch** [comment]
Do these topics follow a predictable naming scheme? If so, subscribing by regex should allow for dynamically picking up new topics.

**Comment by dasch** [comment]
You need to pass `refresh_topic_interval:` to `consumer`.

**Comment by fxn** [comment]
There is no pattern. Technically I could OR the topics in a regexp, but I see two problems:

1. When all topics have been created, I do not need to recheck again.
2. The point of not calling `subscribe` is to not subscribe to a non-existing topic. If autocreation is disabled, you can't. If enabled, you do not own the attributes of that topic anyway (retention policy, number of partitions, etc.), the producer is the owner of them.

**Comment by fxn** [comment]
To be 100% clear, I do not need this to be supported explicitly.

It'd be enough if I can call `subscribe` from a different thread myself, which the consumer is in the `each_message` main loop. But the docs say the lib is not thread-safe, so I wonder if this particular use-case would be still OK, or else if support for it could be added.

**Comment by dasch** [comment]
Hmm, you'd have to test this out because I'm not sure it'll work – but maybe if you converted each topic name to a regex before subscribing you'd get "lazy" subscriptions? That is, if the topic doesn't exist, the regex won't match anything and so won't subscribe, but once the topic is created it'll match and the subscription will be set up.

**Comment by dasch** [comment]
I'm not sure making `subscribe` thread safe is worth the effort and added complexity – subscribing out-of-thread seems to be a somewhat esoteric use case. But dynamically picking up topics as they're created doesn't sound crazy, and is in fact something I'd be looking into doing soon. But the regex approach should already work there.

**Comment by fxn** [comment]
Ah, I've read the source, I see what you mean.

If I am not mistaken, if topic T exists on boot, and topic S is created later, since the scan happens on each iteration of the main loop, and that happens with each poll, event if T is quiet, the consumer would subscribe to S in a timely fashion right? Won't be blocked because T is sending nothing.

Yes, I think that'd work. In this approach, the only thing that I'd miss would be the ability to disable scans, because in the end I have only a bunch of fixed topics to subscribe to. Maybe that leaks there, because re-scanning now an then makes sense for a widlcard pattern, say, but not for this use case, in which we are tunneling fixed strings just to leverage this existing code.

Unfortunately, I am running 0.5.5, though, don't even have this feature available. So, my comment above is feedback for master, but for 0.5.5, if subscribing in a different thread is not thread-safe, I'll see if I can hack something.

I think we can close this one, thank you!

**Comment by dasch** [comment]
Cool! I remember there being a setting that controlled the scan frequency, but I could be wrong.
