### ISSUE TITLE
Is there a reason for not doing GEM release 1.2 that includes critical fixes?

### ISSUE THREAD

**Issue by jdevalk2** [zendesk/ruby-kafka#853]
Until version 1.2 of RubyKafka is released to GEM repo,  downstream FluentD Kafka is as good as unusable.
Wondering why there has not been a release for 1 month even though critical fix was made.

I know technically its downstream project thats not zendesk responsibility, but unfortunate effect is downstream project is now broken as it links in broken 1.1 ruby-kafka GEM.

Fix in question:
https://github.com/zendesk/ruby-kafka/commit/526bb07f7fcf35370605a51a25a203d0bb0a5b21

FluentD kafka plugin relies on this ruby-kafka library
Since February'ish release of FluentD docker links in v1.1 ruby-kafka for Kafka plugin,  FluentD kafka plugin is pretty much dead in the water.  It will run for a little while and then hit the offending code and terminate the docker container due to a NIL object reference.

Had to fall back to a January version of FluentD docker image.

Its impossible to upgrade FluentD to newer (that pulls from Kafka) now without it breaking due to that dependency.

**Comment by dasch** [comment]
Just released v1.2.0.
