### ISSUE TITLE
Ruby script stalls at @offset_manager.commit_offsets_if_necessary in consumer.rb

### ISSUE THREAD

**Issue by rishabhsinghvi** [zendesk/ruby-kafka#864]
If this is a bug report, please fill out the following:

* Version of Ruby: 2.7.1
* Version of Kafka: 2.5
* Version of ruby-kafka: 1.2

For a while, I've found that my ruby script will stop responding after a while. Using byebug, I found that the culprit is line 257 in [consumer.rb](https://github.com/zendesk/ruby-kafka/blob/dad40c965fecf807333cc151d2f512957fd9ffd3/lib/kafka/consumer.rb#L257), specifically:

` @offset_manager.commit_offsets_if_necessary`

Not sure what is causing the error, any advice would be appreciated.

**Comment by dasch** [comment]
Can you enable debug logs and paste them here?
