### ISSUE TITLE
Allow blocking when producing with the async producer

### ISSUE THREAD

**Issue by dasch** [zendesk/ruby-kafka#88]
Currently, when calling `#produce` on an async producer when the message queue is full a BufferOverflow exception is raised. It would be nice to have the option of blocking instead. Bonus points if there's a configurable timeout.

Note that in order to do this correctly a more sophisticated bounded queue would need to be implemented.

**Comment by hkroger** [comment]
This would be nice since it's also impossible to check the queue length at the moment to halt producing messages if queue is getting too long.

**Comment by dasch** [comment]
Closing due to a lack of activity.
