### ISSUE TITLE
Few Partitions of topic are very slow intermittently

### ISSUE THREAD

**Issue by sathia27** [zendesk/ruby-kafka#891]
Few Partitions of topic are very slow intermittently. Lag for 2-3 partitions will keep increasing and not decreasing. Once we restart the service everything looks normal. All Lag is getting reduced fast. 

If this is a bug report, please fill out the following:

* Version of Ruby: ruby 2.3.6p384
* Version of Kafka: 2.4.1.1
* Version of ruby-kafka: 1.3.0 (Recently upgraded from  0.7 to 1.3.0), we are facing below issues in both versions. Tested with master as well.

###### Steps to reproduce

Below code is running as rake task.

```ruby
kafka_consumer = Kafka.new(...)
topics.split(',').collect(&:strip).each do |topic|
   kafka_consumer.subscribe(topic, start_from_beginning: start_from_beginning
end
stop_consumer_proc = proc do
      Rails.logger.info('Stopping kafka consumer...')
      kafka_consumer.stop
      Rails.logger.info('Stopped kafka consumer...')
      exit
end
trap('SIGINT', &stop_consumer_proc)
trap('SIGTERM', &stop_consumer_proc)
kafka_consumer.each_message(max_wait_time: 10) do |message|
  begin
      kafka_consumer.each_message(max_wait_time: 10) do |message|
       #raises exception or True
        consume_messages(message)
      end
    rescue Kafka::Error => e
      Rails.logger.error("Kafka processing error", error_message: e.message, backtrace: e.backtrace)
      raise
    rescue StandardError => e
      Rails.logger.error("Error processing messages", error_message: e.message, backtrace: e.backtrace)
      raise
    end
end
```

###### Expected outcome

When there is any issues in Kafka connection error like EOF error, Timeout error. Ruby-kafka should raise error. Once ruby-kafka raises error, Consumer should shut-down.

###### Actual outcome
We can see there are timeouts and EOF error happening while making fetch, kafka-offset api. We found this from ruby-kafka notification events.

```ruby
    ActiveSupport::Notifications.subscribe(/.*\.kafka$/) do |*args|
      event = ActiveSupport::Notifications::Event.new(*args)
      if ["heartbeat", "fetch", "offset_commit"].include?(event.payload[:api].to_s)
        Rails.logger.info('[rb-kafka] kafka notification', event.payload)
      end
    end
```

But there is no exception raised by ruby-kafka client. Impact is that whenever there is timeouts happening, there is few partitions (2-3 partitions) are getting stuck due to that combined lag is increasing. This is currently happening in production environment.

We have other kafka consumers written in python which is working expected at this time of incidents.

**Comment by dasch** [comment]
Timeouts and network errors do not cause consumer loops to crash – those are considered ephemeral problems, and retries and backoffs are used to deal with them. Do you have a monitoring setup where you can graph key metrics? ruby-kafka comes with a Datadog integration out of the box.

**Comment by sathia27** [comment]
I don't see any retry and back-offs are happening with my case. I can see single partition was not consumed for last half an hour, once i restart the consumer, then everything is picked up very fast.

We have kafkdrop configured for our brokers, so i will be monitoring partition and combined lag in real-time. Also we have configured burrow to check historical combined lag.

**Comment by dasch** [comment]
Do you have logs?

**Comment by sathia27** [comment]
@dasch 

Below is Same logs came from particular task from last 1 hour. After restart connection issue seems normal. I feel this indicates there is issue with re-connection.

```
payload:
api:fetch
broker_host:xxxxx.amazonaws.com
client_id:xxxxx
request_size:129
response_size:0
exception:["Errno::ETIMEDOUT", "Connection timed out"]
```

**Comment by Ravinderbaid** [comment]
@dasch @spuun Any clues why this is happening?

**Comment by dasch** [comment]
We'd need to see proper ruby-kafka logs. Are you passing a logger instance with e.g. DEBUG level?
