### ISSUE TITLE
Add a after_batch hook on the `each_message` method

### ISSUE THREAD

**Issue by arthurnn** [zendesk/ruby-kafka#892]
This is not a bug, is more of a feature request, that if accepted I am glad to work on a PR to implement it.

### My use case
I am using `each_message` in a lot of different consumer processors. However, I have a few that needs to do something after a batch is processed. Today, I could use the `each_batch` for those. However, using `each_message` gives me the heartbeat trigger after each message, so it is safer, as we can have lower session timeouts.

### Proposal
Add an after_batch hook to the `each_message` method. So we can still use it, but have a place to execute code after each batch is done.

**Comment by dasch** [comment]
Have you started by trying to call the `heartbeat` method manually within `each_batch` to get your desired behavior?

**Comment by arthurnn** [comment]
Yes, however that would raise an issue if a rebalance is happening.

**Comment by dasch** [comment]
I don't think that's any different from using `each_message`. [`trigger_heartbeat`](https://rubydoc.info/github/zendesk/ruby-kafka/Kafka/Consumer#trigger_heartbeat-instance_method) _asynchronously_ triggers a heartbeat if necessary, but doesn't block.
