### ISSUE TITLE
Support Reporting Metrics to OpenTelemetry

### ISSUE THREAD

**Issue by gfonseca-tc** [zendesk/ruby-kafka#927]
Since OpenTelemetry is being widely adopted it makes sense to support exporting the metrics in OTel format. I'm not really sure how much work that it, but I'm willing to get this issue to solve, if someone can provide me some guidance.

**Comment by tjwp** [comment]
I believe that this is already supported via one of the OpenTelemetry gems: https://github.com/open-telemetry/opentelemetry-ruby/tree/4a0d233c663d7ae1c02ed649a2958ebf47b63cb1/instrumentation/ruby_kafka

**Comment by gfonseca-tc** [comment]
That's great to hear! I will give a try. Thank you for your prompt response!

**Comment by gfonseca-tc** [comment]
Hey @tjwp, it seems to be only for traces, or at least I've not seen anything else in the code. According to [this doc](https://opentelemetry.io/docs/instrumentation/ruby/#status-and-releases) metrics for ruby is not implemented yet. Do you think it makes sense to implement that there?

**Comment by dasch** [comment]
You can look at the included Datadog metrics reporter and clone that for OT. I don't think OT is yet at a level where I can make it the _only_ metrics reporter and remove the indirection that's currently put in place.
