### ISSUE TITLE
https://ruby-kafka-slack.herokuapp.com is not working. 

### ISSUE THREAD

**Issue by vgnanasekaran** [zendesk/ruby-kafka#968]
Unable to join the slack channel - https://ruby-kafka-slack.herokuapp.com is not working.  

If this is a bug report, please fill out the following:

* Version of Ruby:
* Version of Kafka:
* Version of ruby-kafka:

Please verify that the problem you're seeing hasn't been fixed by the current `master` of ruby-kafka.

###### Steps to reproduce

```ruby
kafka = Kafka.new(...)

# Please write an example that reproduces the problem you're describing.
```

###### Expected outcome

What you thought would happen when running the example.

###### Actual outcome

What actually happened.

**Comment by mensfeld** [comment]
This gem is deprecated: https://github.com/zendesk/ruby-kafka#deprecation-notice hence things may no longer work.

**Comment by vgnanasekaran** [comment]
Thank you for your response.

**Comment by mensfeld** [comment]
@vgnanasekaran  https://join.slack.com/t/ruby-kafka/shared_invite/zt-1mqq84040-seORuxQVQFJddao3dlm71w
