### ISSUE TITLE
Add support for using ssl_ca_cert as string

### ISSUE THREAD

**Issue by davkim** [zendesk/ruby-kafka#975]
The `ruby-kafka` gem supports the use of ssl_ca_cert as string instead of only being able to provide the file name containing it. I believe AvroTurf::Messaging api should also support this option.

**Comment by mensfeld** [comment]
Hey, you may have noticed but this gem is deprecated (stated in the readme). You probably want to use this: https://github.com/appsignal/rdkafka-ruby/ or one of the higher-level libs like:

- https://github.com/karafka/karafka
- https://github.com/zendesk/racecar

**Comment by davkim** [comment]
@mensfeld Actually I've reached here following the documentation on Karafka https://karafka.io/docs/Deserialization/#schema-registry

**Comment by mensfeld** [comment]
@davkim karafka no longer uses ruby-kafka. AvroTurf does not use it as well: https://rubygems.org/gems/avro_turf/versions/1.9.0/dependencies

**Comment by davkim** [comment]
Thanks for the quick responses @mensfeld. How does one use avro schema/schema registry with karafka? Since that's what their documentation tells me to use.

**Comment by mensfeld** [comment]
@davkim I do not quite understand your question.

The karafka docs seem clear on how to use avro schema with karafka and avro_turf is a separate gem: https://rubygems.org/gems/avro_turf

they have nothing to do with ruby-kafka per se (aside from operating in the kafka ecosystem). Add it (avro_turf) to your gemfile, define schemas and follow the readme you linked yourself.

**Comment by davkim** [comment]
@mensfeld My bad, I've posted this issue in a wrong github! I meant to post this to avro-turf to support string value ca cert file like it worked in ruby-kafka. I'm way too tired.

Thanks so much for answering wrong questions, you are a hero

**Comment by mensfeld** [comment]
@davkim it happens to me as well ;) Don't forget to close this issue if it ain't needed anymore :pray:
